import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import test from "node:test";
import ts from "typescript";

const require=createRequire(import.meta.url),source=await readFile(new URL("../lib/purchase-orders/PurchaseOrderRepository.ts",import.meta.url),"utf8"),output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};
new Function("require","exports",output)((name)=>({"server-only":{},"@/lib/supabase-admin":{},"@/lib/brain/CapitalEngine":{},"@/lib/brain/PurchaseIntelligenceEngine":{},"@/lib/catalogue":{},"@/lib/inventory/InventorySyncRepository":{},"@/lib/supplier-style-pack-composition":{},"@/lib/purchase-orders/SupplierOrderPreparation":{}}[name]??require(name)),exports);
const {validateFixedPackSourceProvenance}=exports,po="po-1",fingerprint="a".repeat(32);
const allocation=(over={})=>({purchase_order_line_id:"line-1",variant_id:"variant-1",parent_product_id:"product-1",model_design:"Blue",normalized_size:"S",shopify_variant_id_snapshot:"shopify-variant",shopify_inventory_item_id_snapshot:"shopify-inventory",units_per_pack:5,ordered_units:5,...over});
const snapshot=(source_type="fixed_pack_purchase_recommendation",over={})=>({source_type,supplier_id:"supplier-1",style_id:"style-1",parent_product_id:"product-1",model_design:"Blue",pack_definition_id:"definition-1",recommended_packs:1,recommended_units:5,units_per_pack:5,allocations:[{normalized_size:"S",model_design:"Blue",variant_id:"variant-1",shopify_variant_id_snapshot:"shopify-variant",shopify_inventory_item_id_snapshot:"shopify-inventory",units_per_pack:5,ordered_units:5}],pack_cost_gbp:12.5,line_cost_gbp:12.5,currency:"GBP",fingerprint,recommendation_evidence:{trusted:true},...over});
const line=(source_type="fixed_pack_purchase_recommendation",over={})=>({id:"line-1",supplier_id:"supplier-1",style_id:"style-1",recommended_packs:1,recommended_units:5,units_per_pack:5,pack_cost_gbp:12.5,line_cost_gbp:12.5,source_recommendation_type:source_type,source_snapshot:snapshot(source_type),...over});
const records=[{fingerprint,style_id:"style-1",purchase_order_id:po,purchase_order_line_id:"line-1"}];
const events=(source_type="fixed_pack_purchase_recommendation",snap=snapshot(source_type))=>[{purchase_order_line_id:"line-1",event_type:source_type==="manual_fixed_pack_purchase"?"manual_fixed_pack_added_to_draft":"fixed_pack_recommendation_added_to_draft",event_snapshot:snap}];
const invalid=(...args)=>assert.throws(()=>validateFixedPackSourceProvenance(...args),/SOURCE_PROVENANCE_INVALID/);

test("accepts recommendation, manual, and mixed fixed-pack provenance",()=>{const recommendation=line(),manualSnapshot=snapshot("manual_fixed_pack_purchase",{purchase_order_id:po,pack_definition_updated_at:"2026-01-01T00:00:00Z"}),manual=line("manual_fixed_pack_purchase",{id:"line-2",source_snapshot:manualSnapshot}),manualAllocation={...allocation(),purchase_order_line_id:"line-2"},manualRecord={...records[0],purchase_order_line_id:"line-2"},manualEvent={...events("manual_fixed_pack_purchase",manualSnapshot)[0],purchase_order_line_id:"line-2"};validateFixedPackSourceProvenance(po,[recommendation],[allocation()],records,events());validateFixedPackSourceProvenance(po,[manual],[manualAllocation],[manualRecord],[manualEvent]);validateFixedPackSourceProvenance(po,[recommendation,manual],[allocation(),manualAllocation],[...records,manualRecord],[...events(),manualEvent]);});
test("fails closed on provenance source, fingerprint, and authoritative record defects",()=>{const good=line(),a=[allocation()],s=good.source_snapshot;invalid(po,[{...good,source_recommendation_type:"manual_fixed_pack_purchase"}],a,records,events());invalid(po,[{...good,source_snapshot:null}],a,records,events());invalid(po,[{...good,source_snapshot:{...s,fingerprint:""}}],a,records,events());invalid(po,[{...good,source_snapshot:{...s,fingerprint:"x".repeat(32)}}],a,records,events());invalid(po,[good],a,[...records,...records],events());});
test("detects persisted fact tampering while ignoring presentation metadata",()=>{const good=line(),a=[allocation()],s=good.source_snapshot;for(const changed of [{...good,recommended_packs:2},{...good,source_snapshot:{...s,pack_definition_id:"other"}},{...good,source_snapshot:{...s,allocations:[{...s.allocations[0],units_per_pack:4}]}},{...good,source_snapshot:{...s,allocations:[{...s.allocations[0],shopify_variant_id_snapshot:"other"}]}},{...good,pack_cost_gbp:13}])invalid(po,[changed],a,records,events());validateFixedPackSourceProvenance(po,[{...good,source_snapshot:{...s,productImageUrl:"changed"}}],a,records,events("fixed_pack_purchase_recommendation",{...s,productImageUrl:"original"}));});
test("provenance is after commercial policy and before unsupported approval without demand evaluation",()=>{const branch=source.indexOf('if (sourceFamily === "fixed_pack")'),commercial=source.indexOf("validateFixedPackBasketCommercialPolicy(",branch),provenance=source.indexOf("validateFixedPackSourceProvenance(",commercial+1),unsupported=source.indexOf('throw new Error("FIXED_PACK_APPROVAL_NOT_IMPLEMENTED")',provenance),legacy=source.indexOf("PurchaseIntelligenceEngine.evaluate(",branch);assert.ok(provenance>commercial);assert.ok(unsupported>provenance);assert.ok(legacy>unsupported);});
