import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import test from "node:test";
import ts from "typescript";
const require=createRequire(import.meta.url), source=await readFile(new URL("../lib/purchase-orders/FixedPackDraftRepository.ts",import.meta.url),"utf8"), id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const actionSource=await readFile(new URL("../app/purchase-orders/actions.ts",import.meta.url),"utf8");
function load(deps){const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>deps[n]??require(n),exports);return exports}
const input={styleId:`${id(1)}::Blue`,parentProductId:id(1),idempotencyKey:"key",targetDraftId:id(9)};
const recommendation={kind:"recommendation",recommendation:{supplierId:id(2),styleId:input.styleId,parentProductId:id(1),modelDesign:"Blue",packDefinitionId:"pack",declaredUnitsPerPack:3,commercialUnitsPerPack:3,recommendedPackCount:2,recommendedTotalUnits:6,status:"recommended",trusted:true,blockers:[],warnings:[],reasonCodes:[],totalIdealNeedUnits:6,totalShortageRemainingUnits:0,sizes:[{normalizedSize:"S",unitsPerPack:1,purchasedUnits:2},{normalizedSize:"M",unitsPerPack:2,purchasedUnits:4}]}};
function client(error=null,{supplier={id:id(2),currency_code:"GBP",is_active:true},rule={minimum_order_packs:1},variants=[{id:id(20),product_id:id(1),model_design:"Blue",normalized_size:"S",source:"shopify",source_active:true,identity_resolution_status:"resolved",source_variant_id:"svs",source_inventory_item_id:"iis"},{id:id(21),product_id:id(1),model_design:"Blue",normalized_size:"M",source:"shopify",source_active:true,identity_resolution_status:"resolved",source_variant_id:"svm",source_inventory_item_id:"iim"}]}={}){const calls=[],queries=[],rpcNames=[];const c={from(t){const filters=[];const q={select(){return q},eq(k,v){queries.push([t,k,v]);filters.push([k,v]);return q},maybeSingle(){return Promise.resolve({data:t==="vault_suppliers"?supplier:rule,error:null})},then(r){const data=t==="vault_variants"?variants.filter(variant=>filters.every(([key,value])=>variant[key]===value)):null;return Promise.resolve({data,error:null}).then(r)}};return q},rpc(n,a){rpcNames.push(n);calls.push(a);return Promise.resolve({data:error?null:[{purchase_order_id:id(30),purchase_order_line_id:id(31),created_new_draft:true,created_new_line:true,idempotent:false}],error})}};return{c,calls,queries,rpcNames}}
function deps(results=[recommendation],error=null,options={}){const x=client(error,options),supplierId=options.productSupplierId??results.find(row=>row.kind==="recommendation")?.recommendation.supplierId??id(2),packCost=Object.hasOwn(options,"packCost")?options.packCost:12.5,profit=Object.hasOwn(options,"profit")?options.profit:5,productMoq=Object.hasOwn(options,"productMoq")?options.productMoq:1;return{x,...{loadRecommendations:async()=>results,loadCatalogue:async()=>({products:[{style_id:input.styleId,parent_product_id:id(1),supplier_id:supplierId,product_name:"Product",supplier_moq_packs:productMoq,commercial_cost:{landed_cost_per_pack_gbp:packCost,estimated_gross_profit_per_unit:profit}}]}),client:x.c}}}
test("repository executes authoritative payload construction",async()=>{const d=deps(),r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}});const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,d);assert.equal(result.success,true);assert.equal(d.x.calls[0].authoritative_payload.line_cost_gbp,25);assert.equal(d.x.calls[0].authoritative_payload.expected_profit_gbp,30);assert.equal(d.x.calls[0].authoritative_payload.target_draft_id,id(9));assert.equal(d.x.calls[0].authoritative_payload.allocations[0].variant_id,id(20));});
test("repository fails closed and safely maps B4 refresh",async()=>{const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}});for(const rows of [[],[recommendation,recommendation],[{kind:"unavailable"}]])assert.equal((await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps(rows))).success,false);const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message:"Fixed-pack idempotency key was reused for a different recommendation"}));assert.equal(result.code,"refresh_required");});
test("repository reloads and selects exactly one style plus parent recommendation",async()=>{const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}});let loads=0;const good=deps();good.loadRecommendations=async()=>{loads++;return[recommendation]};assert.equal((await r.addFixedPackRecommendationToDraftFrom(id(7),input,good)).success,true);assert.equal(loads,1);for(const request of [{...input,styleId:"wrong"},{...input,parentProductId:id(8)}]){const d=deps([recommendation]);const result=await r.addFixedPackRecommendationToDraftFrom(id(7),request,d);assert.equal(result.code,"recommendation_unavailable");assert.equal(d.x.calls.length,0)}for(const rows of [[],[recommendation,recommendation]]){const d=deps(rows);const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,d);assert.equal(result.code,"recommendation_unavailable");assert.equal(d.x.calls.length,0)}});
test("unavailable and not_applicable recommendation unions fail closed before RPC",async()=>{const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}});for(const kind of ["unavailable","not_applicable"]){let loads=0;const d=deps();d.loadRecommendations=async()=>{loads++;return[{kind,styleId:input.styleId,parentProductId:input.parentProductId}]};const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,d);assert.equal(loads,1,kind);assert.equal(result.code,"recommendation_unavailable",kind);assert.equal(d.x.calls.length,0,kind)}});
test("untrusted and zero recommendation quantities fail closed before RPC",async()=>{const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}});for(const [label,change] of [["untrusted",{trusted:false}],["zero packs",{recommendedPackCount:0}],["zero units",{recommendedTotalUnits:0}]]){const row={...recommendation,recommendation:{...recommendation.recommendation,...change}};const d=deps([row]);const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,d);assert.equal(result.code,"recommendation_unavailable",label);assert.equal(d.x.calls.length,0,label)}const d=deps();assert.equal(recommendation.recommendation.trusted,true);assert.ok(recommendation.recommendation.recommendedPackCount>0);assert.ok(recommendation.recommendation.recommendedTotalUnits>0);assert.equal((await r.addFixedPackRecommendationToDraftFrom(id(7),input,d)).success,true)});
test("malformed size compositions fail closed before RPC",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),valid=deps();
  assert.equal((await r.addFixedPackRecommendationToDraftFrom(id(7),input,valid)).success,true);
  assert.equal(valid.x.calls.length,1);
  const cases=[
    ["non-positive units per pack",{sizes:[{...recommendation.recommendation.sizes[0],unitsPerPack:0},recommendation.recommendation.sizes[1]]}],
    ["non-positive purchased units",{sizes:[{...recommendation.recommendation.sizes[0],purchasedUnits:0},recommendation.recommendation.sizes[1]]}],
    ["per-size purchased-unit conservation",{sizes:[{...recommendation.recommendation.sizes[0],purchasedUnits:3},recommendation.recommendation.sizes[1]]}],
    ["pack units-per-pack conservation",{declaredUnitsPerPack:4,commercialUnitsPerPack:4}],
    ["recommended-total-units conservation",{recommendedTotalUnits:7}],
  ];
  for(const [label,change] of cases){
    const row={...recommendation,recommendation:{...recommendation.recommendation,...change}},d=deps([row]);let loads=0;
    d.loadRecommendations=async()=>{loads++;return[row]};
    const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,d);
    assert.equal(loads,1,label);assert.equal(result.success,false,label);assert.equal(result.code,"canonical_data_incomplete",label);assert.equal(d.x.calls.length,0,label);
  }
});
test("canonical supplier and currency authority fail closed when absent",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),supplierId=id(42),row={...recommendation,recommendation:{...recommendation.recommendation,supplierId}},browserInput={...input,supplierId:id(99),currency:"USD"};
  const positive=deps([row],null,{supplier:{id:supplierId,currency_code:"EUR",is_active:true}}),accepted=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,positive);
  assert.equal(accepted.success,true);assert.ok(positive.x.queries.some(([table,key,value])=>table==="vault_suppliers"&&key==="id"&&value===supplierId));assert.equal(positive.x.calls[0].authoritative_payload.supplier_id,supplierId);assert.equal(positive.x.calls[0].authoritative_payload.currency,"EUR");assert.notEqual(positive.x.calls[0].authoritative_payload.supplier_id,browserInput.supplierId);assert.notEqual(positive.x.calls[0].authoritative_payload.currency,browserInput.currency);
  for(const [label,supplier] of [["missing supplier",null],["missing currency",{id:supplierId,currency_code:"",is_active:true}]]){
    const d=deps([row],null,{supplier}),result=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,d);
    assert.equal(result.success,false,label);assert.equal(result.code,"canonical_data_incomplete",label);assert.equal(d.x.calls.length,0,label);
  }
});
test("canonical pack cost derives line cost and fails closed when invalid",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),browserInput={...input,packCost:1,lineCost:2},staleRow={...recommendation,recommendation:{...recommendation.recommendation,packCost:1,lineCost:2}};
  const first=deps([staleRow],null,{packCost:17.25}),firstResult=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,first);
  assert.equal(firstResult.success,true);assert.equal(first.x.calls.length,1);assert.equal(first.x.calls[0].authoritative_payload.pack_cost_gbp,17.25);assert.equal(first.x.calls[0].authoritative_payload.line_cost_gbp,34.5);assert.notEqual(first.x.calls[0].authoritative_payload.pack_cost_gbp,browserInput.packCost);assert.notEqual(first.x.calls[0].authoritative_payload.line_cost_gbp,browserInput.lineCost);
  const second=deps([staleRow],null,{packCost:19.1}),secondResult=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,second);
  assert.equal(secondResult.success,true);assert.equal(second.x.calls[0].authoritative_payload.pack_cost_gbp,19.1);assert.equal(second.x.calls[0].authoritative_payload.line_cost_gbp,38.2);
  for(const [label,packCost] of [["missing",null],["zero",0],["negative",-1]]){const d=deps([staleRow],null,{packCost}),result=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,d);assert.equal(result.success,false,label);assert.equal(result.code,"canonical_data_incomplete",label);assert.equal(d.x.calls.length,0,label)}
});
test("canonical expected profit is authoritative and fails closed when missing",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),browserInput={...input,expectedProfit:1},staleRow={...recommendation,recommendation:{...recommendation.recommendation,expectedProfit:1}};
  const first=deps([staleRow],null,{profit:7.25}),firstResult=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,first);
  assert.equal(firstResult.success,true);assert.equal(first.x.calls.length,1);assert.equal(first.x.calls[0].authoritative_payload.expected_profit_gbp,43.5);assert.notEqual(first.x.calls[0].authoritative_payload.expected_profit_gbp,browserInput.expectedProfit);
  const second=deps([staleRow],null,{profit:8}),secondResult=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,second);
  assert.equal(secondResult.success,true);assert.equal(second.x.calls[0].authoritative_payload.expected_profit_gbp,48);
  const missing=deps([staleRow],null,{profit:null}),result=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,missing);
  assert.equal(result.success,false);assert.equal(result.code,"canonical_data_incomplete");assert.equal(missing.x.calls.length,0);
});
test("canonical product and supplier MOQ facts are authoritative",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),browserInput={...input,productMoq:1,supplierMoq:2},staleRow={...recommendation,recommendation:{...recommendation.recommendation,productMoq:1,supplierMoq:2}};
  const first=deps([staleRow],null,{productMoq:7,rule:{minimum_order_packs:13}}),firstResult=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,first),firstPayload=first.x.calls[0].authoritative_payload;
  assert.equal(firstResult.success,true);assert.equal(firstPayload.product_moq_packs,7);assert.equal(firstPayload.source_snapshot.supplier_purchasing_rule.minimum_order_packs,13);assert.notEqual(firstPayload.product_moq_packs,browserInput.productMoq);assert.notEqual(firstPayload.source_snapshot.supplier_purchasing_rule.minimum_order_packs,browserInput.supplierMoq);
  const second=deps([staleRow],null,{productMoq:8,rule:{minimum_order_packs:14}}),secondResult=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,second),secondPayload=second.x.calls[0].authoritative_payload;
  assert.equal(secondResult.success,true);assert.equal(secondPayload.product_moq_packs,8);assert.equal(secondPayload.source_snapshot.supplier_purchasing_rule.minimum_order_packs,14);
  for(const [label,options] of [["missing product MOQ",{productMoq:null}],["missing supplier rule",{rule:null}]]){const d=deps([staleRow],null,options),result=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,d);assert.equal(result.success,false,label);assert.equal(result.code,"canonical_data_incomplete",label);assert.equal(d.x.calls.length,0,label)}
});
test("canonical Shopify variants resolve every size exactly once",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),canonical=[{id:id(20),product_id:id(1),model_design:"Blue",normalized_size:"S",source:"shopify",source_active:true,identity_resolution_status:"resolved",source_variant_id:"svs",source_inventory_item_id:"iis"},{id:id(21),product_id:id(1),model_design:"Blue",normalized_size:"M",source:"shopify",source_active:true,identity_resolution_status:"resolved",source_variant_id:"svm",source_inventory_item_id:"iim"}],browserInput={...input,variantId:id(99),shopifyVariantId:"fake",shopifyInventoryItemId:"fake"},staleRow={...recommendation,recommendation:{...recommendation.recommendation,variantId:id(99)}};
  const positive=deps([staleRow],null,{variants:canonical}),accepted=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,positive),allocations=positive.x.calls[0].authoritative_payload.allocations;
  assert.equal(accepted.success,true);for(const [key,value] of [["product_id",id(1)],["source","shopify"],["source_active",true],["identity_resolution_status","resolved"]])assert.ok(positive.x.queries.some(([table,column,actual])=>table==="vault_variants"&&column===key&&actual===value),key);assert.deepEqual(allocations.map(({variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,normalized_size})=>({variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,normalized_size})),[{variant_id:id(20),shopify_variant_id_snapshot:"svs",shopify_inventory_item_id_snapshot:"iis",normalized_size:"S"},{variant_id:id(21),shopify_variant_id_snapshot:"svm",shopify_inventory_item_id_snapshot:"iim",normalized_size:"M"}]);assert.notEqual(allocations[0].variant_id,browserInput.variantId);
  const replaceM=change=>[canonical[0],{...canonical[1],...change}];
  for(const [label,variants] of [["missing size",[canonical[0]]],["duplicate size",[...canonical,{...canonical[0],id:id(22)}]],["wrong parent",replaceM({product_id:id(8)})],["wrong model",replaceM({model_design:"Other"})],["wrong normalized size",replaceM({normalized_size:"L"})],["non-Shopify source",replaceM({source:"other"})],["inactive",replaceM({source_active:false})],["unresolved identity",replaceM({identity_resolution_status:"unresolved"})],["missing Shopify variant ID",replaceM({source_variant_id:null})],["missing Shopify inventory item ID",replaceM({source_inventory_item_id:null})]]){const d=deps([staleRow],null,{variants}),result=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,d);assert.equal(result.success,false,label);assert.equal(result.code,"canonical_data_incomplete",label);assert.equal(d.x.calls.length,0,label)}
});
test("repository sends exact authoritative allocation payload with conservation",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),browserInput={...input,recommendedPackCount:99,recommendedTotalUnits:999,packCost:1,lineCost:1,expectedProfit:1,productMoq:1,allocations:[]},d=deps(),result=await r.addFixedPackRecommendationToDraftFrom(id(7),browserInput,d),payload=d.x.calls[0].authoritative_payload;
  assert.equal(result.success,true);assert.deepEqual(d.x.rpcNames,["add_fixed_pack_recommendation_to_draft"]);assert.equal(d.x.calls.length,1);
  assert.deepEqual(payload,{operator_id:id(7),style_id:input.styleId,parent_product_id:id(1),supplier_id:id(2),currency:"GBP",idempotency_key:"key",target_draft_id:id(9),product_name:"Product",recommended_packs:2,recommended_units:6,units_per_pack:3,product_moq_packs:1,pack_cost_gbp:12.5,line_cost_gbp:25,expected_profit_gbp:30,source_snapshot:{pack_definition_id:"pack",supplier_purchasing_rule:{minimum_order_packs:1},recommendation_evidence:{trusted:true,reason_codes:[],warnings:[],total_ideal_need_units:6,total_shortage_remaining_units:0}},allocations:[{normalized_size:"S",model_design:"Blue",variant_id:id(20),shopify_variant_id_snapshot:"svs",shopify_inventory_item_id_snapshot:"iis",units_per_pack:1,ordered_units:2},{normalized_size:"M",model_design:"Blue",variant_id:id(21),shopify_variant_id_snapshot:"svm",shopify_inventory_item_id_snapshot:"iim",units_per_pack:2,ordered_units:4}]});
  assert.equal(payload.allocations.reduce((sum,allocation)=>sum+allocation.units_per_pack,0),payload.units_per_pack);assert.ok(payload.allocations.every(allocation=>allocation.ordered_units===payload.recommended_packs*allocation.units_per_pack));assert.equal(payload.allocations.reduce((sum,allocation)=>sum+allocation.ordered_units,0),payload.recommended_units);assert.equal(payload.recommended_units,payload.recommended_packs*payload.units_per_pack);assert.equal(payload.allocations.length,recommendation.recommendation.sizes.length);assert.deepEqual(payload.allocations.map(allocation=>allocation.normalized_size),recommendation.recommendation.sizes.map(size=>size.normalizedSize));
});
test("B4 refresh and changed-recommendation errors map by exact signature",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),idempotencyMessage="Fixed-pack idempotency key was reused for a different recommendation",changedMessage="Fixed-pack recommendation changed; refresh before adding to draft";
  const idempotency=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message:idempotencyMessage}));
  assert.equal(idempotency.code,"refresh_required");assert.doesNotMatch(idempotency.message,new RegExp(idempotencyMessage));
  const changed=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message:changedMessage}));
  assert.equal(changed.code,"changed_recommendation");assert.doesNotMatch(changed.message,new RegExp(changedMessage));
  const logs=[],original=console.error;let nearMiss;console.error=(...entry)=>logs.push(entry);try{nearMiss=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message:"Fixed-pack recommendation changed unexpectedly"}))}finally{console.error=original}
  assert.equal(nearMiss.code,"operation_failed");assert.doesNotMatch(nearMiss.message,/unexpectedly/);assert.ok(logs.some(entry=>entry.some(value=>value?.message==="Fixed-pack recommendation changed unexpectedly")));
});
test("B4 target-selection errors map by exact signature",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),targetMessages=["Explicit fixed-pack draft target is not eligible","Explicit fixed-pack draft target contains incompatible lines"],multipleMessage="Multiple eligible fixed-pack drafts require an explicit target";
  for(const message of targetMessages){const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message}));assert.equal(result.code,"invalid_target_draft");assert.doesNotMatch(result.message,new RegExp(message));}
  const multiple=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message:multipleMessage}));assert.equal(multiple.code,"multiple_eligible_drafts");assert.doesNotMatch(multiple.message,new RegExp(multipleMessage));
  for(const message of ["Explicit fixed-pack draft target changed unexpectedly","Multiple drafts were found"]){const logs=[],original=console.error;let result;console.error=(...entry)=>logs.push(entry);try{result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message}))}finally{console.error=original}assert.equal(result.code,"operation_failed",message);assert.doesNotMatch(result.message,new RegExp(message));assert.ok(logs.some(entry=>entry.some(value=>value?.message===message)),message)}
});
test("B4 canonical-data signatures map before the logged unknown fallback",async()=>{
  const r=load({"server-only":{},"@/lib/catalogue":{},"@/lib/fixed-pack-purchase-recommendations":{},"@/lib/supabase-admin":{}}),canonicalMessages=["Fixed-pack authoritative payload is invalid","Fixed-pack authoritative payload has invalid field types","Fixed-pack authoritative payload is incomplete","Fixed-pack recommended units do not conserve whole packs","Fixed-pack allocations do not conserve the authoritative recommendation","Fixed-pack allocation variant is not a current resolved canonical style variant","Fixed-pack supplier was not found"];
  for(const message of canonicalMessages){const result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message}));assert.equal(result.code,"canonical_data_incomplete",message);assert.doesNotMatch(result.message,new RegExp(message));}
  for(const message of ["Fixed-pack authoritative payload is incomplete-ish","synthetic database outage"]){const logs=[],original=console.error;let result;console.error=(...entry)=>logs.push(entry);try{result=await r.addFixedPackRecommendationToDraftFrom(id(7),input,deps([recommendation],{message}))}finally{console.error=original}assert.equal(result.code,"operation_failed",message);assert.doesNotMatch(result.message,new RegExp(message));assert.ok(logs.some(entry=>entry.some(value=>value?.message===message)),message)}
});
function actionHarness({operatorId=id(7),authError=null,repositoryResult={success:true,purchaseOrderId:id(30),purchaseOrderLineId:id(31),createdNewDraft:true,createdNewLine:true,idempotent:false},repositoryError=null}={}){const calls={auth:0,repo:[],paths:[],logs:[]};const out=ts.transpileModule(actionSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>({"next/cache":{revalidatePath:p=>calls.paths.push(p)},"@/lib/auth/operators":{requireAuthenticatedOperator:async()=>{calls.auth++;if(authError)throw authError;return{id:operatorId}}},"@/lib/business/CashLedgerRules":{},"@/lib/purchase-orders/PurchaseOrderRepository":{},"@/lib/purchase-orders/FixedPackDraftRepository":{addFixedPackRecommendationToDraft:async(...a)=>{calls.repo.push(a);if(repositoryError)throw repositoryError;return repositoryResult}}}[n]??require(n)),exports);return{action:async(...args)=>{const original=console.error;console.error=(...log)=>calls.logs.push(log);try{return await exports.addFixedPackRecommendationToDraftAction(...args)}finally{console.error=original}},calls}}
test("action executes auth, strips browser extras, maps success and revalidates",async()=>{const h=actionHarness(),r=await h.action({...input,supplierId:"bad",packCost:1,allocations:[]});assert.equal(r.success,true);assert.equal(h.calls.auth,1);assert.deepEqual(h.calls.repo[0],[id(7),input]);assert.deepEqual(h.calls.paths,["/purchase-intelligence","/purchase-orders",`/purchase-orders/${id(30)}`]);});
test("action rejects invalid locators before repository and suppresses internal errors",async()=>{for(const bad of [{...input,styleId:" "},{...input,parentProductId:"bad"},{...input,targetDraftId:"bad"},{...input,idempotencyKey:" "},{...input,idempotencyKey:"x".repeat(201)}]){const h=actionHarness();const r=await h.action(bad);assert.equal(r.code,"request_invalid");assert.equal(h.calls.repo.length,0)}const h=actionHarness({repositoryError:Error("secret db failure")});const r=await h.action(input);assert.equal(r.code,"operation_failed");assert.doesNotMatch(r.message,/secret/);assert.equal(h.calls.paths.length,0);});
test("action forwards omitted target without invention",async()=>{const h=actionHarness(),{targetDraftId,...omitted}=input,r=await h.action(omitted);assert.equal(r.success,true);assert.equal(h.calls.auth,1);assert.equal(h.calls.repo.length,1);assert.equal(h.calls.repo[0][0],id(7));assert.equal(h.calls.repo[0][1].targetDraftId,null);});
test("action returns safe repository failures without revalidation",async()=>{const h=actionHarness({repositoryResult:{success:false,code:"recommendation_unavailable",message:"Refresh"}}),r=await h.action(input);assert.equal(r.code,"recommendation_unavailable");assert.equal(h.calls.repo.length,1);assert.deepEqual(h.calls.paths,[]);});
test("action stops cleanly on auth failure",async()=>{const h=actionHarness({authError:Error("auth unavailable")}),r=await h.action(input);assert.equal(h.calls.auth,1);assert.equal(h.calls.repo.length,0);assert.deepEqual(h.calls.paths,[]);assert.equal(r.code,"operation_failed");});
test("action captures original internal error only in server logging",async()=>{const h=actionHarness({repositoryError:Error("secret db failure")}),r=await h.action(input);assert.equal(r.code,"operation_failed");assert.doesNotMatch(r.message,/secret/);assert.equal(h.calls.repo.length,1);assert.equal(h.calls.paths.length,0);assert.ok(h.calls.logs.some(log=>log.some(value=>String(value).includes("secret db failure"))));});
