import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import test from "node:test";

const migration = await readFile(new URL("../../../supabase/migrations/20260919000000_fixed_pack_receipt_allocation_foundation.sql", import.meta.url), "utf8");
const container = `vault-b22b-${process.pid}`;
const id = (n) => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
let started = false;
function docker(args, input) { const result = spawnSync("docker", args, { input, encoding: "utf8" }); if (result.status) throw Error(result.stderr || result.stdout); return result.stdout.trim(); }
function sql(text) { return docker(["exec", "-i", container, "psql", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "b22b", "-t", "-A"], text); }
function fails(text) { const result = spawnSync("docker", ["exec", "-i", container, "psql", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "b22b", "-t", "-A"], { input: text, encoding: "utf8" }); assert.notEqual(result.status, 0); return result.stderr; }

test("B22B links fixed-pack receipt allocations without weakening legacy receiving", async (t) => {
  t.after(() => { if (started) docker(["rm", "-f", container]); });
  docker(["run", "--rm", "-d", "--name", container, "-e", "POSTGRES_PASSWORD=x", "-e", "POSTGRES_DB=b22b", "postgres:17"]); started = true;
  for (let i = 0; i < 40; i++) { try { sql("select 1"); break; } catch { if (i === 39) throw Error("database not ready"); await new Promise((resolve) => setTimeout(resolve, 250)); } }
  sql(`create extension pgcrypto;create role anon;create role authenticated;create table public.vault_variants(id uuid primary key);create table public.vault_purchase_orders(id uuid primary key);create table public.vault_purchase_order_lines(id uuid primary key,purchase_order_id uuid not null references public.vault_purchase_orders(id));create table public.vault_purchase_order_receipts(id uuid primary key);create table public.vault_purchase_order_receipt_lines(id uuid primary key,receipt_id uuid not null references public.vault_purchase_order_receipts(id),purchase_order_line_id uuid not null references public.vault_purchase_order_lines(id),quantity_received integer not null,non_sellable_quantity integer not null default 0);create table public.vault_purchase_order_line_size_allocations(id uuid primary key,purchase_order_line_id uuid not null references public.vault_purchase_order_lines(id),parent_product_id uuid not null,model_design text not null,normalized_size text not null,variant_id uuid not null references public.vault_variants(id),shopify_variant_id_snapshot text not null,shopify_inventory_item_id_snapshot text not null,units_per_pack integer not null,ordered_units integer not null);create table public.vault_purchase_order_receipt_allocations(id uuid primary key default gen_random_uuid(),receipt_line_id uuid not null references public.vault_purchase_order_receipt_lines(id),variant_id uuid not null references public.vault_variants(id),shopify_variant_id_snapshot text not null,shopify_inventory_item_id_snapshot text not null,quantity_received integer not null check(quantity_received>0),created_at timestamptz not null default now(),unique(receipt_line_id,variant_id));create table public.vault_purchase_order_inventory_posting_lines(id uuid primary key default gen_random_uuid(),receipt_allocation_id uuid not null references public.vault_purchase_order_receipt_allocations(id));alter table public.vault_purchase_order_receipt_allocations enable row level security;revoke all on public.vault_purchase_order_receipt_allocations from anon,authenticated;insert into public.vault_variants values('${id(1)}'),('${id(2)}');insert into public.vault_purchase_orders values('${id(10)}'),('${id(11)}');insert into public.vault_purchase_order_lines values('${id(20)}','${id(10)}'),('${id(21)}','${id(11)}');insert into public.vault_purchase_order_receipts values('${id(30)}'),('${id(31)}'),('${id(32)}'),('${id(33)}');insert into public.vault_purchase_order_receipt_lines values('${id(40)}','${id(30)}','${id(20)}',1,0),('${id(41)}','${id(31)}','${id(20)}',1,0),('${id(42)}','${id(32)}','${id(21)}',1,0),('${id(43)}','${id(33)}','${id(20)}',1,0);insert into public.vault_purchase_order_line_size_allocations values('${id(50)}','${id(20)}','${id(60)}','Blue','S','${id(1)}','sv-s','ii-s',1,3),('${id(51)}','${id(20)}','${id(60)}','Blue','M','${id(2)}','sv-m','ii-m',1,2),('${id(52)}','${id(21)}','${id(61)}','Blue','S','${id(1)}','sv-s','ii-s',1,2);`);
  sql(migration);
  sql(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received) values('${id(40)}','${id(2)}','legacy','legacy-item',1);`);
  assert.equal(sql(`select purchase_order_line_size_allocation_id is null and non_sellable_quantity=0 from public.vault_purchase_order_receipt_allocations where shopify_variant_id_snapshot='legacy'`), "t");
  sql(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received,non_sellable_quantity,purchase_order_line_size_allocation_id) values('${id(40)}','${id(1)}','sv-s','ii-s',1,1,'${id(50)}'),('${id(41)}','${id(1)}','sv-s','ii-s',1,0,'${id(50)}');`);
  assert.equal(sql(`select sum(quantity_received+non_sellable_quantity) from public.vault_purchase_order_receipt_allocations where purchase_order_line_size_allocation_id='${id(50)}'`), "3");
  assert.match(fails(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received,purchase_order_line_size_allocation_id) values('${id(40)}','${id(1)}','sv-s','ii-s',1,'${id(50)}');`), /Physical receipt exceeds/);
  assert.match(fails(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received,purchase_order_line_size_allocation_id) values('${id(42)}','${id(1)}','sv-s','ii-s',1,'${id(50)}');`), /same purchase-order line/);
  assert.match(fails(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received,purchase_order_line_size_allocation_id) values('${id(40)}','${id(2)}','sv-s','ii-s',1,'${id(50)}');`), /variant must exactly match/);
  assert.match(fails(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received,purchase_order_line_size_allocation_id) values('${id(40)}','${id(2)}','sv-wrong','ii-m',1,'${id(51)}');`), /Shopify variant snapshot/);
  sql(`insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received,purchase_order_line_size_allocation_id) values('${id(43)}','${id(2)}','sv-m','ii-m',2,'${id(51)}');`);
  assert.equal(sql(`select count(*) from public.vault_purchase_order_inventory_posting_lines`), "0");
  assert.match(fails(`set role authenticated;insert into public.vault_purchase_order_receipt_allocations(receipt_line_id,variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot,quantity_received) values('${id(40)}','${id(1)}','x','y',1);`), /permission denied/);
  assert.match(migration, /before insert/);
  assert.match(migration, /revoke insert, update, delete/);
});
