import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import test from "node:test";

const allocationsMigration = await readFile(new URL("../../../supabase/migrations/20260914000000_fixed_pack_purchase_order_allocations.sql", import.meta.url), "utf8");
const migration = await readFile(new URL("../../../supabase/migrations/20260915000000_fixed_pack_add_to_draft.sql", import.meta.url), "utf8");
const container = `vault-3d5b4b-${process.pid}`;
const id = (n) => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
let started = false;
function docker(args, input) { const r = spawnSync("docker", args, { input, encoding: "utf8" }); if (r.status) throw Error(r.stderr || r.stdout); return r.stdout.trim(); }
function sql(text) { return docker(["exec", "-i", container, "psql", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "phase3d5b4b", "-t", "-A"], text); }
function invoke(payload) { return sql(`select purchase_order_id || '|' || purchase_order_line_id || '|' || created_new_draft || '|' || created_new_line || '|' || idempotent from public.add_fixed_pack_recommendation_to_draft($json$${JSON.stringify(payload)}$json$::jsonb);`); }

test("fixed-pack add-to-draft RPC is atomic, canonical and idempotent", async (t) => {
  t.after(() => { if (started) spawnSync("docker", ["rm", "-f", container]); });
  docker(["run", "--rm", "-d", "--name", container, "-e", "POSTGRES_PASSWORD=x", "-e", "POSTGRES_DB=phase3d5b4b", "postgres:17"]); started = true;
  for (let i = 0; i < 40; i++) { try { sql("select 1"); break; } catch { if (i === 39) throw Error("database not ready"); await new Promise((r) => setTimeout(r, 250)); } }
  sql(`create extension pgcrypto;create role anon;create role authenticated;create role service_role;create table public.vault_operators(id uuid primary key,is_active boolean not null);create table public.vault_suppliers(id uuid primary key);create table public.vault_purchase_orders(id uuid primary key default gen_random_uuid(),supplier_id uuid not null references public.vault_suppliers(id),status text not null,currency text not null,estimated_total_gbp numeric,total_packs integer,recommended_by_vault_brain boolean,created_by_operator_id uuid references public.vault_operators(id),idempotency_key text,source_snapshot jsonb not null default '{}'::jsonb);create table public.vault_variants(id uuid primary key,product_id uuid not null,source text not null,source_active boolean not null,identity_resolution_status text not null,model_design text,normalized_size text,source_variant_id text,source_inventory_item_id text);create table public.vault_purchase_order_lines(id uuid primary key default gen_random_uuid(),purchase_order_id uuid not null references public.vault_purchase_orders(id),supplier_id uuid not null,style_id text not null,product_name text not null,recommended_packs integer not null check(recommended_packs>0),recommended_units integer,units_per_pack integer,product_moq_packs integer,pack_cost_gbp numeric(12,2),line_cost_gbp numeric(12,2),expected_profit_gbp numeric(12,2),source_recommendation_type text not null default 'advisor',source_snapshot jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),unique(purchase_order_id,style_id));create function public.set_vault_commercial_updated_at() returns trigger language plpgsql as $$begin new.updated_at:=now();return new;end$$;insert into public.vault_operators values('${id(1)}',true),('${id(2)}',true),('${id(4)}',true);insert into public.vault_suppliers values('${id(2)}'),('${id(3)}'),('${id(4)}');insert into public.vault_variants values('${id(20)}','${id(10)}','shopify',true,'resolved','Blue','S','sv-s','ii-s'),('${id(21)}','${id(10)}','shopify',true,'resolved','Blue','M','sv-m','ii-m'),('${id(22)}','${id(11)}','shopify',true,'resolved','Blue','L','sv-l','ii-l'),('${id(23)}','${id(10)}','shopify',false,'resolved','Blue','L','sv-old','ii-old'),('${id(24)}','${id(10)}','shopify',true,'unresolved','Blue','L','sv-u','ii-u');`);
  sql(allocationsMigration); sql(migration);
  const base = (key = "key-1") => ({ operator_id:id(1), style_id:`${id(10)}::Blue`, parent_product_id:id(10), supplier_id:id(2), currency:"GBP", idempotency_key:key, product_name:"Product", recommended_packs:2, recommended_units:6, units_per_pack:3, product_moq_packs:1, pack_cost_gbp:12.5, line_cost_gbp:25, expected_profit_gbp:50, source_snapshot:{pack_definition_id:"pack-v1",supplier_purchasing_rule:{minimum_packs:1},recommendation_evidence:{demand_window_days:30}}, allocations:[{normalized_size:"S",model_design:"Blue",variant_id:id(20),shopify_variant_id_snapshot:"sv-s",shopify_inventory_item_id_snapshot:"ii-s",units_per_pack:1,ordered_units:2},{normalized_size:"M",model_design:"Blue",variant_id:id(21),shopify_variant_id_snapshot:"sv-m",shopify_inventory_item_id_snapshot:"ii-m",units_per_pack:2,ordered_units:4}] });
  const first = invoke(base()); const [po,line] = first.split("|");
  assert.match(first, /\|true\|true\|false$/); assert.equal(sql("select count(*) from public.vault_purchase_orders"),"1"); assert.equal(sql("select count(*) from public.vault_purchase_order_lines"),"1"); assert.equal(sql("select count(*) from public.vault_purchase_order_line_size_allocations"),"2"); assert.equal(sql("select count(*) from public.vault_purchase_order_events"),"1"); assert.equal(sql(`select recommended_units from public.vault_purchase_order_lines where id='${line}'`),"6"); assert.equal(sql(`select sum(ordered_units) from public.vault_purchase_order_line_size_allocations where purchase_order_line_id='${line}'`),"6");
  const assertCanonicalSnapshot=(snapshot)=>{ assert.equal(snapshot.source_type,"fixed_pack_purchase_recommendation"); assert.equal(snapshot.supplier_id,id(2)); assert.equal(snapshot.style_id,`${id(10)}::Blue`); assert.equal(snapshot.parent_product_id,id(10)); assert.equal(snapshot.model_design,"Blue"); assert.equal(snapshot.product_name,"Product"); assert.equal(snapshot.pack_definition_id,"pack-v1"); assert.equal(Number(snapshot.recommended_packs),2); assert.equal(Number(snapshot.recommended_units),6); assert.equal(Number(snapshot.units_per_pack),3); assert.equal(Number(snapshot.pack_cost_gbp),12.5); assert.equal(Number(snapshot.line_cost_gbp),25); assert.equal(Number(snapshot.expected_profit_gbp),50); assert.equal(Number(snapshot.product_moq_packs),1); assert.equal(snapshot.currency,"GBP"); assert.deepEqual(snapshot.supplier_purchasing_rule,{minimum_packs:1}); assert.deepEqual(snapshot.recommendation_evidence,{demand_window_days:30}); assert.deepEqual(snapshot.allocations,[...base().allocations].sort((a,b)=>a.normalized_size.localeCompare(b.normalized_size))); };
  const lineSnapshot=JSON.parse(sql(`select source_snapshot::text from public.vault_purchase_order_lines where id='${line}'`)); assertCanonicalSnapshot(lineSnapshot);
  const eventSnapshot=JSON.parse(sql(`select event_snapshot::text from public.vault_purchase_order_events where purchase_order_line_id='${line}'`)); assertCanonicalSnapshot(eventSnapshot); assert.match(eventSnapshot.fingerprint,/^[a-f0-9]{32}$/);
  assert.equal(sql(`select event_snapshot = (select source_snapshot from public.vault_purchase_order_lines where id='${line}') and event_snapshot->>'fingerprint' is not null from public.vault_purchase_order_events where purchase_order_line_id='${line}'`),"t");
  assert.match(invoke(base()), new RegExp(`^${po}\\|${line}\\|false\\|false\\|true$`)); assert.equal(sql("select count(*) from public.vault_purchase_order_events"),"1");
  const changed=base("key-2"); changed.recommended_packs=3; changed.recommended_units=9; changed.allocations[0].ordered_units=3; changed.allocations[1].ordered_units=6; assert.throws(()=>invoke(changed),/refresh before adding/); assert.throws(()=>invoke({...base(),style_id:`${id(10)}::Other`}),/idempotency key was reused/);
  const changedIdempotencyCost=base(); changedIdempotencyCost.line_cost_gbp=26; assert.throws(()=>invoke(changedIdempotencyCost),/idempotency key was reused/);
  const changedStyleCost=base("key-cost"); changedStyleCost.line_cost_gbp=26; assert.throws(()=>invoke(changedStyleCost),/refresh before adding/);
  const changedProvenance=base("key-provenance"); changedProvenance.source_snapshot.recommendation_evidence.demand_window_days=60; assert.throws(()=>invoke(changedProvenance),/refresh before adding/);
  const wrongSupplier=base("key-3"); sql(`insert into public.vault_purchase_orders(id,supplier_id,status,currency,created_by_operator_id,source_snapshot) values('${id(30)}','${id(3)}','draft','GBP','${id(1)}','{}');`); invoke(wrongSupplier); assert.equal(sql("select count(*) from public.vault_purchase_orders"),"2");
  sql(`insert into public.vault_purchase_orders(id,supplier_id,status,currency,created_by_operator_id,source_snapshot) values('${id(31)}','${id(2)}','draft','USD','${id(1)}','{}');`); const target=base("key-4"); target.target_draft_id=id(31); assert.throws(()=>invoke(target),/not eligible/);
  const legacy=base("key-5"); sql(`insert into public.vault_purchase_orders(id,supplier_id,status,currency,created_by_operator_id,source_snapshot) values('${id(32)}','${id(2)}','draft','GBP','${id(1)}','{}');insert into public.vault_purchase_order_lines(purchase_order_id,supplier_id,style_id,product_name,recommended_packs,source_recommendation_type) values('${id(32)}','${id(2)}','legacy','Legacy',1,'advisor');insert into public.vault_purchase_orders(id,supplier_id,status,currency,created_by_operator_id,source_snapshot) values('${id(33)}','${id(2)}','draft','GBP','${id(1)}','{}');`); assert.equal(sql(`select count(*) from public.vault_purchase_orders po where po.created_by_operator_id='${id(1)}' and po.status='draft' and po.supplier_id='${id(2)}' and po.currency='GBP' and not exists (select 1 from public.vault_purchase_order_lines l where l.purchase_order_id=po.id and l.source_recommendation_type <> 'fixed_pack_purchase_recommendation')`),"2"); assert.throws(()=>invoke(legacy),/Multiple eligible/); const explicit=base("key-6"); explicit.target_draft_id=po; assert.match(invoke(explicit),new RegExp(`^${po}\\|${line}\\|false\\|false\\|true$`)); sql(`delete from public.vault_purchase_orders where id='${id(33)}';`);
  const zero=base("key-zero"); zero.recommended_packs=0; zero.recommended_units=0; zero.allocations.forEach((a)=>a.ordered_units=0); assert.throws(()=>invoke(zero),/incomplete/);
  const mismatch=base("key-mismatch"); mismatch.recommended_units=5; assert.throws(()=>invoke(mismatch),/do not conserve/);
  // Use an explicit, otherwise eligible empty draft: the primary draft already
  // contains this style, so its authoritative fingerprint guard must remain
  // the first rejection in that context.
  const badVariantTarget=id(34); sql(`insert into public.vault_purchase_orders(id,supplier_id,status,currency,created_by_operator_id,source_snapshot) values('${badVariantTarget}','${id(3)}','draft','GBP','${id(2)}','{}');`);
  const badVariant=base("key-bad"); badVariant.operator_id=id(2); badVariant.supplier_id=id(3); badVariant.target_draft_id=badVariantTarget; badVariant.allocations[0].variant_id=id(22);
  assert.equal(sql(`select count(*) from public.vault_purchase_orders po where po.created_by_operator_id='${id(2)}' and po.status='draft' and po.supplier_id='${id(3)}' and po.currency='GBP' and not exists (select 1 from public.vault_purchase_order_lines l where l.purchase_order_id=po.id and l.source_recommendation_type <> 'fixed_pack_purchase_recommendation')`),"1");
  assert.equal(sql(`select count(*) from public.vault_purchase_order_lines where purchase_order_id='${badVariantTarget}' and style_id='${badVariant.style_id}'`),"0");
  assert.equal(sql(`select count(*) from public.vault_variants where id='${id(22)}' and source='shopify' and source_active=true and identity_resolution_status='resolved'`),"1");
  assert.equal(sql(`select count(*) from public.vault_variants where id='${id(22)}' and product_id <> '${badVariant.parent_product_id}'`),"1");
  const rejectedLineCount=sql("select count(*) from public.vault_purchase_order_lines"); const rejectedAllocationCount=sql("select count(*) from public.vault_purchase_order_line_size_allocations"); const rejectedEventCount=sql("select count(*) from public.vault_purchase_order_events"); const rejectedLedgerCount=sql("select count(*) from public.vault_fixed_pack_draft_idempotency");
  assert.throws(()=>invoke(badVariant),/canonical style variant/);
  assert.equal(sql("select count(*) from public.vault_purchase_order_lines"),rejectedLineCount); assert.equal(sql("select count(*) from public.vault_purchase_order_line_size_allocations"),rejectedAllocationCount); assert.equal(sql("select count(*) from public.vault_purchase_order_events"),rejectedEventCount); assert.equal(sql("select count(*) from public.vault_fixed_pack_draft_idempotency"),rejectedLedgerCount);
  const autoRollback=base("key-bad-auto"); autoRollback.operator_id=id(4); autoRollback.supplier_id=id(4); autoRollback.allocations[0].variant_id=id(22);
  assert.equal(sql(`select count(*) from public.vault_purchase_orders where created_by_operator_id='${id(4)}' and supplier_id='${id(4)}' and status='draft' and currency='GBP'`),"0");
  const autoOrderCount=sql("select count(*) from public.vault_purchase_orders"); const autoLineCount=sql("select count(*) from public.vault_purchase_order_lines"); const autoAllocationCount=sql("select count(*) from public.vault_purchase_order_line_size_allocations"); const autoEventCount=sql("select count(*) from public.vault_purchase_order_events"); const autoLedgerCount=sql("select count(*) from public.vault_fixed_pack_draft_idempotency");
  assert.throws(()=>invoke(autoRollback),/canonical style variant/);
  assert.equal(sql("select count(*) from public.vault_purchase_orders"),autoOrderCount); assert.equal(sql("select count(*) from public.vault_purchase_order_lines"),autoLineCount); assert.equal(sql("select count(*) from public.vault_purchase_order_line_size_allocations"),autoAllocationCount); assert.equal(sql("select count(*) from public.vault_purchase_order_events"),autoEventCount); assert.equal(sql("select count(*) from public.vault_fixed_pack_draft_idempotency"),autoLedgerCount); assert.equal(sql(`select count(*) from public.vault_purchase_orders where created_by_operator_id='${id(4)}' and supplier_id='${id(4)}' and status='draft' and currency='GBP'`),"0");
  assert.throws(()=>sql(`set role authenticated;select * from public.add_fixed_pack_recommendation_to_draft($json$${JSON.stringify(base("direct"))}$json$::jsonb);`));
  assert.equal(sql(`select count(*) from public.vault_fixed_pack_draft_idempotency where operator_id='${id(1)}' and idempotency_key='key-1' and purchase_order_id='${po}'`),"1");
});
