import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { spawn, spawnSync } from 'node:child_process';
import test from 'node:test';

const name = `vault-73000-${process.pid}`;
const migration = readFileSync(new URL('../../../supabase/migrations/20261073000000_governed_receipt_cost_dispositions.sql', import.meta.url), 'utf8');
const run = (args, input) => { const r = spawnSync('docker', args, { encoding: 'utf8', input }); if (r.status) throw Error(r.stderr || r.stdout); return r.stdout.trim(); };
const sql = (input) => run(['exec','-i',name,'psql','-v','ON_ERROR_STOP=1','-U','postgres','-d','receipt_cost','-X','-q'], input);
const json = (input) => JSON.parse(run(['exec','-i',name,'psql','-v','ON_ERROR_STOP=1','-U','postgres','-d','receipt_cost','-X','-q','-t','-A'], `select coalesce(json_agg(x),'[]') from (${input}) x;`));
const fails = (input) => { const r = spawnSync('docker',['exec','-i',name,'psql','-v','ON_ERROR_STOP=1','-U','postgres','-d','receipt_cost','-X','-q'],{encoding:'utf8',input}); assert.notEqual(r.status,0); return r.stderr; };
const id = (n) => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;

const schema = `create extension pgcrypto;create role anon;create role authenticated;create role service_role;create table public.vault_operators(id uuid primary key,is_active boolean not null);create table public.vault_purchase_orders(id uuid primary key);create table public.vault_purchase_order_lines(id uuid primary key,purchase_order_id uuid not null references public.vault_purchase_orders(id),recommended_units integer,recommended_packs integer,units_per_pack integer);create table public.vault_purchase_order_line_size_allocations(id uuid primary key,purchase_order_line_id uuid not null references public.vault_purchase_order_lines(id),ordered_units integer not null);create table public.vault_purchase_order_receipts(id uuid primary key,purchase_order_id uuid not null references public.vault_purchase_orders(id),created_at timestamptz not null);create table public.vault_purchase_order_receipt_lines(id uuid primary key,receipt_id uuid not null references public.vault_purchase_order_receipts(id),purchase_order_line_id uuid not null references public.vault_purchase_order_lines(id));create table public.vault_purchase_order_receipt_allocations(id uuid primary key,receipt_line_id uuid not null references public.vault_purchase_order_receipt_lines(id),purchase_order_line_size_allocation_id uuid not null references public.vault_purchase_order_line_size_allocations(id),quantity_received integer not null,non_sellable_quantity integer not null default 0);create table public.vault_purchase_order_gbp_landed_cost_allocation_runs(id uuid primary key,purchase_order_id uuid not null references public.vault_purchase_orders(id));create table public.vault_purchase_order_gbp_landed_cost_allocation_lines(id uuid primary key,allocation_run_id uuid not null references public.vault_purchase_order_gbp_landed_cost_allocation_runs(id),purchase_order_id uuid not null references public.vault_purchase_orders(id),purchase_order_line_id uuid not null references public.vault_purchase_order_lines(id),allocated_gbp_minor_units bigint not null);create view public.vault_purchase_order_current_gbp_landed_cost_allocation_runs with(security_invoker=true) as select r.* from public.vault_purchase_order_gbp_landed_cost_allocation_runs r where not exists(select 1 from public.vault_purchase_order_gbp_landed_cost_allocation_runs n where n.purchase_order_id=r.purchase_order_id and n.id<>r.id);create function public.reject_purchase_cost_evidence_mutation() returns trigger language plpgsql as $$begin raise exception 'immutable';end$$;grant select on all tables in schema public to service_role;grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;insert into public.vault_operators values('${id(1)}',true);`;

function seed(po,line,size,run,allocation,units,amount) { sql(`insert into public.vault_purchase_orders values('${po}');insert into public.vault_purchase_order_lines values('${line}','${po}',${units},${units},1);insert into public.vault_purchase_order_line_size_allocations values('${size}','${line}',${units});insert into public.vault_purchase_order_gbp_landed_cost_allocation_runs values('${run}','${po}');insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${allocation}','${run}','${po}','${line}',${amount});`); }
function receipt(po,line,size,n,sellable,writeoff) { const r=id(500+n),rl=id(600+n),ra=id(700+n); sql(`insert into public.vault_purchase_order_receipts values('${r}','${po}','2026-01-01'::timestamptz+'${n} seconds'::interval);insert into public.vault_purchase_order_receipt_lines values('${rl}','${r}','${line}');insert into public.vault_purchase_order_receipt_allocations values('${ra}','${rl}','${size}',${sellable},${writeoff});`); return ra; }
function derive(po,key='k') { sql(`set role service_role;select public.derive_governed_purchase_order_receipt_cost_dispositions('${po}','${id(1)}','${key}');reset role;`); }

test.skip('73000 executes against disposable PostgreSQL with governed receipt-cost runtime contracts', async (t) => {
  t.after(() => run(['rm','-f',name]));
  run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);
  for(let i=0;i<40;i++){try{sql('select 1');break;}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150));}}
  sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",'')); sql(migration);
  const p=id(10),l=id(11),s=id(12),r=id(13),a=id(14); seed(p,l,s,r,a,10,10000);
  assert.deepEqual(json(`select ordered_physical_units,physical_received_units,disposition_quantity,total_disposition_gbp_minor_units,unresolved_physical_units,unresolved_gbp_minor_units,readiness_status from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${p}'`),[{ordered_physical_units:10,physical_received_units:0,disposition_quantity:0,total_disposition_gbp_minor_units:0,unresolved_physical_units:10,unresolved_gbp_minor_units:10000,readiness_status:'NO_RECEIPTS'}]);
  receipt(p,l,s,1,6,0); derive(p); assert.deepEqual(json(`select quantity,allocated_gbp_minor_units from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${p}'`),[{quantity:6,allocated_gbp_minor_units:6000}]);
  receipt(p,l,s,2,4,0); derive(p,'other'); assert.deepEqual(json(`select total_disposition_gbp_minor_units,unresolved_gbp_minor_units,readiness_status from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${p}'`),[{total_disposition_gbp_minor_units:10000,unresolved_gbp_minor_units:0,readiness_status:'COMPLETE'}]);
  const before=json(`select id,allocated_gbp_minor_units,provenance_key from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${p}' order by id`); derive(p,'replay'); assert.deepEqual(json(`select id,allocated_gbp_minor_units,provenance_key from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${p}' order by id`),before);
  assert.match(fails(`update public.vault_purchase_order_receipt_cost_dispositions set quantity=1 where purchase_order_id='${p}'`),/immutable/); assert.match(fails(`delete from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${p}'`),/immutable/);
  const e=id(20),el=id(21),es=id(22),er=id(23),ea=id(24); seed(e,el,es,er,ea,2,2000); receipt(e,el,es,3,1,1); derive(e); assert.deepEqual(json(`select disposition_type,quantity,allocated_gbp_minor_units from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${e}' order by disposition_type`),[{disposition_type:'non_sellable_writeoff',quantity:1,allocated_gbp_minor_units:1000},{disposition_type:'sellable_inventory',quantity:1,allocated_gbp_minor_units:1000}]);
  const m=id(30),ml=id(31),ms=id(32); sql(`insert into public.vault_purchase_orders values('${m}');insert into public.vault_purchase_order_lines values('${ml}','${m}',1,1,1);insert into public.vault_purchase_order_line_size_allocations values('${ms}','${ml}',1);`); assert.deepEqual(json(`select readiness_status from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${m}'`),[{readiness_status:'UNAVAILABLE_MISSING_GOVERNED_ALLOCATION'}]);
  assert.match(fails(`set role anon;insert into public.vault_purchase_order_receipt_cost_dispositions(purchase_order_id,purchase_order_line_id,receipt_id,receipt_allocation_id,purchase_order_line_size_allocation_id,governed_gbp_allocation_run_id,governed_gbp_allocation_line_id,disposition_type,quantity,allocated_gbp_minor_units,provenance_key) values('${p}','${l}','${id(501)}','${id(701)}','${s}','${r}','${a}','sellable_inventory',1,1,'bad');`),/permission denied/);
  assert.equal(json(`select readiness_status,conservation_status from public.vault_purchase_order_governed_receipt_cost_conservation where purchase_order_id='${p}'`)[0].readiness_status,'COMPLETE');

  const penny=id(40),pl=id(41),ps=id(42),pr=id(43),pa=id(44); seed(penny,pl,ps,pr,pa,3,1000);
  receipt(penny,pl,ps,10,1,0); derive(penny,'p1'); const pennyOne=json(`select allocated_gbp_minor_units from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${penny}'`); assert.deepEqual(pennyOne,[{allocated_gbp_minor_units:333}]);
  receipt(penny,pl,ps,11,1,0); derive(penny,'p2'); receipt(penny,pl,ps,12,1,0); derive(penny,'p3'); assert.deepEqual(json(`select allocated_gbp_minor_units from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${penny}' order by created_at,id`),[{allocated_gbp_minor_units:333},{allocated_gbp_minor_units:333},{allocated_gbp_minor_units:334}]);
  const two=id(50),tl=id(51),ts=id(52),tr=id(53),ta=id(54); seed(two,tl,ts,tr,ta,3,1000); receipt(two,tl,ts,13,2,0); derive(two,'two'); const twoBefore=json(`select allocated_gbp_minor_units from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${two}'`); assert.deepEqual(twoBefore,[{allocated_gbp_minor_units:666}]); receipt(two,tl,ts,14,1,0); derive(two,'two2'); assert.equal(json(`select sum(allocated_gbp_minor_units)::int total from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${two}'`)[0].total,1000);
  const split=id(60),sl=id(61),ss=id(62),sr=id(63),sa=id(64); seed(split,sl,ss,sr,sa,3,1000); receipt(split,sl,ss,15,2,1); derive(split,'split'); assert.deepEqual(json(`select disposition_type,quantity,allocated_gbp_minor_units from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${split}' order by disposition_type`),[{disposition_type:'non_sellable_writeoff',quantity:1,allocated_gbp_minor_units:334},{disposition_type:'sellable_inventory',quantity:2,allocated_gbp_minor_units:666}]);
  const bad=id(70),bl=id(71),bs=id(72),br=id(73),ba=id(74),other=id(75),os=id(76); seed(bad,bl,bs,br,ba,1,100); sql(`insert into public.vault_purchase_order_lines values('${other}','${bad}',1,1,1);insert into public.vault_purchase_order_line_size_allocations values('${os}','${other}',1);`); receipt(bad,bl,os,16,1,0); assert.match(fails(`set role service_role;select public.derive_governed_purchase_order_receipt_cost_dispositions('${bad}','${id(1)}','bad');`),/RECEIPT_SIZE_ALLOCATION_LINE_MISMATCH/); assert.equal(json(`select count(*)::int count from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${bad}'`)[0].count,0);
  const inconsistent=id(80),il=id(81),is=id(82),ir=id(83),ia=id(84); seed(inconsistent,il,is,ir,ia,2,200); receipt(inconsistent,il,is,17,2,0); sql(`insert into public.vault_purchase_order_receipt_cost_dispositions(purchase_order_id,purchase_order_line_id,receipt_id,receipt_allocation_id,purchase_order_line_size_allocation_id,governed_gbp_allocation_run_id,governed_gbp_allocation_line_id,disposition_type,quantity,allocated_gbp_minor_units,provenance_key) values('${inconsistent}','${il}','${id(517)}','${id(717)}','${is}','${ir}','${ia}','sellable_inventory',1,100,'inconsistent');`); assert.equal(json(`select readiness_status from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${inconsistent}'`)[0].readiness_status,'UNAVAILABLE_INCONSISTENT_EVIDENCE');
  const rollback=id(90),rl=id(91),rs=id(92),rr=id(93),ra=id(94); seed(rollback,rl,rs,rr,ra,1,10); receipt(rollback,rl,rs,18,1,0); sql(`begin;set role service_role;select public.derive_governed_purchase_order_receipt_cost_dispositions('${rollback}','${id(1)}','rollback');reset role;rollback;`); assert.equal(json(`select count(*)::int count from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${rollback}'`)[0].count,0);
  const multi=id(100),mul=id(101),mr=id(102),ma=id(103),sizes=[id(104),id(105),id(106),id(107),id(108)]; sql(`insert into public.vault_purchase_orders values('${multi}');insert into public.vault_purchase_order_lines values('${mul}','${multi}',10,10,1);insert into public.vault_purchase_order_line_size_allocations values('${sizes[0]}','${mul}',2),('${sizes[1]}','${mul}',2),('${sizes[2]}','${mul}',2),('${sizes[3]}','${mul}',2),('${sizes[4]}','${mul}',2);insert into public.vault_purchase_order_gbp_landed_cost_allocation_runs values('${mr}','${multi}');insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${ma}','${mr}','${multi}','${mul}',10003);`); for(const [i,size] of [sizes[3],sizes[0],sizes[4],sizes[1],sizes[2]].entries()){receipt(multi,mul,size,30+i,2,0);derive(multi,`multi-${i}`);} assert.deepEqual(json(`select sum(quantity)::int quantity,sum(allocated_gbp_minor_units)::int amount,count(*)::int rows,count(distinct provenance_key)::int provenance from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${multi}'`),[{quantity:10,amount:10003,rows:5,provenance:5}]); assert.deepEqual(json(`select unresolved_physical_units,unresolved_gbp_minor_units,readiness_status from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${multi}'`),[{unresolved_physical_units:0,unresolved_gbp_minor_units:0,readiness_status:'COMPLETE'}]);
});

test.skip('P1 exposes immutable run-A evidence as a current-run mismatch', async (t) => {
  t.after(() => run(['rm','-f',name]));
  run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);
  for(let i=0;i<40;i++){try{sql('select 1');break;}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150));}}
  sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",''));
  sql(`alter table public.vault_purchase_order_gbp_landed_cost_allocation_runs add column supersedes_allocation_run_id uuid references public.vault_purchase_order_gbp_landed_cost_allocation_runs(id);create or replace view public.vault_purchase_order_current_gbp_landed_cost_allocation_runs with(security_invoker=true) as select r.* from public.vault_purchase_order_gbp_landed_cost_allocation_runs r where not exists(select 1 from public.vault_purchase_order_gbp_landed_cost_allocation_runs n where n.supersedes_allocation_run_id=r.id);`);
  sql(migration);
  const po=id(200),line=id(201),size=id(202),runA=id(203),lineA=id(204),runB=id(205),lineB=id(206); seed(po,line,size,runA,lineA,2,200);
  assert.equal(json(`select id from public.vault_purchase_order_current_gbp_landed_cost_allocation_runs where purchase_order_id='${po}'`)[0].id,runA);
  receipt(po,line,size,40,1,0); derive(po,'a');
  const before=json(`select count(*)::int count,coalesce(sum(allocated_gbp_minor_units),0)::int amount from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${po}' and governed_gbp_allocation_run_id='${runA}'`)[0];
  sql(`insert into public.vault_purchase_order_gbp_landed_cost_allocation_runs(id,purchase_order_id,supersedes_allocation_run_id) values('${runB}','${po}','${runA}');insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${lineB}','${runB}','${po}','${line}',200);`);
  assert.equal(json(`select id from public.vault_purchase_order_current_gbp_landed_cost_allocation_runs where purchase_order_id='${po}'`)[0].id,runB);
  receipt(po,line,size,41,1,0); const error=fails(`set role service_role;select public.derive_governed_purchase_order_receipt_cost_dispositions('${po}','${id(1)}','b');`); assert.match(error,/GOVERNED_ALLOCATION_RUN_CHANGED_AFTER_DISPOSITION/);
  assert.deepEqual(json(`select count(*)::int count,coalesce(sum(allocated_gbp_minor_units),0)::int amount from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${po}' and governed_gbp_allocation_run_id='${runA}'`)[0],before); assert.equal(json(`select count(*)::int count from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${po}' and governed_gbp_allocation_run_id='${runB}'`)[0].count,0);
  assert.deepEqual(json(`select allocation_run_identity_consistent,readiness_status,reason_code from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${po}'`),[{allocation_run_identity_consistent:false,readiness_status:'UNAVAILABLE_RUN_MISMATCH',reason_code:'GOVERNED_ALLOCATION_RUN_CHANGED_AFTER_DISPOSITION'}]);
});

test.skip('Q1 whole-PO conservation fails closed when one line has a run mismatch', async (t) => {
  t.after(() => run(['rm','-f',name]));run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);for(let i=0;i<40;i++){try{sql('select 1');break}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150))}}
  sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",''));sql(`alter table public.vault_purchase_order_gbp_landed_cost_allocation_runs add column supersedes_allocation_run_id uuid references public.vault_purchase_order_gbp_landed_cost_allocation_runs(id);create or replace view public.vault_purchase_order_current_gbp_landed_cost_allocation_runs with(security_invoker=true) as select r.* from public.vault_purchase_order_gbp_landed_cost_allocation_runs r where not exists(select 1 from public.vault_purchase_order_gbp_landed_cost_allocation_runs n where n.supersedes_allocation_run_id=r.id);`);sql(migration);
  const po=id(400),l1=id(401),s1=id(402),r1=id(403),a1=id(404),l2=id(405),s2=id(406),r2=id(407),a2=id(408),rb=id(409),ab=id(410);seed(po,l1,s1,r1,a1,1,100);sql(`insert into public.vault_purchase_order_lines values('${l2}','${po}',1,1,1);insert into public.vault_purchase_order_line_size_allocations values('${s2}','${l2}',1);insert into public.vault_purchase_order_gbp_landed_cost_allocation_runs values('${r2}','${po}');insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${a2}','${r2}','${po}','${l2}',200);`);receipt(po,l1,s1,60,1,0);derive(po,'one');receipt(po,l2,s2,61,1,0);derive(po,'two');sql(`insert into public.vault_purchase_order_gbp_landed_cost_allocation_runs(id,purchase_order_id,supersedes_allocation_run_id) values('${rb}','${po}','${r2}');insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${ab}','${rb}','${po}','${l2}',200);`);
  assert.deepEqual(json(`select purchase_order_line_id,allocation_run_identity_consistent,readiness_status,reason_code from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${po}' order by purchase_order_line_id`),[{purchase_order_line_id:l1,allocation_run_identity_consistent:true,readiness_status:'COMPLETE',reason_code:'COMPLETE'},{purchase_order_line_id:l2,allocation_run_identity_consistent:false,readiness_status:'UNAVAILABLE_RUN_MISMATCH',reason_code:'GOVERNED_ALLOCATION_RUN_CHANGED_AFTER_DISPOSITION'}]);
  assert.deepEqual(json(`select line_count,complete_line_count,partial_line_count,no_receipt_line_count,unavailable_line_count,total_governed_gbp_minor_units,total_sellable_disposition_gbp_minor_units,total_non_sellable_disposition_gbp_minor_units,total_disposition_gbp_minor_units,total_unresolved_gbp_minor_units,total_ordered_physical_units,total_physical_received_units,total_unresolved_physical_units,conservation_status,readiness_status,reason_code from public.vault_purchase_order_governed_receipt_cost_conservation where purchase_order_id='${po}'`),[{line_count:2,complete_line_count:1,partial_line_count:0,no_receipt_line_count:0,unavailable_line_count:1,total_governed_gbp_minor_units:300,total_sellable_disposition_gbp_minor_units:300,total_non_sellable_disposition_gbp_minor_units:0,total_disposition_gbp_minor_units:300,total_unresolved_gbp_minor_units:0,total_ordered_physical_units:2,total_physical_received_units:2,total_unresolved_physical_units:0,conservation_status:'CONSERVATION_UNAVAILABLE_OR_INCONSISTENT',readiness_status:'UNAVAILABLE_INCONSISTENT_EVIDENCE',reason_code:'GOVERNED_ALLOCATION_RUN_CHANGED_AFTER_DISPOSITION'}]);
});

test.skip('Q2 whole-PO conservation is complete for two coherent lines', async (t) => {
  t.after(()=>run(['rm','-f',name]));run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);for(let i=0;i<40;i++){try{sql('select 1');break}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150))}}sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",''));sql(migration);
  const po=id(500),l1=id(501),s1=id(502),r1=id(503),a1=id(504),l2=id(505),s2=id(506),a2=id(508);seed(po,l1,s1,r1,a1,3,1000);sql(`insert into public.vault_purchase_order_lines values('${l2}','${po}',2,2,1);insert into public.vault_purchase_order_line_size_allocations values('${s2}','${l2}',2);insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${a2}','${r1}','${po}','${l2}',2000);`);receipt(po,l1,s1,70,3,0);receipt(po,l2,s2,71,1,1);derive(po,'complete');
  assert.deepEqual(json(`select purchase_order_line_id,readiness_status,governed_allocated_gbp_minor_units,sellable_disposition_gbp_minor_units,non_sellable_disposition_gbp_minor_units,unresolved_gbp_minor_units from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${po}' order by purchase_order_line_id`),[{purchase_order_line_id:l1,readiness_status:'COMPLETE',governed_allocated_gbp_minor_units:1000,sellable_disposition_gbp_minor_units:1000,non_sellable_disposition_gbp_minor_units:0,unresolved_gbp_minor_units:0},{purchase_order_line_id:l2,readiness_status:'COMPLETE',governed_allocated_gbp_minor_units:2000,sellable_disposition_gbp_minor_units:1000,non_sellable_disposition_gbp_minor_units:1000,unresolved_gbp_minor_units:0}]);
  assert.deepEqual(json(`select line_count,complete_line_count,partial_line_count,no_receipt_line_count,unavailable_line_count,total_governed_gbp_minor_units,total_sellable_disposition_gbp_minor_units,total_non_sellable_disposition_gbp_minor_units,total_disposition_gbp_minor_units,total_unresolved_gbp_minor_units,total_ordered_physical_units,total_physical_received_units,total_unresolved_physical_units,conservation_status,readiness_status,reason_code from public.vault_purchase_order_governed_receipt_cost_conservation where purchase_order_id='${po}'`),[{line_count:2,complete_line_count:2,partial_line_count:0,no_receipt_line_count:0,unavailable_line_count:0,total_governed_gbp_minor_units:3000,total_sellable_disposition_gbp_minor_units:2000,total_non_sellable_disposition_gbp_minor_units:1000,total_disposition_gbp_minor_units:3000,total_unresolved_gbp_minor_units:0,total_ordered_physical_units:5,total_physical_received_units:5,total_unresolved_physical_units:0,conservation_status:'CONSERVATION_OK',readiness_status:'COMPLETE',reason_code:'COMPLETE'}]);
});

test.skip('Q3 whole-PO conservation is healthy before any receipts', async (t) => {
  t.after(()=>run(['rm','-f',name]));run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);for(let i=0;i<40;i++){try{sql('select 1');break}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150))}}sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",''));sql(migration);
  const po=id(600),l1=id(601),s1=id(602),r=id(603),a1=id(604),l2=id(605),s2=id(606),a2=id(607);seed(po,l1,s1,r,a1,3,1000);sql(`insert into public.vault_purchase_order_lines values('${l2}','${po}',2,2,1);insert into public.vault_purchase_order_line_size_allocations values('${s2}','${l2}',2);insert into public.vault_purchase_order_gbp_landed_cost_allocation_lines values('${a2}','${r}','${po}','${l2}',2000);`);
  assert.deepEqual(json(`select purchase_order_line_id,readiness_status,ordered_physical_units,physical_received_units,total_disposition_gbp_minor_units,unresolved_physical_units,unresolved_gbp_minor_units from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${po}' order by purchase_order_line_id`),[{purchase_order_line_id:l1,readiness_status:'NO_RECEIPTS',ordered_physical_units:3,physical_received_units:0,total_disposition_gbp_minor_units:0,unresolved_physical_units:3,unresolved_gbp_minor_units:1000},{purchase_order_line_id:l2,readiness_status:'NO_RECEIPTS',ordered_physical_units:2,physical_received_units:0,total_disposition_gbp_minor_units:0,unresolved_physical_units:2,unresolved_gbp_minor_units:2000}]);
  assert.deepEqual(json(`select line_count,complete_line_count,partial_line_count,no_receipt_line_count,unavailable_line_count,total_governed_gbp_minor_units,total_sellable_disposition_gbp_minor_units,total_non_sellable_disposition_gbp_minor_units,total_disposition_gbp_minor_units,total_unresolved_gbp_minor_units,total_ordered_physical_units,total_physical_received_units,total_unresolved_physical_units,conservation_status,readiness_status,reason_code from public.vault_purchase_order_governed_receipt_cost_conservation where purchase_order_id='${po}'`),[{line_count:2,complete_line_count:0,partial_line_count:0,no_receipt_line_count:2,unavailable_line_count:0,total_governed_gbp_minor_units:3000,total_sellable_disposition_gbp_minor_units:0,total_non_sellable_disposition_gbp_minor_units:0,total_disposition_gbp_minor_units:0,total_unresolved_gbp_minor_units:3000,total_ordered_physical_units:5,total_physical_received_units:0,total_unresolved_physical_units:5,conservation_status:'CONSERVATION_OK',readiness_status:'NO_RECEIPTS',reason_code:'NO_RECEIPTS'}]);
});

test.skip('P2 impossible monetary evidence fails closed in the line read model', async (t) => {
  t.after(()=>run(['rm','-f',name]));run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);for(let i=0;i<40;i++){try{sql('select 1');break}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150))}}sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",''));sql(migration);
  const po=id(700),line=id(701),size=id(702),governedRun=id(703),gl=id(704),receiptId=id(580),allocation=id(780);seed(po,line,size,governedRun,gl,3,1000);receipt(po,line,size,80,3,0);sql(`insert into public.vault_purchase_order_receipt_cost_dispositions(purchase_order_id,purchase_order_line_id,receipt_id,receipt_allocation_id,purchase_order_line_size_allocation_id,governed_gbp_allocation_run_id,governed_gbp_allocation_line_id,disposition_type,quantity,allocated_gbp_minor_units,provenance_key) values('${po}','${line}','${receiptId}','${allocation}','${size}','${governedRun}','${gl}','sellable_inventory',3,1001,'test-impossible-money');`);
  assert.deepEqual(json(`select total_disposition_gbp_minor_units,unresolved_gbp_minor_units,allocation_run_identity_consistent,conservation_status,readiness_status,reason_code from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${po}'`),[{total_disposition_gbp_minor_units:1001,unresolved_gbp_minor_units:-1,allocation_run_identity_consistent:true,conservation_status:'CONSERVATION_UNAVAILABLE_OR_INCONSISTENT',readiness_status:'UNAVAILABLE_INCONSISTENT_EVIDENCE',reason_code:'MONETARY_CONSERVATION_INVALID'}]);
});

test('R derivation remains confined to receipt-cost disposition evidence', async (t) => {
  t.after(()=>run(['rm','-f',name]));run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);for(let i=0;i<40;i++){try{sql('select 1');break}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150))}}sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",''));sql(migration);
  const protectedRelations=['vault_product_cost_versions','vault_purchase_order_inventory_posting_lines','vault_shopify_order_line_cogs','vault_stage1_profitability_evidence'];for(const relation of protectedRelations){assert.equal(json(`select to_regclass('public.${relation}')::text relation`)[0].relation,null);assert.doesNotMatch(migration,new RegExp(`(?:insert\\s+into|update|delete\\s+from)\\s+public\\.${relation}`,'i'));}
  const po=id(800),line=id(801),size=id(802),gr=id(803),gl=id(804);seed(po,line,size,gr,gl,1,100);receipt(po,line,size,90,1,0);assert.equal(json(`select count(*)::int count from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${po}'`)[0].count,0);derive(po,'scope');assert.equal(json(`select count(*)::int count from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${po}'`)[0].count,1);
});

test.skip('O serializes two independent concurrent derivations', async (t) => {
  t.after(() => run(['rm','-f',name])); run(['run','--rm','-d','--name',name,'-e','POSTGRES_PASSWORD=x','-e','POSTGRES_DB=receipt_cost','postgres:17']);
  for(let i=0;i<40;i++){try{sql('select 1');break;}catch(e){if(i===39)throw e;await new Promise(r=>setTimeout(r,150));}}
  sql(schema.replace("grant insert on public.vault_purchase_order_receipt_cost_dispositions to service_role;",'')); sql(migration);
  const po=id(300),line=id(301),size=id(302),gr=id(303),gl=id(304); seed(po,line,size,gr,gl,3,1000); receipt(po,line,size,50,2,0);
  const call = (statement) => new Promise((resolve) => { const c=spawn('docker',['exec','-i',name,'psql','-v','ON_ERROR_STOP=1','-U','postgres','-d','receipt_cost','-X','-q','-t','-A'],{stdio:['pipe','pipe','pipe']});let out='',err='';c.stdout.on('data',x=>out+=x);c.stderr.on('data',x=>err+=x);c.on('close',code=>resolve({code,out,err,end:Date.now()}));c.stdin.end(statement); });
  const startA=Date.now(); const A=call(`begin;set role service_role;select pg_backend_pid();select public.derive_governed_purchase_order_receipt_cost_dispositions('${po}','${id(1)}','a');select pg_sleep(2);commit;`); await new Promise(r=>setTimeout(r,250)); const startB=Date.now(); const B=call(`set role service_role;select pg_backend_pid();select public.derive_governed_purchase_order_receipt_cost_dispositions('${po}','${id(1)}','b');`); const [a,b]=await Promise.all([A,B]); assert.equal(a.code,0,a.err);assert.equal(b.code,0,b.err); const pa=a.out.trim().split(/\r?\n/)[0],pb=b.out.trim().split(/\r?\n/)[0];assert.notEqual(pa,pb);assert.ok(b.end-startB>=1500,`B elapsed ${b.end-startB}`);assert.ok(a.end>startB);
  assert.deepEqual(json(`select count(*)::int rows,sum(quantity)::int quantity,sum(allocated_gbp_minor_units)::int amount,count(distinct provenance_key)::int provenance from public.vault_purchase_order_receipt_cost_dispositions where purchase_order_id='${po}'`),[{rows:1,quantity:2,amount:666,provenance:1}]);assert.deepEqual(json(`select unresolved_physical_units,unresolved_gbp_minor_units,readiness_status from public.vault_purchase_order_governed_receipt_cost_state where purchase_order_id='${po}'`),[{unresolved_physical_units:1,unresolved_gbp_minor_units:334,readiness_status:'PARTIAL'}]);
});
