import assert from 'node:assert/strict'; import test from 'node:test'; import {readFile} from 'node:fs/promises'; import ts from 'typescript';
const root=new URL('../../../',import.meta.url); const sql=await readFile(new URL('supabase/migrations/20261102000000_historical_c2_reconciliation_framework.sql',root),'utf8'); const edge=await readFile(new URL('supabase/functions/shopify-historical-c2-reconciliation/index.ts',root),'utf8');
const financial=await readFile(new URL('supabase/functions/_shared/shopify/financial-evidence.ts',root),'utf8'); const financialExports={}; new Function('exports',ts.transpileModule(financial,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(financialExports);
const shared=await readFile(new URL('supabase/functions/_shared/shopify/historical-c2-reconciliation.ts',root),'utf8'); const sharedExports={}; new Function('exports','require',ts.transpileModule(shared,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(sharedExports,(path)=>{if(path==='./financial-evidence.ts')return financialExports;throw new Error(`Unexpected import: ${path}`);}); const {mapHistoricalC2DryRunResponse}=sharedExports;
function edgeHandler(planItems){let handler;const hashQueue=planItems.filter((item)=>item.required_hash).map(({id,payload})=>({id,payload}));const client={rpc:async(name,args)=>{assert.equal(name,'prepare_historical_c2_v1');assert.deepEqual(args,{p_order_numbers:['1254'],p_dry_run:true,p_idempotency_key:'http-case'});return {data:{run_id:'run-1',state:'DRY_RUN_COMPLETE',items:hashQueue},error:null};},from:(table)=>({select:()=>table==='vault_shopify_historical_c2_prepared_plan_items'?{eq:(column,value)=>{assert.equal(column,'run_id');assert.equal(value,'run-1');return {order:async()=>({data:planItems,error:null})};}}:{in:async(column,ids)=>({data:ids.map((id)=>({id,order_number:planItems.find((item)=>item.canonical_order_id===id).order_number})),error:null})}})};const output=ts.transpileModule(edge,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('exports','require','Deno',output)({},(path)=>{if(path==='npm:@supabase/supabase-js@2')return {createClient:()=>client};if(path.endsWith('historical-c2-reconciliation.ts'))return sharedExports;throw new Error(`Unexpected import: ${path}`);},{serve:(candidate)=>{handler=candidate;},env:{get:(name)=>name==='VAULT_ORDER_SYNC_SECRET'?'test-secret':name==='SUPABASE_URL'?'http://local':name==='SUPABASE_SERVICE_ROLE_KEY'?'service-role':undefined}});return handler;}
test('C2 is DB prepare, canonical TypeScript hash, then DB finalize',()=>{for(const token of ['prepare_historical_c2_v1','finalize_historical_c2_v1','vault_shopify_historical_c2_prepared_plan_items','PREPARED','DRY_RUN_COMPLETE','ZERO_DISCOUNT_PROOF','C2_ORDER_UNSUPPORTED','C2_PREPARED_PLAN_IMMUTABLE'])assert.ok(sql.includes(token));assert.doesNotMatch(sql,/fnv|2166136261|sourceContentFingerprint/i);});
test('prepare accepts only governed target inputs and finalize accepts no payload',()=>{assert.match(sql,/p_order_numbers text\[\],p_dry_run boolean,p_idempotency_key text/);assert.match(sql,/p_run_id uuid,p_hashes jsonb/);assert.doesNotMatch(sql,/p_manifest|p_evidence|p_payload/);});
function plan(counts){let n=0;return Object.entries(counts).flatMap(([kind,count])=>Array.from({length:count},()=>({id:`plan-${++n}`,order_number:kind==='ZERO_DISCOUNT_PROOF'?'1264':'1254',kind,source_observation_id:`source-${n}`,canonical_order_id:`order-${n}`,canonical_order_line_id:`line-${n}`,completeness_observation_id:`complete-${n}`,payload:{n},required_hash:kind==='ZERO_DISCOUNT_PROOF',expected_source_fingerprint:`fp-${n}`})));}
async function assertEdgeDryRunPlan(counts,expectedTotal,expectedHashQueue){const items=plan(counts);const response=await edgeHandler(items)(new Request('http://local/functions/v1/shopify-historical-c2-reconciliation',{method:'POST',headers:{'content-type':'application/json','x-vault-sync-secret':'test-secret'},body:JSON.stringify({order_numbers:['1254'],dry_run:true,idempotency_key:'http-case'})}));const mapped=await response.json();assert.equal(response.status,200);assert.equal(mapped.items.length,expectedTotal);assert.equal(mapped.hash_attestation_items.length,expectedHashQueue);assert.equal(mapped.items.filter((item)=>item.hash_classification==='REUSABLE').length,expectedTotal-expectedHashQueue);assert.equal(mapped.items.filter((item)=>item.hash_classification==='NEW_HASH_REQUIRED').length,expectedHashQueue);assert.ok(mapped.items.every((item)=>item.order_number&&item.evidence_kind&&item.source_observation_id&&item.canonical_order_id&&item.fingerprint));}
test('Edge HTTP dry-run mapping returns the complete all-reusable Batch 1 plan, not its empty hash queue',async()=>{assert.match(edge,/mapHistoricalC2DryRunResponse/);assert.match(edge,/vault_shopify_historical_c2_prepared_plan_items/);await assertEdgeDryRunPlan({APPLICATION:3,ALLOCATION:6},9,0);});
test('Edge HTTP dry-run mapping separates the 1264 full plan from its one-item hash queue',async()=>{await assertEdgeDryRunPlan({APPLICATION:1,ALLOCATION:2,ZERO_DISCOUNT_PROOF:1},4,1);});
test('Edge HTTP dry-run mapping separates a mixed full plan from its one-item hash queue',async()=>{await assertEdgeDryRunPlan({APPLICATION:2,ALLOCATION:4,ZERO_DISCOUNT_PROOF:1},7,1);});
