import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import test from "node:test";
import ts from "typescript";

const require=createRequire(import.meta.url),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const source=await readFile(new URL("../lib/purchase-orders/ManualFixedPackDraftRepository.ts",import.meta.url),"utf8"),actionSource=await readFile(new URL("../app/purchase-orders/actions.ts",import.meta.url),"utf8");
const input={purchaseOrderId:id(10),parentProductId:id(1),styleId:`${id(1)}::Blue`,packCount:2,idempotencyKey:"manual-key"};
const sizes=["S","M","L","XL","2XL"];
function load(deps){const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>deps[n]??require(n),exports);return exports}
function fixture(over={}){
  const calls=[],po={id:input.purchaseOrderId,status:"draft",supplier_id:id(2),currency:"GBP",created_by_operator_id:id(7),vault_purchase_order_lines:[]},product={style_id:input.styleId,parent_product_id:id(1),supplier_id:id(2),product_name:"Canonical product",supplier_moq_packs:1,restock_enabled:true,inventory_strategy:"continue",commercial_cost:{landed_cost_per_pack_gbp:12.5}},composition=sizes.map((normalized_size)=>({id:"pack-v1",supplier_id:id(2),style_id:input.styleId,parent_product_id:id(1),normalized_size,units_per_pack:1,declared_units_per_pack:5,composition_complete:true,composition_valid:true,commercial_pack_consistent:true,active:true,updated_at:"2026-01-01T00:00:00Z"})),variants=sizes.map((normalized_size,i)=>({id:id(20+i),product_id:id(1),model_design:"Blue",normalized_size,source_variant_id:`sv-${i}`,source_inventory_item_id:`ii-${i}`}));
  const data={po,product,supplier:{id:id(2),is_active:true,currency_code:"GBP"},rule:{supplier_id:id(2),minimum_order_packs:20},composition,variants,rpcError:null,...over};
  const client={from(table){const q={select(){return q},eq(){return q},maybeSingle(){return Promise.resolve({data:table==="vault_purchase_orders"?data.po:table==="vault_suppliers"?data.supplier:data.rule,error:null})},then(resolve){return Promise.resolve({data:table==="vault_supplier_style_pack_composition_intelligence"?data.composition:table==="vault_variants"?data.variants:null,error:null}).then(resolve)}};return q},rpc(name,args){calls.push({name,args});return Promise.resolve({data:data.rpcError?null:[{purchase_order_id:input.purchaseOrderId,purchase_order_line_id:id(99),idempotent:false}],error:data.rpcError})}};
  return {client,loadCatalogue:async()=>({products:[data.product]}),calls,data};
}
const repository=()=>load({"server-only":{},"@/lib/catalogue":{},"@/lib/supabase-admin":{}});
test("repository derives canonical payload and ignores browser authority",async()=>{const d=fixture(),r=repository(),result=await r.addManualFixedPackToDraftFrom(id(7),{...input,supplierId:"evil",currency:"EUR",packCost:1,allocations:[],recommendedUnits:999},d);assert.equal(result.success,true);const payload=d.calls[0].args.authoritative_payload;assert.equal(d.calls[0].name,"add_manual_fixed_pack_to_draft");assert.equal(payload.supplier_id,id(2));assert.equal(payload.currency,"GBP");assert.equal(payload.pack_cost_gbp,12.5);assert.equal(payload.recommended_units,10);assert.equal(payload.line_cost_gbp,25);assert.equal(payload.source_type,"manual_fixed_pack_purchase");assert.equal(payload.supplier_purchasing_rule.minimum_order_packs,20);assert.equal(payload.allocations.length,5);assert.ok(!("supplierId" in payload));assert.ok(!("recommendedUnits" in payload));assert.equal(payload.fingerprint,(await r.buildManualFixedPackPayloadFrom(id(7),input,d)).fingerprint);});
test("zero recommendation is not a prerequisite and canonical changes alter fingerprint",async()=>{const r=repository(),a=fixture(),b=fixture({product:{...fixture().data.product,commercial_cost:{landed_cost_per_pack_gbp:14}}});const pa=await r.buildManualFixedPackPayloadFrom(id(7),input,a),pb=await r.buildManualFixedPackPayloadFrom(id(7),input,b);assert.equal((await r.addManualFixedPackToDraftFrom(id(7),input,a)).success,true);assert.notEqual(pa.fingerprint,pb.fingerprint);assert.notEqual(pa.line_cost_gbp,pb.line_cost_gbp);});
test("repository fails closed before RPC for policy, contract, identity, commercial, and count defects",async()=>{const r=repository();const cases=[
  ["restock",{product:{...fixture().data.product,restock_enabled:false}}],["do not restock",{product:{...fixture().data.product,inventory_strategy:"do_not_restock"}}],["missing pack",{composition:[]}],["ambiguous pack",{composition:[...fixture().data.composition,{...fixture().data.composition[0],id:"pack-v2"}]}],["duplicate size",{composition:[...fixture().data.composition,{...fixture().data.composition[0]}]}],["missing size",{composition:fixture().data.composition.slice(0,4)}],["missing variant",{variants:fixture().data.variants.slice(0,4)}],["duplicate variant",{variants:[...fixture().data.variants,{...fixture().data.variants[0],id:id(88)}]}],["missing Shopify id",{variants:[{...fixture().data.variants[0],source_variant_id:null},...fixture().data.variants.slice(1)]}],["cost",{product:{...fixture().data.product,commercial_cost:{landed_cost_per_pack_gbp:null}}}],["product MOQ",{product:{...fixture().data.product,supplier_moq_packs:3}}],["inactive supplier",{supplier:{id:id(2),is_active:false,currency_code:"GBP"}}],["supplier currency",{supplier:{id:id(2),is_active:true,currency_code:"EUR"}}],["PO currency",{po:{...fixture().data.po,currency:"EUR"}}],["not draft",{po:{...fixture().data.po,status:"approved"}}],["legacy basket",{po:{...fixture().data.po,vault_purchase_order_lines:[{style_id:"x",source_recommendation_type:"manual"}]}}]
];for(const [label,over] of cases){const d=fixture(over),result=await r.addManualFixedPackToDraftFrom(id(7),input,d);assert.equal(result.success,false,label);assert.equal(d.calls.length,0,label)}for(const packCount of [0,-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1]){const d=fixture(),result=await r.addManualFixedPackToDraftFrom(id(7),{...input,packCount},d);assert.equal(result.success,false,String(packCount));assert.equal(d.calls.length,0)}});
test("deterministic RPC errors are safe and idempotent results pass through",async()=>{const r=repository();for(const [message,code] of [["Manual fixed-pack style already exists in draft","style_already_in_draft"],["Manual fixed-pack idempotency conflict","idempotency_conflict"]]){const result=await r.addManualFixedPackToDraftFrom(id(7),input,fixture({rpcError:{message}}));assert.equal(result.code,code);assert.doesNotMatch(result.message,new RegExp(message))}const unknown=await r.addManualFixedPackToDraftFrom(id(7),input,fixture({rpcError:{message:"constraint secret"}}));assert.equal(unknown.code,"operation_failed");assert.doesNotMatch(unknown.message,/secret/);const d=fixture();d.client.rpc=()=>Promise.resolve({data:[{purchase_order_id:input.purchaseOrderId,purchase_order_line_id:id(99),idempotent:true}],error:null});assert.deepEqual(await r.addManualFixedPackToDraftFrom(id(7),input,d),{success:true,purchaseOrderId:input.purchaseOrderId,purchaseOrderLineId:id(99),idempotent:true});});
function actionHarness({operator=id(7),authError=null,result={success:true,purchaseOrderId:input.purchaseOrderId,purchaseOrderLineId:id(99),idempotent:false}}={}){const calls={auth:0,repo:[],paths:[]},out=ts.transpileModule(actionSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>({"next/cache":{revalidatePath:p=>calls.paths.push(p)},"@/lib/auth/operators":{requireAuthenticatedOperator:async()=>{calls.auth++;if(authError)throw authError;return{id:operator}}},"@/lib/business/CashLedgerRules":{},"@/lib/purchase-orders/PurchaseOrderRepository":{},"@/lib/purchase-orders/FixedPackDraftRepository":{},"@/lib/purchase-orders/ManualFixedPackDraftRepository":{addManualFixedPackToDraft:async(...args)=>{calls.repo.push(args);return result}}}[n]??require(n)),exports);return{calls,action:exports.addManualFixedPackToDraftAction}}
test("server action authenticates, strips extras, validates locator-only input, and has no side effects",async()=>{const h=actionHarness(),response=await h.action({...input,supplierId:"evil",currency:"EUR",cost:1,allocations:[],operatorId:id(8)});assert.equal(response.success,true);assert.equal(h.calls.auth,1);assert.deepEqual(h.calls.repo,[[id(7),input]]);assert.deepEqual(h.calls.paths,["/purchase-orders",`/purchase-orders/${input.purchaseOrderId}`]);for(const bad of [{...input,purchaseOrderId:"bad"},{...input,parentProductId:"bad"},{...input,styleId:""},{...input,idempotencyKey:""},{...input,packCount:0},{...input,packCount:1.5}]){const x=actionHarness(),result=await x.action(bad);assert.equal(result.code,"request_invalid");assert.equal(x.calls.repo.length,0)}const unauth=actionHarness({authError:Error("no auth")}),failure=await unauth.action(input);assert.equal(failure.code,"operation_failed");assert.equal(unauth.calls.repo.length,0);});
