import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import test from "node:test";
import ts from "typescript";
const require=createRequire(import.meta.url),source=await readFile(new URL("../lib/purchase-orders/ManualFixedPackCandidates.ts",import.meta.url),"utf8"),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
function load(){const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>({"server-only":{},"@/lib/catalogue":{},"@/lib/supabase-admin":{},"@/lib/supplier-style-pack-composition":{}}[n]??require(n)),exports);return exports}
function deps(over={}){const supplier={id:id(2),supplier_name:"Exclusive",is_active:true,currency_code:"GBP"},po={id:id(10),status:"draft",currency:"GBP",supplier_id:id(2),vault_purchase_order_lines:[{style_id:"existing",recommended_packs:6,source_recommendation_type:"fixed_pack_purchase_recommendation"}]},sizes=over.sizes??[["S",1],["M",1],["L",1],["XL",1],["2XL",1]],product={style_id:`${id(1)}::Blue`,parent_product_id:id(1),supplier_id:id(2),product_name:"Alpha",supplier_moq_packs:1,restock_enabled:true,inventory_strategy:"continue",commercial_cost:{landed_cost_per_pack_gbp:12.5}},composition=sizes.map(([normalized_size,units_per_pack])=>({id:"pack",supplier_id:id(2),style_id:product.style_id,parent_product_id:id(1),normalized_size,units_per_pack,declared_units_per_pack:sizes.reduce((s,x)=>s+x[1],0),composition_complete:true,composition_valid:true,commercial_pack_consistent:true,active:true})),variants=sizes.map(([normalized_size],i)=>({id:id(20+i),product_id:id(1),model_design:"Blue",normalized_size,source_variant_id:`sv${i}`,source_inventory_item_id:`ii${i}`})),data={supplier,po,product,composition,variants,rule:{minimum_order_packs:20},...over};const client={from(table){const q={select(){return q},eq(){return q},maybeSingle(){return Promise.resolve({data:table==="vault_purchase_orders"?data.po:table==="vault_suppliers"?data.supplier:data.rule,error:null})},then(resolve){return Promise.resolve({data:table==="vault_variants"?data.variants:null,error:null}).then(resolve)}};return q}};return{client,product:data.product,composition:data.composition,variants:data.variants,po:data.po,supplier:data.supplier,loadCatalogue:async()=>({products:[data.product,...(data.extraProducts??[])]}),loadComposition:async()=>data.composition}}
test("candidate loader uses canonical supplier styles, explicit shapes, and MOQ presentation without recommendation state",async()=>{const r=load(),d=deps(),x=await r.loadManualFixedPackCandidatesFrom(id(10),d);assert.equal(x.status,"compatible");assert.equal(x.currentBasketPacks,6);assert.equal(x.remainingPacksToMinimum,14);assert.equal(x.candidates.length,1);assert.deepEqual(x.candidates[0].composition.map(x=>x.normalizedSize),["S","M","L","XL","2XL"]);assert.equal(x.candidates[0].unitsPerPack,5);});
test("candidate loader excludes invalid presentation candidates and incompatible drafts",async()=>{const r=load();for(const over of [{product:{...deps().product,restock_enabled:false}},{product:{...deps().product,inventory_strategy:"do_not_restock"}},{composition:[]},{composition:[...deps().composition,{...deps().composition[0]}]},{variants:deps().variants.slice(0,4)},{variants:[...deps().variants,{...deps().variants[0],id:id(99)}]},{variants:[{...deps().variants[0],source_variant_id:null},...deps().variants.slice(1)]},{po:{...deps().po,vault_purchase_order_lines:[{style_id:deps().product.style_id,recommended_packs:1,source_recommendation_type:"manual_fixed_pack_purchase"}]}}]){const x=await r.loadManualFixedPackCandidatesFrom(id(10),deps(over));assert.equal(x.status,"compatible");assert.equal(x.candidates.length,0)}for(const [over,reason] of [[{supplier:{...deps().supplier,currency_code:"EUR"}},"currency_not_gbp"],[{supplier:{...deps().supplier,is_active:false}},"supplier_inactive"],[{po:{...deps().po,status:"approved"}},"po_not_draft"],[{po:{...deps().po,vault_purchase_order_lines:[{style_id:"x",recommended_packs:1,source_recommendation_type:"purchase_intelligence_required"}]}},"po_not_fixed_pack_compatible"]])assert.equal((await r.loadManualFixedPackCandidatesFrom(id(10),deps(over))).reason,reason);});
test("six-unit and nonuniform explicit pack shapes are preserved",async()=>{const r=load();for(const sizes of [[["S",1],["M",1],["L",1],["XL",1],["2XL",1],["3XL",1]],[["S",2],["M",1],["L",3]]]){const x=await r.loadManualFixedPackCandidatesFrom(id(10),deps({sizes}));assert.equal(x.candidates[0].unitsPerPack,sizes.reduce((sum,row)=>sum+row[1],0));assert.deepEqual(x.candidates[0].composition.map(row=>row.unitsPerPack),sizes.map(row=>row[1]));}});
