import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import test from "node:test";
import ts from "typescript";

const require=createRequire(import.meta.url), id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const source=await readFile(new URL("../lib/purchase-orders/PendingCatalogueDraftRepository.ts",import.meta.url),"utf8");
const actionSource=await readFile(new URL("../app/purchase-orders/actions.ts",import.meta.url),"utf8");
const input={purchaseOrderId:id(1),workingTitle:"New tee",supplierReference:"SUP-1",brand:"Vault",productCategory:"Tee",colourModel:"Black",modelDesign:"Black",notes:"",orderedUnits:5,unitCostGbp:4.5,sizes:[{supplierSizeLabel:"S",normalizedSize:"S",orderedUnits:2},{supplierSizeLabel:"M",normalizedSize:"M",orderedUnits:3}],idempotencyKey:"pending-key"};
function load(deps){const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>deps[n]??require(n),exports);return exports}
function fixture(over={}){const calls=[],data={po:{id:input.purchaseOrderId,status:"draft",supplier_id:id(2),created_by_operator_id:id(7),vault_purchase_order_lines:[]},supplier:{id:id(2),is_active:true},rpcError:null,...over};const client={from(table){const q={select(){return q},eq(){return q},maybeSingle(){return Promise.resolve({data:table==="vault_purchase_orders"?data.po:data.supplier,error:null})}};return q},rpc(name,args){calls.push({name,args});return Promise.resolve({data:data.rpcError?null:[{purchase_order_id:input.purchaseOrderId,purchase_order_line_id:id(3),pending_catalogue_product_id:id(4),idempotent:false}],error:data.rpcError})}};return{client,calls,data}}
const repository=()=>load({"server-only":{},"@/lib/supabase-admin":{}});

test("pending draft repository validates exact sizes and sends only pending evidence to its atomic RPC",async()=>{const d=fixture(),r=repository(),result=await r.addPendingCatalogueProductToDraftFrom(id(7),input,d);assert.equal(result.success,true);assert.equal(d.calls[0].name,"create_pending_catalogue_purchase_line");const p=d.calls[0].args.authoritative_payload;assert.equal(p.supplier_id,id(2));assert.equal(p.ordered_units,5);assert.equal(p.unit_cost_gbp,4.5);assert.deepEqual(p.sizes,[{supplier_size_label:"S",normalized_size:"S",ordered_units:2},{supplier_size_label:"M",normalized_size:"M",ordered_units:3}]);assert.ok(!("variant_id" in p));assert.ok(!("shopify_variant_id_snapshot" in p));assert.ok(!("shopify_inventory_item_id_snapshot" in p));});
test("pending draft repository rejects invalid allocation conservation and incompatible drafts before the RPC",async()=>{const r=repository();for(const bad of [{...input,sizes:[{...input.sizes[0],orderedUnits:4}]},{...input,sizes:[input.sizes[0],{...input.sizes[0],orderedUnits:3}]},{...input,sizes:[{...input.sizes[0],orderedUnits:0},input.sizes[1]]},{...input,orderedUnits:0}]){const d=fixture(),x=await r.addPendingCatalogueProductToDraftFrom(id(7),bad,d);assert.equal(x.success,false);assert.equal(d.calls.length,0)}for(const po of [{...fixture().data.po,status:"approved"},{...fixture().data.po,vault_purchase_order_lines:[{source_recommendation_type:"manual_fixed_pack_purchase"}]}]){const d=fixture({po}),x=await r.addPendingCatalogueProductToDraftFrom(id(7),input,d);assert.equal(x.success,false);assert.equal(d.calls.length,0)}});
test("pending draft migration remains atomic, pending-only, and service-role-only",async()=>{const sql=await readFile(new URL("../../../supabase/migrations/20260925000000_pending_catalogue_draft_creation.sql",import.meta.url),"utf8");assert.match(sql,/create or replace function public\.create_pending_catalogue_purchase_line\(authoritative_payload jsonb\)/);assert.match(sql,/PENDING_CATALOGUE_ALLOCATION_INVALID/);assert.match(sql,/source_recommendation_type<>'pending_catalogue_purchase'/);assert.match(sql,/identity_mode,model_design,normalized_size/);assert.match(sql,/revoke all on function public\.create_pending_catalogue_purchase_line\(jsonb\) from public,anon,authenticated/);assert.match(sql,/grant execute on function public\.create_pending_catalogue_purchase_line\(jsonb\) to service_role/);assert.doesNotMatch(sql,/shopify_variant_id_snapshot/);});
test("pending server action authenticates and approval dispatch keeps pending, fixed, and unknown sources separate",async()=>{const calls=[];const out=ts.transpileModule(actionSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exports={};new Function("require","exports",out)(n=>({"next/cache":{revalidatePath:p=>calls.push(p)},"@/lib/auth/operators":{requireAuthenticatedOperator:async()=>({id:id(7)})},"@/lib/business/CashLedgerRules":{},"@/lib/purchase-orders/PurchaseOrderRepository":{},"@/lib/purchase-orders/FixedPackDraftRepository":{},"@/lib/purchase-orders/ManualFixedPackDraftRepository":{},"@/lib/purchase-orders/PendingCatalogueLinkRepository":{},"@/lib/purchase-orders/PendingCatalogueDraftRepository":{addPendingCatalogueProductToDraft:async(...args)=>{calls.push(args);return{success:true,purchaseOrderId:input.purchaseOrderId,purchaseOrderLineId:id(3),pendingCatalogueProductId:id(4),idempotent:false}}}}[n]??require(n)),exports);const result=await exports.addPendingCatalogueProductToDraftAction(input);assert.equal(result.success,true);assert.deepEqual(calls[0],[id(7),input]);const approval=await readFile(new URL("../lib/purchase-orders/PurchaseOrderRepository.ts",import.meta.url),"utf8");assert.match(approval,/sourceFamily === "pending_catalogue"[\s\S]*approve_pending_catalogue_purchase_order/);assert.match(approval,/sourceFamily === "fixed_pack"[\s\S]*approve_fixed_pack_vault_purchase_order/);assert.match(approval,/PO_SOURCE_MIX_INVALID/);});
