import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import ts from "typescript";
import * as XLSX from "xlsx";

const normalize = (value) => { const text = String(value ?? "").trim().replace(/^#/, ""); return /^\d+$/.test(text) && Number(text) > 0 ? text.replace(/^0+(?=\d)/, "") : null; };
const parse = (bytes) => { const workbook = XLSX.read(bytes, { type: "array" }); const sheet = workbook.Sheets.Sales; const data = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: false, defval: "" }); const headerRow = data.findIndex((row) => row[0] === "Product") + 1; return { valid: headerRow > 0, rowCount: data.length - headerRow, rows: data.slice(headerRow).map((cells, index) => ({ rowNumber: headerRow + index + 1, orderNumber: normalize(cells[11]) })) }; };
async function writer() { const source = await readFile(new URL("../lib/sales-workbook/TrackingRepairWriter.ts", import.meta.url), "utf8"); const executable = source.replace('import "server-only";', "").replace('import * as XLSX from "xlsx";', 'const XLSX=(globalThis).__xlsx;').replace(/import \{ normalizeWorkbookOrderNumber, parseSalesWorkbook \} from "\.\/WorkbookParser";/, 'const normalizeWorkbookOrderNumber=(globalThis).__normalize; const parseSalesWorkbook=(globalThis).__parse;'); globalThis.__xlsx=XLSX; globalThis.__normalize=normalize; globalThis.__parse=parse; const javascript=ts.transpileModule(executable,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText; return import(`data:text/javascript;base64,${Buffer.from(javascript).toString("base64")}`); }
function bytes(){const workbook=XLSX.utils.book_new();const sales=XLSX.utils.aoa_to_sheet([["SALES"],["Product","Sale Price","Cost","Unit COGS","Postage fee","Card Fee","Profit","Posted","Tracking","","date of sale","order number"],["A",10,1,2,1,1,5,"Complete","","","1/1/26","1257"],["B",10,1,2,1,1,5,"Complete","","","1/1/26","1257"],["C",10,1,2,1,1,5,"Complete","OLD","","2/1/26","1260"]]);XLSX.utils.book_append_sheet(workbook,sales,"Sales");XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([["keep",{f:"1+1",v:2}]]),"Costings");XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([["keep"]]),"Dashboard");return new Uint8Array(XLSX.write(workbook,{bookType:"xlsx",type:"array"}));}
test("tracking repair changes only blank tracking cells for a whole proven order group",async()=>{const api=await writer(),before=bytes(),result=api.prepareSalesWorkbookTrackingRepair(before,["1257","1260"],new Map([["1257",["AA001"]],["1260",["NEW"]]]));assert.deepEqual(result.eligibleOrderNumbers,["1257"]);assert.deepEqual(result.blockedOrderNumbers,["1260"]);assert.equal(result.rowsUpdated,2);const verification=api.verifySalesWorkbookTrackingRepairPreservation(before,result.bytes,new Map([[3,"AA001"],[4,"AA001"]]));assert.equal(verification.valid,true,verification.errors.join("; "));});
test("missing and ambiguous evidence do not write; already-correct tracking remains untouched",async()=>{const api=await writer(),before=bytes(),result=api.prepareSalesWorkbookTrackingRepair(before,["1257","1260"],new Map([["1257",["AA001"]],["1260",[]]]));assert.equal(result.skippedNoTracking,1);assert.equal(result.rowsUpdated,2);const ambiguous=api.prepareSalesWorkbookTrackingRepair(before,["1257"],new Map([["1257",["AA001","BB002"]]]));assert.equal(ambiguous.rowsUpdated,0);assert.equal(ambiguous.skippedAmbiguousTracking,1);const rerun=api.prepareSalesWorkbookTrackingRepair(result.bytes,["1257"],new Map([["1257",["AA001"]]]));assert.equal(rerun.rowsUpdated,0);assert.equal(rerun.alreadyCorrectRows,2);assert.throws(()=>api.prepareSalesWorkbookTrackingRepair(before,["1257","1257"],new Map()),/invalid or duplicated/);});
