import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import ts from "typescript";
const root=new URL("../",import.meta.url);
async function analyzer(){const source=(await readFile(new URL("lib/sales-workbook/WorkbookSemanticAnalyzer.ts",root),"utf8")).replace('import "server-only";',"");const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`)}
const sample=(overrides={})=>({orderNumber:"1200",cost:"£10.00",costAndShip:"£10.00",postage:"£3.00",cardFee:"£1.00",salePrice:"£40.00",profit:"£26.00",payout:"£40.00",governedCogs:10,grossTotal:40,netRevenue:40,financialStatus:"paid",fulfilmentStatus:"fulfilled",...overrides});
test("proves repeatable Cost & Ship and profit relationships",async()=>{const{analyzeWorkbookSemantics}=await analyzer();const result=analyzeWorkbookSemantics(Array.from({length:20},(_,i)=>sample({orderNumber:String(1200+i)})));assert.equal(result.costAndShip.status,"likely");assert.equal(result.costAndShip.inferredMeaning,"Cost & Ship equals workbook Cost");assert.equal(result.profitRelationship.matches,20);});
test("conflicting cost evidence is unresolved and payout types are classified",async()=>{const{analyzeWorkbookSemantics}=await analyzer();const conflict=analyzeWorkbookSemantics(Array.from({length:20},(_,i)=>sample({orderNumber:String(1200+i),costAndShip:i%2?"£10.00":"£17.00"})));assert.equal(conflict.costAndShip.status,"unresolved");assert.equal(conflict.payout.dataType,"numeric");assert.equal(analyzeWorkbookSemantics([sample({payout:"Paid"})]).payout.dataType,"text");assert.equal(analyzeWorkbookSemantics([sample({payout:"Paid"}),sample({payout:"£40.00"})]).payout.dataType,"mixed");});
test("semantic analysis route remains read-only and excludes ambiguous rows",async()=>{const[source,route]=await Promise.all([readFile(new URL("lib/sales-workbook/WorkbookSemanticAnalyzer.ts",root),"utf8"),readFile(new URL("app/api/sales-workbook/semantic-analysis/route.ts",root),"utf8")]);assert.match(route,/rows\.length!==1\|\|canonical\.length!==1/);assert.match(route,/requireOperatorRole\("owner", "operator"\)/);assert.doesNotMatch(`${source}${route}`,/\.insert\(|\.update\(|\.upsert\(|\.remove\(|storage\.from/i);});
