import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const root=new URL("../",import.meta.url);
const read=path=>readFile(new URL(path,root),"utf8");
test("tracking repair route is owner/operator-only and accepts only the approved two-field request",async()=>{const route=await read("app/api/sales-workbook/tracking-repair/route.ts");for(const text of['requireOperatorRole("owner","operator")','Object.keys(value).length===2','expectedWorkbookVersion','expectedWorkbookSha256','status:400','status:409'])assert.ok(route.includes(text));assert.doesNotMatch(route,/trackingNumber|orderIds|destinationPath|auditMetadata/);});
test("tracking repair recomputes governed evidence, verifies bytes and preservation, and pins the approved candidate",async()=>{const[route,service,repository]=await Promise.all([read("app/api/sales-workbook/tracking-repair/route.ts"),read("lib/sales-workbook/TrackingRepairService.ts"),read("lib/sales-workbook/SalesWorkbookRepository.ts")]);for(const text of['getCurrentWorkbook','readCurrentWorkbookBytes','sha256(sourceBytes)','prepareApprovedTrackingRepair','candidateSha256!==TRACKING_REPAIR_APPROVAL.candidateSha256','writeTrackingRepairWorkbook'])assert.ok(route.includes(text));for(const text of['get_shopify_fulfillment_tracking_for_orders','prepareSalesWorkbookTrackingRepair','verifySalesWorkbookTrackingRepairPreservation','TRACKING_REPAIR_TARGET_ORDER_NUMBERS','skippedNoTracking!==0','skippedAmbiguousTracking!==0','skippedConflictTracking!==0'])assert.ok(service.includes(text));for(const text of['upsert:false','audit_event_type:versionAudit.eventType','tracking_repair_audit_metadata:versionAudit.metadata'])assert.ok(repository.includes(text));});
test("tracking repair has safe orphan handling and v3-only replay protection",async()=>{const route=await read("app/api/sales-workbook/tracking-repair/route.ts");for(const text of['current.current_version===3','current.content_hash!==TRACKING_REPAIR_APPROVAL.candidateSha256','alreadyApplied:true','SalesWorkbookOrphanedUploadError','orphanPath:error.orphanPath'])assert.ok(route.includes(text));assert.doesNotMatch(route,/current\.current_version\+1|version:\s*4/);});
