import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import ts from "typescript";

const root = new URL("../", import.meta.url);
const migrationPath = new URL("../../../supabase/migrations/20261100000000_managed_sales_workbook_tracking_repair_audit.sql", import.meta.url);
async function repository(){const source=await readFile(new URL("lib/sales-workbook/SalesWorkbookRepository.ts",root),"utf8");const executable=source.replace(/^import .*?\r?\n/,"const { createHash, randomUUID, supabaseAdmin, SALES_WORKBOOK_BUCKET, SALES_WORKBOOK_PREFIX, XLSX_MIME, SalesWorkbookConflictError, SalesWorkbookOrphanedUploadError } = globalThis.__trackingRepairAuditDeps;");globalThis.__trackingRepairAuditDeps={createHash:()=>({update:()=>({digest:()=>""})}),randomUUID:()=>"",supabaseAdmin:{},SALES_WORKBOOK_BUCKET:"vault-documents",SALES_WORKBOOK_PREFIX:"sales-workbook/versions",XLSX_MIME:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",SalesWorkbookConflictError:class extends Error{},SalesWorkbookOrphanedUploadError:class extends Error{}};const js=ts.transpileModule(executable,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`);}
const valid={sourceWorkbookVersion:2,newWorkbookVersion:3,ordersUpdated:43,rowsUpdated:79,skippedNoTracking:0,skippedAmbiguousTracking:0,skippedConflictTracking:0,source:"governed_shopify_fulfillment_tracking"};

test("application tracking-repair audit sanitizer accepts only the exact governed flat contract",async()=>{const{sanitizeTrackingRepairAuditMetadata}=await repository();assert.deepEqual(sanitizeTrackingRepairAuditMetadata(valid),valid);for(const value of[{...valid,source:"other"},{...valid,extra:1},{...valid,source:{nested:true}},{...valid,rowsUpdated:-1},{...valid,ordersUpdated:1.5},{...valid,newWorkbookVersion:2},{...valid,skippedNoTracking:"0"}])assert.throws(()=>sanitizeTrackingRepairAuditMetadata(value),/Invalid tracking repair audit metadata/);});

test("forward RPC migration adds only a guarded tracking-repair audit branch and retains existing audit paths",async()=>{const source=await readFile(migrationPath,"utf8");assert.match(source,/'repair_governed_tracking'/);for(const field of Object.keys(valid))assert.match(source,new RegExp(`'${field}'`));assert.match(source,/count\(\*\).*<> 8/s);assert.match(source,/new_v <= source_v/);assert.match(source,/governed_shopify_fulfillment_tracking/);assert.match(source,/audit_payload is not null/);assert.match(source,/backfill_ready_sales_orders/);for(const event of["upload","replace","download","validation_failed","conflict"])assert.match(source,new RegExp(`'${event}'`));assert.match(source,/revoke all on function public\.record_sales_workbook_version\(jsonb\) from public, anon, authenticated/);assert.match(source,/grant execute on function public\.record_sales_workbook_version\(jsonb\) to service_role/);});
