import "server-only";
import { supabaseAdmin } from "@/lib/supabase-admin";

export type PendingLinkContext = { pendingProductId:string; workingTitle:string; status:string; sizes:Array<{allocationId:string;supplierSizeLabel:string;normalizedSize:string;orderedUnits:number;physicalReceived:number}>; products:Array<{id:string;title:string;shopifyProductId:string}>; variants:Array<{id:string;productId:string;title:string;normalizedSize:string;shopifyVariantId:string;inventoryItemId:string}>; links:Array<{normalizedSize:string;variantId:string;shopifyVariantId:string;inventoryItemId:string}> };
export async function loadPendingCatalogueLinkContexts(purchaseOrderId:string):Promise<PendingLinkContext[]> {
 const {data: lines,error}=await supabaseAdmin.from("vault_purchase_order_lines").select("id,source_recommendation_type,vault_purchase_order_line_size_allocations(id,pending_catalogue_product_id,supplier_size_label,normalized_size,ordered_units)").eq("purchase_order_id",purchaseOrderId).eq("source_recommendation_type","pending_catalogue_purchase"); if(error)throw error;
 const ids=Array.from(new Set((lines??[]).flatMap((l:any)=>l.vault_purchase_order_line_size_allocations??[]).map((a:any)=>a.pending_catalogue_product_id).filter(Boolean)));
 if(!ids.length)return [];
 const allocationIds=(lines??[]).flatMap((l:any)=>l.vault_purchase_order_line_size_allocations??[]).map((a:any)=>a.id); const [pending,products,variants,links,receipts]=await Promise.all([supabaseAdmin.from("vault_pending_catalogue_products").select("id,working_title,status").in("id",ids),supabaseAdmin.from("vault_products").select("id,title,source_product_id").eq("source","shopify").not("source_product_id","is",null),supabaseAdmin.from("vault_variants").select("id,product_id,title,normalized_size,source_variant_id,source_inventory_item_id").eq("source","shopify").eq("source_active",true).eq("identity_resolution_status","resolved").not("source_variant_id","is",null).not("source_inventory_item_id","is",null),supabaseAdmin.from("vault_pending_catalogue_product_size_links").select("pending_catalogue_product_id,normalized_size,canonical_variant_id,shopify_variant_id_snapshot,shopify_inventory_item_id_snapshot").in("pending_catalogue_product_id",ids),supabaseAdmin.from("vault_purchase_order_receipt_allocations").select("purchase_order_line_size_allocation_id,quantity_received,non_sellable_quantity").in("purchase_order_line_size_allocation_id",allocationIds)]); if(pending.error||products.error||variants.error||links.error||receipts.error)throw pending.error??products.error??variants.error??links.error??receipts.error;
 const physical=new Map<string,number>(); for(const x of receipts.data??[])physical.set(x.purchase_order_line_size_allocation_id,(physical.get(x.purchase_order_line_size_allocation_id)??0)+x.quantity_received+x.non_sellable_quantity); return (pending.data??[]).map((p:any)=>{const sizes=(lines??[]).flatMap((l:any)=>l.vault_purchase_order_line_size_allocations??[]).filter((a:any)=>a.pending_catalogue_product_id===p.id).map((a:any)=>({allocationId:a.id,supplierSizeLabel:a.supplier_size_label,normalizedSize:a.normalized_size,orderedUnits:a.ordered_units,physicalReceived:physical.get(a.id)??0}));return {pendingProductId:p.id,workingTitle:p.working_title,status:p.status,sizes,products:(products.data??[]).map((x:any)=>({id:x.id,title:x.title,shopifyProductId:x.source_product_id})),variants:(variants.data??[]).map((x:any)=>({id:x.id,productId:x.product_id,title:x.title??x.normalized_size,normalizedSize:x.normalized_size,shopifyVariantId:x.source_variant_id,inventoryItemId:x.source_inventory_item_id})),links:(links.data??[]).filter((x:any)=>x.pending_catalogue_product_id===p.id).map((x:any)=>({normalizedSize:x.normalized_size,variantId:x.canonical_variant_id,shopifyVariantId:x.shopify_variant_id_snapshot,inventoryItemId:x.shopify_inventory_item_id_snapshot}))};});
}
export async function linkPendingCatalogueProduct(operatorId:string,pendingProductId:string,mappings:Array<{normalizedSize:string;canonicalProductId:string;canonicalVariantId:string;shopifyProductId:string}>){const {data,error}=await supabaseAdmin.rpc("link_pending_catalogue_product",{target_pending_catalogue_product_id:pendingProductId,target_operator_id:operatorId,target_mappings:mappings.map(x=>({normalized_size:x.normalizedSize,canonical_product_id:x.canonicalProductId,canonical_variant_id:x.canonicalVariantId,shopify_product_id:x.shopifyProductId}))});if(error)throw new Error(error.message);return data;}
