import {
  BriefingActionList,
} from "@/components/brain/briefing/BriefingActionList";

import {
  BriefingMetricGrid,
} from "@/components/brain/briefing/BriefingMetricGrid";

import type {
  BriefingResult,
} from "@/lib/brain/BriefingEngine";

type VaultBrainBriefingCardProps = {
  briefing: BriefingResult;
};

export function VaultBrainBriefingCard({
  briefing,
}: VaultBrainBriefingCardProps) {
  const metrics = [
    {
      label: "Business Health",
      value: `${briefing.businessHealthScore}%`,
      supportingText:
        briefing.businessHealth
          .charAt(0)
          .toUpperCase() +
        briefing.businessHealth.slice(1),
    },

    {
      label: "Available Capital",
      value: `£${briefing.availableCapital.toLocaleString()}`,
    },

    {
      label: "Recommended Spend",
      value: `£${briefing.recommendedSpend.toLocaleString()}`,
    },

    {
      label: "Projected Profit",
      value: `£${briefing.projectedProfit.toLocaleString()}`,
    },
  ];

  return (
    <section className="vault-brain-briefing-card">
      <header className="vault-brain-briefing-header">
        <div>
          <p className="vault-eyebrow">
            Generated by Vault Brain
          </p>

          <h2>
            Good Morning Tom
          </h2>

          <p>
            Vault Brain has analysed your
            commercial position and ranked
            today's highest-value actions.
          </p>
        </div>
      </header>

      <BriefingMetricGrid
        metrics={metrics}
      />

      {briefing.primaryAction && (
        <section className="vault-primary-action">
          <span>
            Highest Priority
          </span>

          <h3>
            {briefing.primaryAction.title}
          </h3>

          <p>
            {
              briefing.primaryAction
                .description
            }
          </p>
        </section>
      )}

      <BriefingActionList
        actions={briefing.actions}
      />
    </section>
  );
}