import type {
  CataloguePageExtraction,
} from "@/lib/ai/extractCataloguePage";

export type CataloguePageAnalysisStatus =
  | "pending"
  | "analysing"
  | "complete"
  | "failed"
  | "skipped";

/**
 * Coordinates are stored as percentages from 0 to 1.
 *
 * Example:
 * x: 0.1 means 10% from the left.
 * width: 0.4 means 40% of the image width.
 */
export type CatalogueGarmentBoundingBox = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type CatalogueDetectedGarmentStatus =
  | "detected"
  | "confirmed"
  | "ignored"
  | "split";

export type CatalogueDetectedGarment = {
  /**
   * Stable ID for this detected garment.
   *
   * Example:
   * page-384-garment-1
   */
  id: string;

  pageNumber: number;

  /**
   * Human-readable label generated by Vault Brain.
   *
   * Examples:
   * Black Logo Tee
   * White Graphic Tee
   */
  label: string;

  brand: string | null;
  productType: string | null;
  garmentType: string | null;

  colour: string | null;
  secondaryColours: string[];

  /**
   * Position of this garment inside the original supplier image.
   */
  boundingBox: CatalogueGarmentBoundingBox;

  /**
   * Detection confidence from 0 to 100.
   */
  confidence: number;

  status: CatalogueDetectedGarmentStatus;

  /**
   * Review-card ID created after the image has been split.
   */
  childReviewCardId: string | null;

  /**
   * Product-group ID created for this individual garment.
   */
  childProductGroupId: string | null;

  warnings: string[];
};

export type CatalogueMultiProductSplitStatus =
  | "not-required"
  | "available"
  | "splitting"
  | "complete"
  | "failed";

export type CatalogueMultiProductDetection = {
  /**
   * True when Vault Brain believes this page contains
   * more than one separately reviewable product.
   */
  isMultiProduct: boolean;

  detectedCount: number;

  /**
   * Overall detection confidence from 0 to 100.
   */
  confidence: number;

  garments: CatalogueDetectedGarment[];

  splitStatus: CatalogueMultiProductSplitStatus;

  /**
   * IDs of the new review cards created from this page.
   */
  childReviewCardIds: string[];

  detectedAt: string | null;
  splitAt: string | null;

  error: string | null;
};

export type CataloguePageAnalysisRecord = {
  pageNumber: number;
  status: CataloguePageAnalysisStatus;

  extraction: CataloguePageExtraction | null;

  /**
   * Optional for backwards compatibility with existing
   * catalogue-analysis sessions.
   */
  multiProductDetection?:
    | CatalogueMultiProductDetection
    | null;

  error: string | null;

  attempts: number;

  analysedAt: string | null;
};

export type CatalogueProductGroupStatus =
  | "draft"
  | "confirmed"
  | "requires-review";

export type CatalogueProductGroup = {
  id: string;

  startPage: number;
  endPage: number;
  pageNumbers: number[];

  brand: string | null;
  productName: string | null;
  productType: string | null;
  garmentType: string | null;

  colour: string | null;
  secondaryColours: string[];

  chestLogo: string | null;
  frontGraphic: string | null;
  backGraphic: string | null;
  sleeveDetail: string | null;
  neckLabel: string | null;

  fit: string | null;
  collection: string | null;

  visualFingerprint: string[];
  rawVisibleText: string[];

  displayedPrice: number | null;
  currency: string | null;

  supplierSku: string | null;
  sizes: string[];
  packQuantity: number | null;

  confidence: number;

  status: CatalogueProductGroupStatus;

  warnings: string[];

  /**
   * Present when this group was created by splitting one
   * detected garment from a multi-product supplier image.
   */
  sourceDetectedGarmentId?: string | null;

  /**
   * Original parent group before it was split.
   */
  parentProductGroupId?: string | null;

  /**
   * Crop displayed for this individual review item.
   */
  cropBoundingBox?:
    | CatalogueGarmentBoundingBox
    | null;

  /**
   * Allows Vault OS to distinguish ordinary groups from
   * groups created by the Split Image workflow.
   */
  isSplitChild?: boolean;
};

export type CatalogueBatchAnalysisState =
  | "idle"
  | "running"
  | "paused"
  | "complete"
  | "failed";

export type CatalogueBatchAnalysisProgress = {
  state: CatalogueBatchAnalysisState;

  totalPages: number;
  completedPages: number;
  failedPages: number;
  skippedPages: number;

  currentPageNumber: number | null;

  startedAt: string | null;
  completedAt: string | null;

  error: string | null;
};

export type CatalogueAnalysisSession = {
  documentId: string;
  fileName: string;

  pages: Record<
    number,
    CataloguePageAnalysisRecord
  >;

  productGroups: CatalogueProductGroup[];

  progress: CatalogueBatchAnalysisProgress;
};