import Link from "next/link";
import type { VaultBrainEvidenceState, VaultBrainIntelligence } from "@/lib/brain/getVaultBrainIntelligence";

function label(state: VaultBrainEvidenceState): string { return state === "proven" ? "Action available" : state === "no_action_required" ? "No action required" : state === "no_trusted_action" ? "No trusted action" : state === "watch" ? "Watch" : state === "gathering_evidence" ? "Gathering evidence" : state === "blocked" ? "Blocked" : state === "unavailable" ? "Unavailable" : "Unknown"; }
function freshness(value: string | null): string {
  if (!value || Number.isNaN(Date.parse(value))) return "Freshness unavailable";
  return `Updated ${new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value))}`;
}

export function VaultBrainV2({ data }: { data: VaultBrainIntelligence }) {
  const boundary = data.decisionTrace.find((stage) => stage.id === "trusted-buying-decision");
  return <main className="vault-brain-v2">
    <header className="vault-brain-v2-header"><p className="vault-eyebrow">VAULT BRAIN</p><h1>Executive Intelligence</h1><p>Governed conclusions, their evidence, and the limits of what Vault OS currently knows.</p></header>
    <section aria-labelledby="executive-understanding"><div className="vault-brain-v2-heading"><p className="vault-eyebrow">EXECUTIVE UNDERSTANDING</p><h2 id="executive-understanding">What Vault OS understands now</h2></div>
      {data.conclusions.length ? <div className="vault-brain-v2-conclusions">{data.conclusions.map((conclusion) => <article className="vault-brain-v2-card" key={conclusion.id}><div className="vault-brain-v2-card-topline"><span className={`vault-brain-v2-state is-${conclusion.evidenceState}`}>{label(conclusion.evidenceState)}</span><span>{conclusion.severity}</span></div><h3>{conclusion.headline}</h3><p>{conclusion.interpretation}</p><small>{freshness(conclusion.freshness)}</small><Link href={conclusion.destination}>Open authoritative surface →</Link></article>)}</div> : <article className="vault-brain-v2-card"><h3>No governed executive conclusion is currently available</h3><p>Vault Brain will not infer a conclusion when Command Centre evidence is unavailable.</p></article>}
    </section>
    <section aria-labelledby="decision-trace"><div className="vault-brain-v2-heading"><p className="vault-eyebrow">DECISION TRACE</p><h2 id="decision-trace">How the governed decision path reaches its current boundary</h2></div>
      <div className="vault-brain-v2-trace">{data.decisionTrace.map((stage, index) => <div className="vault-brain-v2-trace-wrap" key={stage.id}><article className={`vault-brain-v2-trace-stage is-${stage.state}`}><div><span className="vault-eyebrow">{stage.source}</span><h3>{stage.label}</h3></div><span className={`vault-brain-v2-state is-${stage.state}`}>{label(stage.state)}</span><p>{stage.explanation}</p><small>{freshness(stage.freshness)}</small><Link href={stage.destination}>Open source →</Link></article>{index < data.decisionTrace.length - 1 ? <span className="vault-brain-v2-trace-arrow" aria-hidden="true">↓</span> : null}</div>)}</div>
      {data.blockerExplanations.length ? <article className="vault-brain-v2-card vault-brain-v2-blockers"><p className="vault-eyebrow">GOVERNED DECISION REASONS</p><h3>Why the buying path reached this outcome</h3><ul>{data.blockerExplanations.map((reason) => <li key={reason}>{reason}</li>)}</ul></article> : null}
      {boundary ? <p className="vault-brain-v2-safety">Vault Brain explains the governed boundary. It does not create a buying, reorder, or approval recommendation.</p> : null}
    </section>
    <section className="vault-brain-v2-secondary-grid"><article className="vault-brain-v2-card"><p className="vault-eyebrow">CHANGES &amp; MEMORY</p><h2>Comparable governed history is not available yet</h2><p>Vault Brain does not use legacy mixed operational snapshots. Review current executive remediation in Command Centre.</p><Link href="/">Open Command Centre →</Link></article><article className="vault-brain-v2-card"><p className="vault-eyebrow">LEARNED INTELLIGENCE</p><h2>No governed learned patterns available yet</h2><p>Patterns will appear only when supported by sufficient verified evidence.</p><Link href="/intelligence">Open Store Intelligence →</Link></article></section>
    <style>{`
      .vault-brain-v2{max-width:1120px;margin:0 auto;padding:44px 30px 80px;color:#f3f1eb}.vault-brain-v2-header{max-width:700px;margin-bottom:46px}.vault-brain-v2 h1{margin:6px 0 12px;font:600 clamp(32px,5vw,54px)/1.02 Georgia,serif}.vault-brain-v2 h2{margin:4px 0 0;font:600 23px/1.2 Georgia,serif}.vault-brain-v2 h3{margin:12px 0 9px;font-size:18px}.vault-brain-v2 p{color:#b8bcb7;line-height:1.6}.vault-brain-v2-heading{margin:38px 0 14px}.vault-brain-v2-conclusions,.vault-brain-v2-secondary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.vault-brain-v2-card,.vault-brain-v2-trace-stage{padding:22px;border:1px solid rgba(220,181,72,.23);border-radius:12px;background:linear-gradient(145deg,rgba(220,181,72,.07),rgba(255,255,255,.02));box-shadow:inset 0 1px rgba(255,255,255,.04)}.vault-brain-v2-card a,.vault-brain-v2-trace-stage a{display:inline-block;margin-top:15px;color:#e5bb53;font-size:13px;text-decoration:none}.vault-brain-v2-card small,.vault-brain-v2-trace-stage small{display:block;margin-top:14px;color:#7f8780;font-size:11px}.vault-brain-v2-card-topline{display:flex;justify-content:space-between;gap:12px;color:#a4a9a2;font-size:11px;text-transform:uppercase}.vault-brain-v2-state{display:inline-block;padding:3px 7px;border-radius:99px;font-size:11px;text-transform:uppercase}.vault-brain-v2-state.is-proven,.vault-brain-v2-state.is-no_action_required{background:rgba(68,172,102,.18);color:#8ce4aa}.vault-brain-v2-state.is-blocked{background:rgba(202,104,85,.18);color:#f09b87}.vault-brain-v2-state.is-watch,.vault-brain-v2-state.is-gathering_evidence{background:rgba(217,177,76,.16);color:#e8c26a}.vault-brain-v2-state.is-no_trusted_action,.vault-brain-v2-state.is-unavailable,.vault-brain-v2-state.is-unknown{background:rgba(135,141,143,.15);color:#c6cdca}.vault-brain-v2-trace{display:grid;gap:0;max-width:760px;margin:0 auto}.vault-brain-v2-trace-stage{position:relative}.vault-brain-v2-trace-stage>div:first-child{display:flex;align-items:start;justify-content:space-between}.vault-brain-v2-trace-stage>div:first-child+span{position:absolute;right:22px;top:22px}.vault-brain-v2-trace-arrow{display:grid;height:32px;place-items:center;color:#d7ad47;font-size:22px}.vault-brain-v2-trace-stage.is-blocked{border-color:rgba(212,105,83,.55)}.vault-brain-v2-blockers{max-width:760px;margin:18px auto 0}.vault-brain-v2-blockers ul{margin:13px 0 0;padding-left:20px;color:#c9cdc7;line-height:1.6}.vault-brain-v2-safety{max-width:760px;margin:16px auto;padding:12px 14px;border-left:3px solid #d7a83e;background:rgba(215,168,62,.1);color:#eee5cb}.vault-brain-v2-secondary-grid{margin-top:38px}@media(max-width:720px){.vault-brain-v2{padding:30px 17px}.vault-brain-v2-trace-stage{padding:18px}}
    `}</style>
  </main>;
}
