import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

import { deriveOrderFreshness } from "./OrderFreshness.ts";
import { VAULT_NAVIGATION } from "../navigation.ts";

const webRoot = new URL("../../", import.meta.url);

async function source(path) {
  return readFile(new URL(path, webRoot), "utf8");
}

test("orders list and detail routes exist", async () => {
  await Promise.all([
    access(new URL("app/orders/page.tsx", webRoot)),
    access(new URL("app/orders/[id]/page.tsx", webRoot)),
  ]);
});

test("orders use canonical server-side order and line contracts in newest-first order", async () => {
  const repository = await source("lib/orders/OrdersRepository.ts");
  assert.match(repository, /import "server-only"/);
  assert.match(repository, /from\("vault_shopify_orders"\)/);
  assert.match(repository, /from\("vault_shopify_order_lines"\)/);
  assert.match(repository, /\.order\("shopify_created_at", \{ ascending: false \}\)/);
  assert.match(repository, /\.eq\("order_id", id\)/);
  assert.doesNotMatch(repository, /fetch\(|shopify\.com|graphql/i);
});

test("orders expose read-only canonical list and line evidence without mutation actions", async () => {
  const [list, detail, repository] = await Promise.all([
    source("app/orders/page.tsx"),
    source("app/orders/[id]/page.tsx"),
    source("lib/orders/OrdersRepository.ts"),
  ]);
  assert.match(list, /OrdersRepository\.list\(\)/);
  assert.match(detail, /OrdersRepository\.getById\(id\)/);
  assert.match(detail, /order\.lines\.map/);
  assert.doesNotMatch(`${list}${detail}${repository}`, /\.insert\(|\.update\(|\.delete\(|\.upsert\(|refundOrder|cancelOrder|fulfilOrder/);
});

test("freshness preserves current, stale and unavailable states", () => {
  const now = new Date("2026-08-08T12:00:00.000Z");
  assert.equal(deriveOrderFreshness("2026-08-08T11:45:00.000Z", now), "current");
  assert.equal(deriveOrderFreshness("2026-08-08T11:29:59.000Z", now), "stale");
  assert.equal(deriveOrderFreshness(null, now), "unavailable");
});

test("failed canonical reads return no fabricated order data", async () => {
  const repository = await source("lib/orders/OrdersRepository.ts");
  assert.match(repository, /data: \[\],\s*freshness: "error"/);
  assert.match(repository, /data: null, freshness: "error"/);
});

test("canonical navigation exposes only implemented primary destinations", () => {
  const hrefs = VAULT_NAVIGATION.map((item) => item.href);
  assert.ok(hrefs.includes("/orders"));
  assert.ok(hrefs.includes("/supplier-catalogue/review"));
  assert.ok(hrefs.includes("/purchase-intelligence"));
  assert.ok(!hrefs.includes("/partners"));
  assert.ok(!hrefs.includes("/analytics"));
  assert.ok(!hrefs.includes("/settings"));
});

test("standard shell and Vault Brain consume the shared navigation contract", async () => {
  const [shell, brain] = await Promise.all([
    source("components/layout/VaultAppShell.tsx"),
    source("components/brain/MissionControlWorkspace.tsx"),
  ]);
  for (const component of [shell, brain]) {
    assert.match(component, /VAULT_NAVIGATION/);
    assert.doesNotMatch(component, /const navigation = \[/);
  }
});

test("Command Centre View orders targets the implemented route", async () => {
  const component = await source("components/command-centre/CommandCentreCockpit.tsx");
  assert.match(component, /href="\/orders">View orders/);
});

test("application metadata identifies Vault OS", async () => {
  const layout = await source("app/layout.tsx");
  assert.match(layout, /title: "Vault OS"/);
  assert.doesNotMatch(layout, /Create Next App|Generated by create next app/);
});
