"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { filterAndSortProductProfitability, type ProductProfitability, type ProductProfitabilityComparison, type ProductProfitabilitySummary, type ProfitPeriod, type ProfitabilitySort } from "@/lib/intelligence/ProductProfitabilityIntelligence";
import type { ProductProfitabilityAvailability } from "@/lib/intelligence/StoreIntelligence";

const money = (value: number | null) => value === null ? "—" : new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 2 }).format(value);
const percent = (value: number | null) => value === null ? "—" : `${value.toFixed(1)}%`;
const change = (value: number | null) => value === null ? "—" : `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)}%`;

export function ProductProfitabilityPanel({ period, rows, summary, comparison, availability }: { period: ProfitPeriod; rows: ProductProfitability[]; summary: ProductProfitabilitySummary; comparison: ProductProfitabilityComparison | null; availability: ProductProfitabilityAvailability }) {
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState<ProfitabilitySort>("contribution");
  const visible = useMemo(() => filterAndSortProductProfitability(rows, search, sort), [rows, search, sort]);

  return <section className="intelligence-panel intelligence-insights-panel"><div className="intelligence-panel-heading"><div><span>PRODUCT PROFITABILITY</span><h2>{period === "all" ? "All-time verified product profitability" : `${period.slice(0, -1)} completed days`}</h2></div><div>{(["7d", "30d", "90d", "all"] as const).map(item => <Link className={`confidence-badge${item === period ? " is-high" : ""}`} href={`/intelligence?profitPeriod=${item}`} key={item}>{item === "all" ? "All Time" : item.toUpperCase()}</Link>)}</div></div>
    {!availability.available ? <p className="intelligence-muted">{availability.message}</p> : <><div className="trend-metrics"><div><small>Verified revenue</small><strong>{money(summary.verifiedRevenue)}</strong>{comparison && <span>{change(comparison.revenueChange)} vs prior period</span>}</div><div><small>Contribution</small><strong>{money(summary.verifiedContribution)}</strong>{comparison && <span>{change(comparison.contributionChange)} vs prior period</span>}</div><div><small>Margin</small><strong>{percent(summary.contributionMarginPct)}</strong>{comparison && <span>{comparison.marginPpChange === null ? "—" : `${comparison.marginPpChange >= 0 ? "+" : ""}${comparison.marginPpChange.toFixed(1)}pp`}</span>}</div><div><small>Units / orders / ASP</small><strong>{summary.eligibleUnits} / {summary.eligibleOrders}</strong><span>{money(summary.asp)} ASP {comparison && `· ${change(comparison.unitsChange)} units`}</span></div></div>
    <div className="pp-controls"><input aria-label="Search products" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search products" /><select aria-label="Sort products" value={sort} onChange={event => setSort(event.target.value as ProfitabilitySort)}><option value="contribution">Contribution</option><option value="revenue">Revenue</option><option value="units">Units</option><option value="margin">Margin</option></select></div>
    {visible.length ? <div className="weekday-table-wrap"><table className="weekday-table"><thead><tr><th>Product</th><th>Units</th><th>Orders</th><th>ASP</th><th>Revenue</th><th>COGS</th><th>Ship</th><th>Fees</th><th>Contribution</th><th>£/Unit</th><th>Margin</th></tr></thead><tbody>{visible.map(row => <tr key={row.productId}><td><Link href={`/intelligence/products/${encodeURIComponent(row.productId)}?profitPeriod=${period}`}><strong>{row.productName}</strong></Link>{row.excludedOrders > 0 && <small className="confidence-badge">{row.excludedOrders} excluded</small>}</td><td>{row.eligibleUnits}</td><td>{row.eligibleOrders}</td><td>{money(row.asp)}</td><td>{money(row.verifiedRevenue)}</td><td>{money(row.cogs)}</td><td>{money(row.shippingCost)}</td><td>{money(row.paymentFees)}</td><td>{money(row.contribution)}</td><td>{money(row.contributionPerUnit)}</td><td>{percent(row.contributionMarginPct)}</td></tr>)}</tbody></table></div> : <p className="intelligence-muted">{rows.length ? "No products match this search." : "No financially verified product profitability is available for this period."}</p>}</>}
    <style jsx>{`.pp-controls{display:flex;gap:10px;margin:16px 0}.pp-controls input,.pp-controls select{background:#111a16;border:1px solid rgba(255,255,255,.16);border-radius:8px;color:#eee;padding:9px}.pp-controls input{min-width:220px}.weekday-table a{color:inherit;text-decoration:none}.weekday-table a:hover{text-decoration:underline}`}</style>
  </section>;
}
