import "server-only"; import {createHash,randomUUID} from "node:crypto"; import {supabaseAdmin} from "@/lib/supabase-admin"; import {SALES_WORKBOOK_BUCKET,SALES_WORKBOOK_PREFIX,XLSX_MIME,type SalesWorkbookMetadata,type SalesWorkbookVersion,type WorkbookWriteResult,type SignedWorkbookDownload,SalesWorkbookConflictError,SalesWorkbookOrphanedUploadError} from "./types";
export const sha256=(bytes:Uint8Array)=>createHash("sha256").update(bytes).digest("hex"); export const immutableWorkbookPath=(id:string,v:number,h:string)=>`${SALES_WORKBOOK_PREFIX}/${id}/${v}-${h}.xlsx`;
const BACKFILL_AUDIT_NUMBER_FIELDS=new Set(["sourceWorkbookVersion","newWorkbookVersion","ordersWritten","rowsWritten","skippedExistingOrders","skippedReviewOrders"]);
const BACKFILL_AUDIT_RANGE=/^[1-9]\d{0,8}-[1-9]\d{0,8}$/;
export const sanitizeSalesWorkbookAuditMetadata=(value:Record<string,unknown>)=>Object.fromEntries(Object.entries(value).filter(([key,item])=>{
 if(["filename","storage_path","content_hash"].includes(key))return typeof item==="string";
 if(["version","predecessor_version","size_bytes","expiry_seconds"].includes(key))return typeof item==="number"&&Number.isFinite(item);
 if(BACKFILL_AUDIT_NUMBER_FIELDS.has(key))return typeof item==="number"&&Number.isInteger(item)&&item>=0&&item<=999999999;
 return key==="targetOrderRange"&&typeof item==="string"&&BACKFILL_AUDIT_RANGE.test(item);
}));
const auditMetadata=sanitizeSalesWorkbookAuditMetadata;
const audit=async(id:string,v:number,event:"download",operator:string,metadata:Record<string,unknown>={})=>{const {error}=await supabaseAdmin.from("vault_sales_workbook_audit_events").insert({workbook_id:id,version:v,event_type:event,operator_id:operator,metadata:auditMetadata(metadata)});if(error)throw new Error(error.message);};
type BackfillAuditMetadata={sourceWorkbookVersion:number;newWorkbookVersion:number;ordersWritten:number;rowsWritten:number;skippedExistingOrders:number;skippedReviewOrders:number;targetOrderRange:string};
export const SalesWorkbookRepository={
 async getCurrentWorkbook():Promise<SalesWorkbookMetadata|null>{const {data,error}=await supabaseAdmin.from("vault_sales_workbooks").select("*").order("last_modified_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data as SalesWorkbookMetadata|null;},
 async readCurrentWorkbookBytes(){const workbook=await this.getCurrentWorkbook();if(!workbook)throw new Error("No workbook");const {data,error}=await supabaseAdmin.storage.from(SALES_WORKBOOK_BUCKET).download(workbook.current_storage_path);if(error||!data)throw new Error("Workbook unavailable");return {workbook,bytes:await data.arrayBuffer()};},
 async uploadInitialWorkbook({bytes,filename,operatorId}:{bytes:Uint8Array;filename:string;operatorId:string}):Promise<WorkbookWriteResult>{if(await this.getCurrentWorkbook())throw new Error("Workbook already exists");return this.write(randomUUID(),1,null,bytes,filename,operatorId);},
 async replaceWorkbook(input:{bytes:Uint8Array;filename:string;operatorId:string;expectedVersion:number;expectedChecksum:string}):Promise<WorkbookWriteResult>{const current=await this.getCurrentWorkbook();if(!current)throw new Error("No workbook");if(current.current_version!==input.expectedVersion||current.content_hash!==input.expectedChecksum)throw new SalesWorkbookConflictError(current);return this.write(current.id,current.current_version+1,current.current_version,input.bytes,input.filename,input.operatorId,current);},
 async writeBackfillWorkbook(input:{bytes:Uint8Array;operatorId:string;current:SalesWorkbookMetadata;metadata:BackfillAuditMetadata}):Promise<WorkbookWriteResult>{const{current}=input;if(input.metadata.sourceWorkbookVersion!==current.current_version||input.metadata.newWorkbookVersion!==current.current_version+1)throw new SalesWorkbookConflictError(current);return this.write(current.id,current.current_version+1,current.current_version,input.bytes,current.filename,input.operatorId,current,input.metadata);},
 async write(id:string,version:number,predecessor:number|null,bytes:Uint8Array,filename:string,operatorId:string,current?:SalesWorkbookMetadata,backfillAuditMetadata?:BackfillAuditMetadata):Promise<WorkbookWriteResult>{const hash=sha256(bytes),path=immutableWorkbookPath(id,version,hash);const {error:uploadError}=await supabaseAdmin.storage.from(SALES_WORKBOOK_BUCKET).upload(path,bytes,{contentType:XLSX_MIME,upsert:false});if(uploadError)throw new Error(uploadError.message);try{const payload={workbook_id:id,filename,storage_path:path,content_hash:hash,operator_id:operatorId,expected_version:current?.current_version??null,expected_checksum:current?.content_hash??null,...(backfillAuditMetadata?{audit_event_type:"backfill_ready_sales_orders",backfill_audit_metadata:backfillAuditMetadata}:{})};const {data:workbook,error}=await supabaseAdmin.rpc("record_sales_workbook_version",{payload});if(error||!workbook){if(/conflict/i.test(error?.message??"")&&current)throw new SalesWorkbookConflictError(current);throw new Error(error?.message??"metadata failed");}const {data:versionRow,error:ve}=await supabaseAdmin.from("vault_sales_workbook_versions").select("*").eq("workbook_id",id).eq("version",version).single();if(ve||!versionRow)throw new Error("Atomic workbook version was not returned");return {workbook:workbook as SalesWorkbookMetadata,version:versionRow as SalesWorkbookVersion,storagePath:path};}catch(error){if(error instanceof SalesWorkbookConflictError)throw error;throw new SalesWorkbookOrphanedUploadError(path,error);}},
 async createSignedDownload({operatorId,expiresIn=120}:{operatorId:string;expiresIn?:number}):Promise<SignedWorkbookDownload>{const workbook=await this.getCurrentWorkbook();if(!workbook)throw new Error("No workbook");const ttl=Math.max(30,Math.min(300,Math.trunc(expiresIn)));const {data,error}=await supabaseAdmin.storage.from(SALES_WORKBOOK_BUCKET).createSignedUrl(workbook.current_storage_path,ttl);if(error||!data?.signedUrl)throw new Error("Signed URL failed");await audit(workbook.id,workbook.current_version,"download",operatorId,{expiry_seconds:ttl});return {url:data.signedUrl,expiresIn:ttl,workbook};}
} as const;
