-- Historical C2 v1: DB_PREPARE_TS_HASH_DB_FINALIZE. PostgreSQL never hashes.
begin;
create table public.vault_shopify_historical_c2_reconciliation_runs (
 id uuid primary key default gen_random_uuid(), idempotency_key text unique, requested_order_numbers text[] not null,
 dry_run boolean not null, idempotent boolean not null default false, state text not null check(state in ('PREPARING','PREPARED','DRY_RUN_COMPLETE','FINALIZING','COMPLETED','FAILED')),
 failure_code text, created_at timestamptz not null default now(), completed_at timestamptz
);
create table public.vault_shopify_historical_c2_prepared_plan_items (
 id uuid primary key default gen_random_uuid(), run_id uuid not null references public.vault_shopify_historical_c2_reconciliation_runs(id),
 canonical_order_id uuid not null references public.vault_shopify_orders(id), canonical_order_line_id uuid references public.vault_shopify_order_lines(id),
 kind text not null check(kind in ('APPLICATION','ALLOCATION','ZERO_DISCOUNT_PROOF')), source_observation_id uuid,
 completeness_observation_id uuid not null references public.vault_shopify_financial_capture_completeness_observations(id), payload jsonb not null,
 required_hash boolean not null default false, expected_source_fingerprint text, unique(run_id,kind,canonical_order_id,canonical_order_line_id)
);
create table public.vault_shopify_historical_c2_reconciliation_evidence (
 id uuid primary key default gen_random_uuid(), run_id uuid not null references public.vault_shopify_historical_c2_reconciliation_runs(id), plan_item_id uuid not null unique references public.vault_shopify_historical_c2_prepared_plan_items(id),
 canonical_order_id uuid not null references public.vault_shopify_orders(id), canonical_order_line_id uuid references public.vault_shopify_order_lines(id), evidence_kind text not null,
 source_observation_id uuid, appended_observation_id uuid not null unique, completeness_observation_id uuid not null references public.vault_shopify_financial_capture_completeness_observations(id), source_content_fingerprint text not null, created_at timestamptz not null default now()
);
-- A hash attestation is distinct from the immutable plan: the trusted Edge may
-- attest the DB-owned payload once, but may never alter either payload or plan.
create table public.vault_shopify_historical_c2_hash_attestations (
 plan_item_id uuid primary key references public.vault_shopify_historical_c2_prepared_plan_items(id),
 fingerprint text not null check(fingerprint ~ '^[0-9a-f]{1,8}$'), attested_at timestamptz not null default now()
);
alter table public.vault_shopify_historical_c2_reconciliation_runs enable row level security;
alter table public.vault_shopify_historical_c2_prepared_plan_items enable row level security;
alter table public.vault_shopify_historical_c2_reconciliation_evidence enable row level security;
alter table public.vault_shopify_historical_c2_hash_attestations enable row level security;
revoke all on public.vault_shopify_historical_c2_reconciliation_runs,public.vault_shopify_historical_c2_prepared_plan_items,public.vault_shopify_historical_c2_reconciliation_evidence from public,anon,authenticated,service_role;
grant select on public.vault_shopify_historical_c2_reconciliation_runs,public.vault_shopify_historical_c2_prepared_plan_items,public.vault_shopify_historical_c2_reconciliation_evidence to service_role;
create function public.c2_immutable() returns trigger language plpgsql set search_path='' as $$begin raise exception 'C2_PREPARED_PLAN_IMMUTABLE'; end$$;
create trigger c2_plan_immutable before update or delete on public.vault_shopify_historical_c2_prepared_plan_items for each row execute function public.c2_immutable();
create trigger c2_evidence_immutable before update or delete on public.vault_shopify_historical_c2_reconciliation_evidence for each row execute function public.c2_immutable();
create trigger c2_attestation_immutable before update or delete on public.vault_shopify_historical_c2_hash_attestations for each row execute function public.c2_immutable();
create function public.c2_run_transition() returns trigger language plpgsql set search_path=pg_catalog,public as $$begin if current_setting('vault.c2_transition',true)<>'on' or (old.state,new.state) not in (('PREPARING','PREPARED'),('PREPARING','DRY_RUN_COMPLETE'),('PREPARED','FINALIZING'),('FINALIZING','COMPLETED'),('PREPARING','FAILED'),('FINALIZING','FAILED'),('PREPARING','COMPLETED')) or (old.state='PREPARING' and new.state='COMPLETED' and (not new.idempotent or new.completed_at is null or exists(select 1 from public.vault_shopify_historical_c2_prepared_plan_items where run_id=new.id))) then raise exception 'C2_INVALID_STATE_TRANSITION'; end if; return new; end$$;
create trigger c2_run_transition_guard before update or delete on public.vault_shopify_historical_c2_reconciliation_runs for each row execute function public.c2_run_transition();

create function public.prepare_historical_c2_v1(p_order_numbers text[],p_dry_run boolean,p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare r uuid; o record; c record; a record; x record; line record; expected text; payload jsonb;
begin
 if p_order_numbers is null or cardinality(p_order_numbers)=0 then raise exception 'C2_TARGET_ARRAY_EMPTY'; end if;
 if cardinality(p_order_numbers)<>cardinality(array(select distinct v from unnest(p_order_numbers)v)) then raise exception 'C2_DUPLICATE_ORDER'; end if;
 if exists(select 1 from unnest(p_order_numbers)v where v not in ('1254','1256','1259','1263','1264','1270')) then raise exception 'C2_ORDER_UNSUPPORTED'; end if;
 if p_idempotency_key is not null and exists(select 1 from public.vault_shopify_historical_c2_reconciliation_runs where idempotency_key=p_idempotency_key) then return (select jsonb_build_object('run_id',z.id,'state',z.state,'items',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'payload',p.payload)) from public.vault_shopify_historical_c2_prepared_plan_items p where p.run_id=z.id and p.required_hash),'[]'::jsonb)) from public.vault_shopify_historical_c2_reconciliation_runs z where z.idempotency_key=p_idempotency_key); end if;
 if (select count(*) from public.vault_shopify_orders where order_number=any(p_order_numbers))<>cardinality(p_order_numbers) then raise exception 'C2_ORDER_NOT_FOUND'; end if;
 if exists(select 1 from public.vault_shopify_orders ord where ord.order_number=any(p_order_numbers) and exists(select 1 from public.vault_shopify_historical_c2_reconciliation_evidence e join public.vault_shopify_historical_c2_reconciliation_runs done on done.id=e.run_id and done.state='COMPLETED' where e.canonical_order_id=ord.id) and (select count(*) from public.vault_shopify_historical_c2_reconciliation_evidence e join public.vault_shopify_historical_c2_reconciliation_runs done on done.id=e.run_id and done.state='COMPLETED' where e.canonical_order_id=ord.id) < case when ord.order_number='1264' then 4 else 3 end) then raise exception 'C2_PARTIAL_COUNTERPART_STATE'; end if;
 -- Exact idempotency is proven from immutable C2 audit rows plus the live
 -- counterpart identity/fingerprint, never from a weak order-level existence check.
 if not exists(select 1 from public.vault_shopify_orders ord where ord.order_number=any(p_order_numbers) and
   (select count(*) from public.vault_shopify_historical_c2_reconciliation_evidence e join public.vault_shopify_historical_c2_reconciliation_runs done on done.id=e.run_id and done.state='COMPLETED' left join public.vault_shopify_discount_application_observations sa on e.evidence_kind='APPLICATION' and sa.id=e.source_observation_id left join public.vault_shopify_discount_application_observations aa on e.evidence_kind='APPLICATION' and aa.id=e.appended_observation_id left join public.vault_shopify_line_discount_allocation_observations sl on e.evidence_kind='ALLOCATION' and sl.id=e.source_observation_id left join public.vault_shopify_line_discount_allocation_observations al on e.evidence_kind='ALLOCATION' and al.id=e.appended_observation_id left join public.vault_shopify_line_zero_discount_allocation_observations z on e.evidence_kind='ZERO_DISCOUNT_PROOF' and z.id=e.appended_observation_id where e.canonical_order_id=ord.id and e.source_content_fingerprint=coalesce(sa.source_content_fingerprint,sl.source_content_fingerprint,z.source_content_fingerprint) and ((e.evidence_kind='APPLICATION' and (sa.source,sa.shopify_order_id,sa.application_index,sa.order_source_updated_at,sa.source_content_fingerprint)=(aa.source,aa.shopify_order_id,aa.application_index,aa.order_source_updated_at,aa.source_content_fingerprint)) or (e.evidence_kind='ALLOCATION' and (sl.source,sl.shopify_order_id,sl.shopify_line_item_id,sl.application_index,sl.order_source_updated_at,sl.source_content_fingerprint)=(al.source,al.shopify_order_id,al.shopify_line_item_id,al.application_index,al.order_source_updated_at,al.source_content_fingerprint)) or (e.evidence_kind='ZERO_DISCOUNT_PROOF' and z.source_content_fingerprint=e.source_content_fingerprint)) ) <> case when ord.order_number='1264' then 4 else 3 end) then
  insert into public.vault_shopify_historical_c2_reconciliation_runs(idempotency_key,requested_order_numbers,dry_run,idempotent,state,completed_at) values(p_idempotency_key,p_order_numbers,p_dry_run,true,'PREPARING',null) returning id into r;
  perform set_config('vault.c2_transition','on',true); update public.vault_shopify_historical_c2_reconciliation_runs set state='COMPLETED',completed_at=now() where id=r;
  return jsonb_build_object('run_id',r,'state','COMPLETED','idempotent',true,'items','[]'::jsonb);
 end if;
 insert into public.vault_shopify_historical_c2_reconciliation_runs(idempotency_key,requested_order_numbers,dry_run,state) values(p_idempotency_key,p_order_numbers,p_dry_run,'PREPARING') returning id into r;
 for o in select * from public.vault_shopify_orders where order_number=any(p_order_numbers) order by order_number loop
  expected:=case o.order_number when '1254' then '847ed9bf' when '1256' then '52b2f940' when '1259' then '7530aae4' when '1263' then 'd18c8c60' when '1264' then '39f3dfc2' when '1270' then 'f22b1b82' end;
  select * into c from public.vault_shopify_financial_capture_completeness_observations where source='shopify' and shopify_order_id=o.shopify_order_id and order_source_updated_at=o.shopify_updated_at and fingerprint_contract_version='shopify-source-content-v1' and discount_applications_complete and line_items_complete and refunds_complete and refund_lines_complete and refund_transactions_complete;
  if not found or (select count(*) from public.vault_shopify_financial_capture_completeness_observations where source='shopify' and shopify_order_id=o.shopify_order_id and order_source_updated_at=o.shopify_updated_at and fingerprint_contract_version='shopify-source-content-v1')<>1 then raise exception 'C2_COMPLETENESS_INVALID'; end if;
  select * into a from public.vault_shopify_discount_application_observations where source='shopify' and shopify_order_id=o.shopify_order_id and order_source_updated_at=o.shopify_updated_at and application_index=0 and completeness_source_content_fingerprint is null;
  if not found or a.evidence_mode<>'historical' or a.source_content_fingerprint<>expected or (select count(*) from public.vault_shopify_discount_application_observations where source='shopify' and shopify_order_id=o.shopify_order_id and order_source_updated_at=o.shopify_updated_at and application_index=0 and completeness_source_content_fingerprint is null)<>1 then raise exception 'C2_APPLICATION_ATTESTATION_FAILED'; end if;
  if c.discount_application_count<>1 or c.discount_allocation_count<>2 or (select count(*) from public.vault_shopify_line_discount_allocation_observations q join public.vault_shopify_order_lines l on l.order_id=o.id and l.shopify_line_item_id=q.shopify_line_item_id where q.source='shopify' and q.shopify_order_id=o.shopify_order_id and q.order_source_updated_at=o.shopify_updated_at and q.application_index=0 and q.completeness_source_content_fingerprint is null and q.evidence_mode='historical')<>2 then raise exception 'C2_ALLOCATION_OR_COMPLETENESS_COUNT_MISMATCH'; end if;
  if exists(select 1 from public.vault_shopify_discount_application_observations q where q.shopify_order_id=o.shopify_order_id and q.order_source_updated_at=o.shopify_updated_at and q.completeness_source_content_fingerprint=c.source_content_fingerprint and q.source_content_fingerprint<>a.source_content_fingerprint) then raise exception 'C2_COUNTERPART_CONFLICT'; end if;
  insert into public.vault_shopify_historical_c2_prepared_plan_items(run_id,canonical_order_id,kind,source_observation_id,completeness_observation_id,payload,expected_source_fingerprint) values(r,o.id,'APPLICATION',a.id,c.id,jsonb_build_object('source_id',a.id),a.source_content_fingerprint);
  for x in select q.*,l.id line_id from public.vault_shopify_line_discount_allocation_observations q join public.vault_shopify_order_lines l on l.order_id=o.id and l.shopify_line_item_id=q.shopify_line_item_id where q.shopify_order_id=o.shopify_order_id and q.order_source_updated_at=o.shopify_updated_at and q.application_index=0 and q.completeness_source_content_fingerprint is null order by q.id loop insert into public.vault_shopify_historical_c2_prepared_plan_items(run_id,canonical_order_id,canonical_order_line_id,kind,source_observation_id,completeness_observation_id,payload,expected_source_fingerprint) values(r,o.id,x.line_id,'ALLOCATION',x.id,c.id,jsonb_build_object('source_id',x.id),x.source_content_fingerprint); end loop;
  if o.order_number='1264' then
   if (select count(*) from public.vault_shopify_order_lines where order_id=o.id)<>3 then raise exception 'C2_1264_LINE_COUNT_INVALID'; end if;
   select l.* into line from public.vault_shopify_order_lines l where l.order_id=o.id and not exists(select 1 from public.vault_shopify_line_discount_allocation_observations q where q.shopify_order_id=o.shopify_order_id and q.order_source_updated_at=o.shopify_updated_at and q.shopify_line_item_id=l.shopify_line_item_id and q.completeness_source_content_fingerprint is null);
   if not found or (select count(*) from public.vault_shopify_order_lines l where l.order_id=o.id and not exists(select 1 from public.vault_shopify_line_discount_allocation_observations q where q.shopify_order_id=o.shopify_order_id and q.order_source_updated_at=o.shopify_updated_at and q.shopify_line_item_id=l.shopify_line_item_id and q.completeness_source_content_fingerprint is null))<>1 then raise exception 'C2_1264_ZERO_PROOF_AMBIGUOUS'; end if;
   payload:=jsonb_build_object('source','shopify','shopify_order_id',o.shopify_order_id,'shopify_line_item_id',line.shopify_line_item_id,'order_source_updated_at',to_char(o.shopify_updated_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'),'evidence_method','PROVEN_ZERO_DISCOUNT_ALLOCATION','discount_application_count',c.discount_application_count,'discount_allocation_count',c.discount_allocation_count,'completeness_source_content_fingerprint',c.source_content_fingerprint);
   -- A live zero-proof on the exact governed target is never an unrelated row.
   -- Exact repeats are handled above from completed C2 audit evidence; without
   -- that audit, this is an untrusted conflicting counterpart and must not be
   -- overwritten, duplicated, or silently repaired during prepare.
   if exists(select 1 from public.vault_shopify_line_zero_discount_allocation_observations z where z.source='shopify' and z.evidence_mode='historical' and z.shopify_order_id=o.shopify_order_id and z.shopify_line_item_id=line.shopify_line_item_id and z.order_source_updated_at=o.shopify_updated_at and z.evidence_method='PROVEN_ZERO_DISCOUNT_ALLOCATION' and z.discount_application_count=c.discount_application_count and z.discount_allocation_count=c.discount_allocation_count and z.completeness_source_content_fingerprint=c.source_content_fingerprint and z.fingerprint_contract_version='shopify-source-content-v1') then raise exception 'C2_COUNTERPART_CONFLICT'; end if;
   insert into public.vault_shopify_historical_c2_prepared_plan_items(run_id,canonical_order_id,canonical_order_line_id,kind,completeness_observation_id,payload,required_hash) values(r,o.id,line.id,'ZERO_DISCOUNT_PROOF',c.id,payload,true);
  end if;
 end loop;
 perform set_config('vault.c2_transition','on',true); update public.vault_shopify_historical_c2_reconciliation_runs set state=case when p_dry_run then 'DRY_RUN_COMPLETE' else 'PREPARED' end,completed_at=case when p_dry_run then now() end where id=r;
 return jsonb_build_object('run_id',r,'state',case when p_dry_run then 'DRY_RUN_COMPLETE' else 'PREPARED' end,'items',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'payload',p.payload)) from public.vault_shopify_historical_c2_prepared_plan_items p where p.run_id=r and p.required_hash),'[]'::jsonb));
end$$;

create function public.finalize_historical_c2_v1(p_run_id uuid,p_hashes jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare r record; p record; h text; appended uuid; supplied int; required int;
begin
 select * into r from public.vault_shopify_historical_c2_reconciliation_runs where id=p_run_id for update; if not found or r.state<>'PREPARED' or r.dry_run then raise exception 'C2_RUN_NOT_FINALIZABLE'; end if;
 if jsonb_typeof(p_hashes)<>'array' then raise exception 'C2_FINALIZE_HASHES_INVALID'; end if; select count(*) into supplied from jsonb_array_elements(p_hashes); select count(*) into required from public.vault_shopify_historical_c2_prepared_plan_items where run_id=p_run_id and required_hash; if supplied<>required or supplied<>(select count(distinct x->>'id') from jsonb_array_elements(p_hashes)x) then raise exception 'C2_FINALIZE_ITEM_COUNT_MISMATCH'; end if;
 perform set_config('vault.c2_transition','on',true); update public.vault_shopify_historical_c2_reconciliation_runs set state='FINALIZING' where id=p_run_id;
 for p in select * from public.vault_shopify_historical_c2_prepared_plan_items where run_id=p_run_id order by kind,id loop
  h:=case when p.required_hash then (select x->>'fingerprint' from jsonb_array_elements(p_hashes)x where (x->>'id')::uuid=p.id) else p.expected_source_fingerprint end; if h is null or h !~ '^[0-9a-f]{1,8}$' then raise exception 'C2_FINALIZE_HASH_MISMATCH'; end if;
  if p.kind='APPLICATION' then insert into public.vault_shopify_discount_application_observations(source,evidence_mode,shopify_order_id,application_index,order_source_updated_at,application_type,code,title,description,allocation_method,target_selection,target_type,pricing_value_type,pricing_value,pricing_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint,completeness_source_content_fingerprint) select s.source,'historical',s.shopify_order_id,s.application_index,s.order_source_updated_at,s.application_type,s.code,s.title,s.description,s.allocation_method,s.target_selection,s.target_type,s.pricing_value_type,s.pricing_value,s.pricing_currency,now(),h,'shopify-source-content-v1',h,c.source_content_fingerprint from public.vault_shopify_discount_application_observations s join public.vault_shopify_financial_capture_completeness_observations c on c.id=p.completeness_observation_id where s.id=p.source_observation_id returning id into appended;
  elsif p.kind='ALLOCATION' then insert into public.vault_shopify_line_discount_allocation_observations(source,evidence_mode,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at,allocated_shop_amount,allocated_shop_currency,allocated_presentment_amount,allocated_presentment_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint,completeness_source_content_fingerprint) select s.source,'historical',s.shopify_order_id,s.shopify_line_item_id,s.application_index,s.order_source_updated_at,s.allocated_shop_amount,s.allocated_shop_currency,s.allocated_presentment_amount,s.allocated_presentment_currency,now(),h,'shopify-source-content-v1',h,c.source_content_fingerprint from public.vault_shopify_line_discount_allocation_observations s join public.vault_shopify_financial_capture_completeness_observations c on c.id=p.completeness_observation_id where s.id=p.source_observation_id returning id into appended;
  else insert into public.vault_shopify_line_zero_discount_allocation_observations(source,evidence_mode,shopify_order_id,shopify_line_item_id,order_source_updated_at,evidence_method,discount_application_count,discount_allocation_count,completeness_source_content_fingerprint,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint) values('shopify','historical',p.payload->>'shopify_order_id',p.payload->>'shopify_line_item_id',(p.payload->>'order_source_updated_at')::timestamptz,'PROVEN_ZERO_DISCOUNT_ALLOCATION',(p.payload->>'discount_application_count')::int,(p.payload->>'discount_allocation_count')::int,p.payload->>'completeness_source_content_fingerprint',now(),h,'shopify-source-content-v1',h) returning id into appended; end if;
  insert into public.vault_shopify_historical_c2_reconciliation_evidence(run_id,plan_item_id,canonical_order_id,canonical_order_line_id,evidence_kind,source_observation_id,appended_observation_id,completeness_observation_id,source_content_fingerprint) values(p_run_id,p.id,p.canonical_order_id,p.canonical_order_line_id,p.kind,p.source_observation_id,appended,p.completeness_observation_id,h);
 end loop;
 perform set_config('vault.c2_transition','on',true); update public.vault_shopify_historical_c2_reconciliation_runs set state='COMPLETED',completed_at=now() where id=p_run_id; return jsonb_build_object('run_id',p_run_id,'state','COMPLETED');
end$$;
create function public.attest_historical_c2_v1_fingerprint(p_run_id uuid,p_plan_item_id uuid,p_fingerprint text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing text;
begin
 if p_fingerprint !~ '^[0-9a-f]{1,8}$' then raise exception 'C2_HASH_ATTESTATION_INVALID'; end if;
 if not exists(select 1 from public.vault_shopify_historical_c2_reconciliation_runs where id=p_run_id and state='PREPARED' and not dry_run) then raise exception 'C2_RUN_NOT_ATTESTABLE'; end if;
 if not exists(select 1 from public.vault_shopify_historical_c2_prepared_plan_items where id=p_plan_item_id and run_id=p_run_id and required_hash) then raise exception 'C2_PLAN_ITEM_NOT_ATTESTABLE'; end if;
 select fingerprint into existing from public.vault_shopify_historical_c2_hash_attestations where plan_item_id=p_plan_item_id;
 if found then if existing<>p_fingerprint then raise exception 'C2_HASH_ATTESTATION_CONFLICT'; end if; return jsonb_build_object('plan_item_id',p_plan_item_id,'attested',true,'idempotent',true); end if;
 insert into public.vault_shopify_historical_c2_hash_attestations(plan_item_id,fingerprint) values(p_plan_item_id,p_fingerprint);
 return jsonb_build_object('plan_item_id',p_plan_item_id,'attested',true,'idempotent',false);
end$$;
drop function public.finalize_historical_c2_v1(uuid,jsonb);
create function public.finalize_historical_c2_v1(p_run_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare r record; p record; h text; appended uuid;
begin
 select * into r from public.vault_shopify_historical_c2_reconciliation_runs where id=p_run_id for update; if not found or r.state<>'PREPARED' or r.dry_run then raise exception 'C2_RUN_NOT_FINALIZABLE'; end if;
 if exists(select 1 from public.vault_shopify_historical_c2_prepared_plan_items pi left join public.vault_shopify_historical_c2_hash_attestations a on a.plan_item_id=pi.id where pi.run_id=p_run_id and pi.required_hash and a.plan_item_id is null) then raise exception 'C2_HASH_ATTESTATION_MISSING'; end if;
 perform set_config('vault.c2_transition','on',true); update public.vault_shopify_historical_c2_reconciliation_runs set state='FINALIZING' where id=p_run_id;
 for p in select * from public.vault_shopify_historical_c2_prepared_plan_items where run_id=p_run_id order by kind,id loop
  h:=case when p.required_hash then (select fingerprint from public.vault_shopify_historical_c2_hash_attestations where plan_item_id=p.id) else p.expected_source_fingerprint end;
  if p.kind='APPLICATION' then insert into public.vault_shopify_discount_application_observations(source,evidence_mode,shopify_order_id,application_index,order_source_updated_at,application_type,code,title,description,allocation_method,target_selection,target_type,pricing_value_type,pricing_value,pricing_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint,completeness_source_content_fingerprint) select s.source,'historical',s.shopify_order_id,s.application_index,s.order_source_updated_at,s.application_type,s.code,s.title,s.description,s.allocation_method,s.target_selection,s.target_type,s.pricing_value_type,s.pricing_value,s.pricing_currency,now(),h,'shopify-source-content-v1',h,c.source_content_fingerprint from public.vault_shopify_discount_application_observations s join public.vault_shopify_financial_capture_completeness_observations c on c.id=p.completeness_observation_id where s.id=p.source_observation_id returning id into appended;
  elsif p.kind='ALLOCATION' then insert into public.vault_shopify_line_discount_allocation_observations(source,evidence_mode,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at,allocated_shop_amount,allocated_shop_currency,allocated_presentment_amount,allocated_presentment_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint,completeness_source_content_fingerprint) select s.source,'historical',s.shopify_order_id,s.shopify_line_item_id,s.application_index,s.order_source_updated_at,s.allocated_shop_amount,s.allocated_shop_currency,s.allocated_presentment_amount,s.allocated_presentment_currency,now(),h,'shopify-source-content-v1',h,c.source_content_fingerprint from public.vault_shopify_line_discount_allocation_observations s join public.vault_shopify_financial_capture_completeness_observations c on c.id=p.completeness_observation_id where s.id=p.source_observation_id returning id into appended;
  else insert into public.vault_shopify_line_zero_discount_allocation_observations(source,evidence_mode,shopify_order_id,shopify_line_item_id,order_source_updated_at,evidence_method,discount_application_count,discount_allocation_count,completeness_source_content_fingerprint,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint) values('shopify','historical',p.payload->>'shopify_order_id',p.payload->>'shopify_line_item_id',(p.payload->>'order_source_updated_at')::timestamptz,'PROVEN_ZERO_DISCOUNT_ALLOCATION',(p.payload->>'discount_application_count')::int,(p.payload->>'discount_allocation_count')::int,p.payload->>'completeness_source_content_fingerprint',now(),h,'shopify-source-content-v1',h) returning id into appended; end if;
  insert into public.vault_shopify_historical_c2_reconciliation_evidence(run_id,plan_item_id,canonical_order_id,canonical_order_line_id,evidence_kind,source_observation_id,appended_observation_id,completeness_observation_id,source_content_fingerprint) values(p_run_id,p.id,p.canonical_order_id,p.canonical_order_line_id,p.kind,p.source_observation_id,appended,p.completeness_observation_id,h);
 end loop;
 perform set_config('vault.c2_transition','on',true); update public.vault_shopify_historical_c2_reconciliation_runs set state='COMPLETED',completed_at=now() where id=p_run_id; return jsonb_build_object('run_id',p_run_id,'state','COMPLETED');
end$$;
revoke all on function public.prepare_historical_c2_v1(text[],boolean,text),public.attest_historical_c2_v1_fingerprint(uuid,uuid,text),public.finalize_historical_c2_v1(uuid) from public,anon,authenticated;
grant execute on function public.prepare_historical_c2_v1(text[],boolean,text),public.attest_historical_c2_v1_fingerprint(uuid,uuid,text),public.finalize_historical_c2_v1(uuid) to service_role;
notify pgrst,'reload schema'; commit;
