-- Commercial C2: source-content fingerprint v1 extending 20261022000000. Legacy full-row fingerprints remain immutable.
-- No existing financial evidence is updated, backfilled, or reclassified.
do $$
declare relation_name text;
begin
  foreach relation_name in array array[
    'vault_shopify_discount_application_observations',
    'vault_shopify_line_discount_allocation_observations',
    'vault_shopify_refund_observations',
    'vault_shopify_refund_line_observations',
    'vault_shopify_refund_transaction_observations'
  ] loop
    execute format('alter table public.%I add column if not exists fingerprint_contract_version text not null default ''legacy-full-row-v1'' check (fingerprint_contract_version in (''legacy-full-row-v1'',''shopify-source-content-v1''))', relation_name);
    execute format('alter table public.%I add column if not exists source_content_fingerprint text', relation_name);
    execute format('alter table public.%I add constraint %I check ((fingerprint_contract_version = ''legacy-full-row-v1'' and source_content_fingerprint is null) or (fingerprint_contract_version = ''shopify-source-content-v1'' and source_content_fingerprint is not null))', relation_name, relation_name || '_fingerprint_contract_check');
  end loop;
end $$;

create or replace function public.record_shopify_financial_evidence(payload jsonb, capture_mode text)
returns void language plpgsql security definer set search_path='' as $$
declare prospective boolean := capture_mode = 'prospective'; observed timestamptz;
begin
 if capture_mode not in ('prospective','historical') or jsonb_typeof(payload) <> 'object' or payload->>'capture_mode' is distinct from capture_mode then raise exception 'INVALID_FINANCIAL_CAPTURE'; end if;
 observed := (payload->>'observed_at')::timestamptz;
 if observed is null or observed > clock_timestamp()+interval '1 minute' then raise exception 'INVALID_FINANCIAL_OBSERVED_AT'; end if;
 -- Same source version must either be equivalent source content or fail closed. Evidence mode and observed_at are governance/ingestion metadata, not source content.
 if exists (select 1 from jsonb_to_recordset(coalesce(payload->'applications','[]')) as x(source text,evidence_mode text,shopify_order_id text,application_index int,order_source_updated_at timestamptz,application_type text,code text,title text,description text,allocation_method text,target_selection text,target_type text,pricing_value_type text,pricing_value numeric,pricing_currency text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text)
   join public.vault_shopify_discount_application_observations e using(source,shopify_order_id,application_index,order_source_updated_at) where x.fingerprint_contract_version <> 'shopify-source-content-v1' or (e.fingerprint_contract_version='shopify-source-content-v1' and e.source_content_fingerprint is distinct from x.source_content_fingerprint) or (e.fingerprint_contract_version='legacy-full-row-v1' and (e.application_type,e.code,e.title,e.description,e.allocation_method,e.target_selection,e.target_type,e.pricing_value_type,e.pricing_value,e.pricing_currency) is distinct from (x.application_type,x.code,x.title,x.description,x.allocation_method,x.target_selection,x.target_type,x.pricing_value_type,x.pricing_value,x.pricing_currency)) or e.fingerprint_contract_version not in ('legacy-full-row-v1','shopify-source-content-v1'))
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'allocations','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_line_item_id text,application_index int,order_source_updated_at timestamptz,allocated_shop_amount numeric,allocated_shop_currency text,allocated_presentment_amount numeric,allocated_presentment_currency text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text)
   join public.vault_shopify_line_discount_allocation_observations e using(source,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at) where x.fingerprint_contract_version <> 'shopify-source-content-v1' or (e.fingerprint_contract_version='shopify-source-content-v1' and e.source_content_fingerprint is distinct from x.source_content_fingerprint) or (e.fingerprint_contract_version='legacy-full-row-v1' and (e.allocated_shop_amount,e.allocated_shop_currency,e.allocated_presentment_amount,e.allocated_presentment_currency) is distinct from (x.allocated_shop_amount,x.allocated_shop_currency,x.allocated_presentment_amount,x.allocated_presentment_currency)) or e.fingerprint_contract_version not in ('legacy-full-row-v1','shopify-source-content-v1'))
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'refunds','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,refund_created_at timestamptz,refund_source_updated_at timestamptz,refund_processed_at timestamptz,total_refunded_amount numeric,currency text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text)
   join public.vault_shopify_refund_observations e using(source,shopify_refund_id,refund_source_updated_at) where x.fingerprint_contract_version <> 'shopify-source-content-v1' or (e.fingerprint_contract_version='shopify-source-content-v1' and e.source_content_fingerprint is distinct from x.source_content_fingerprint) or (e.fingerprint_contract_version='legacy-full-row-v1' and (e.shopify_order_id,e.refund_created_at,e.refund_processed_at,e.total_refunded_amount,e.currency) is distinct from (x.shopify_order_id,x.refund_created_at,x.refund_processed_at,x.total_refunded_amount,x.currency)) or e.fingerprint_contract_version not in ('legacy-full-row-v1','shopify-source-content-v1'))
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'refund_lines','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,shopify_refund_line_item_id text,shopify_line_item_id text,refund_source_updated_at timestamptz,quantity int,price_amount numeric,subtotal_amount numeric,tax_amount numeric,currency text,restocked boolean,restock_type text,restock_location_id text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text)
   join public.vault_shopify_refund_line_observations e using(source,shopify_refund_id,shopify_refund_line_item_id,refund_source_updated_at) where x.fingerprint_contract_version <> 'shopify-source-content-v1' or (e.fingerprint_contract_version='shopify-source-content-v1' and e.source_content_fingerprint is distinct from x.source_content_fingerprint) or (e.fingerprint_contract_version='legacy-full-row-v1' and (e.shopify_order_id,e.shopify_line_item_id,e.quantity,e.price_amount,e.subtotal_amount,e.tax_amount,e.currency,e.restocked,e.restock_type,e.restock_location_id) is distinct from (x.shopify_order_id,x.shopify_line_item_id,x.quantity,x.price_amount,x.subtotal_amount,x.tax_amount,x.currency,x.restocked,x.restock_type,x.restock_location_id)) or e.fingerprint_contract_version not in ('legacy-full-row-v1','shopify-source-content-v1'))
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'refund_transactions','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,shopify_order_transaction_id text,parent_transaction_id text,refund_source_updated_at timestamptz,transaction_kind text,transaction_status text,gateway text,amount numeric,currency text,transaction_created_at timestamptz,processed_at timestamptz,is_test boolean,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text)
   join public.vault_shopify_refund_transaction_observations e using(source,shopify_order_transaction_id,refund_source_updated_at) where x.fingerprint_contract_version <> 'shopify-source-content-v1' or (e.fingerprint_contract_version='shopify-source-content-v1' and e.source_content_fingerprint is distinct from x.source_content_fingerprint) or (e.fingerprint_contract_version='legacy-full-row-v1' and (e.shopify_order_id,e.shopify_refund_id,e.parent_transaction_id,e.transaction_kind,e.transaction_status,e.gateway,e.amount,e.currency,e.transaction_created_at,e.processed_at,e.is_test) is distinct from (x.shopify_order_id,x.shopify_refund_id,x.parent_transaction_id,x.transaction_kind,x.transaction_status,x.gateway,x.amount,x.currency,x.transaction_created_at,x.processed_at,x.is_test)) or e.fingerprint_contract_version not in ('legacy-full-row-v1','shopify-source-content-v1'))
 then raise exception 'FINANCIAL_SOURCE_VERSION_CONFLICT'; end if;
 insert into public.vault_shopify_discount_application_observations(source,evidence_mode,shopify_order_id,application_index,order_source_updated_at,application_type,code,title,description,allocation_method,target_selection,target_type,pricing_value_type,pricing_value,pricing_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint)
 select source,evidence_mode,shopify_order_id,application_index,order_source_updated_at,application_type,code,title,description,allocation_method,target_selection,target_type,pricing_value_type,pricing_value,pricing_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint from jsonb_to_recordset(coalesce(payload->'applications','[]')) as x(source text,evidence_mode text,shopify_order_id text,application_index int,order_source_updated_at timestamptz,application_type text,code text,title text,description text,allocation_method text,target_selection text,target_type text,pricing_value_type text,pricing_value numeric,pricing_currency text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_line_discount_allocation_observations(source,evidence_mode,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at,allocated_shop_amount,allocated_shop_currency,allocated_presentment_amount,allocated_presentment_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at,allocated_shop_amount,allocated_shop_currency,allocated_presentment_amount,allocated_presentment_currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint from jsonb_to_recordset(coalesce(payload->'allocations','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_line_item_id text,application_index int,order_source_updated_at timestamptz,allocated_shop_amount numeric,allocated_shop_currency text,allocated_presentment_amount numeric,allocated_presentment_currency text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_refund_observations(source,evidence_mode,shopify_order_id,shopify_refund_id,refund_created_at,refund_source_updated_at,refund_processed_at,total_refunded_amount,currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_refund_id,refund_created_at,refund_source_updated_at,refund_processed_at,total_refunded_amount,currency,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint from jsonb_to_recordset(coalesce(payload->'refunds','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,refund_created_at timestamptz,refund_source_updated_at timestamptz,refund_processed_at timestamptz,total_refunded_amount numeric,currency text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_refund_line_observations(source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_refund_line_item_id,shopify_line_item_id,refund_source_updated_at,quantity,price_amount,subtotal_amount,tax_amount,currency,restocked,restock_type,restock_location_id,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_refund_line_item_id,shopify_line_item_id,refund_source_updated_at,quantity,price_amount,subtotal_amount,tax_amount,currency,restocked,restock_type,restock_location_id,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint from jsonb_to_recordset(coalesce(payload->'refund_lines','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,shopify_refund_line_item_id text,shopify_line_item_id text,refund_source_updated_at timestamptz,quantity int,price_amount numeric,subtotal_amount numeric,tax_amount numeric,currency text,restocked boolean,restock_type text,restock_location_id text,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_refund_transaction_observations(source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_order_transaction_id,parent_transaction_id,refund_source_updated_at,transaction_kind,transaction_status,gateway,amount,currency,transaction_created_at,processed_at,is_test,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_order_transaction_id,parent_transaction_id,refund_source_updated_at,transaction_kind,transaction_status,gateway,amount,currency,transaction_created_at,processed_at,is_test,observed_at,payload_fingerprint,fingerprint_contract_version,source_content_fingerprint from jsonb_to_recordset(coalesce(payload->'refund_transactions','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,shopify_order_transaction_id text,parent_transaction_id text,refund_source_updated_at timestamptz,transaction_kind text,transaction_status text,gateway text,amount numeric,currency text,transaction_created_at timestamptz,processed_at timestamptz,is_test boolean,observed_at timestamptz,payload_fingerprint text,fingerprint_contract_version text,source_content_fingerprint text) on conflict do nothing;
 if prospective then update public.vault_shopify_financial_evidence_governance set prospective_started_at=observed where singleton and prospective_started_at is null; end if;
end $$;

revoke all on function public.record_shopify_financial_evidence(jsonb,text) from public,anon,authenticated;
grant execute on function public.record_shopify_financial_evidence(jsonb,text) to service_role;
comment on column public.vault_shopify_discount_application_observations.source_content_fingerprint is 'Canonical Shopify source-content fingerprint. Excludes observation and governance metadata.';
notify pgrst,'reload schema';
