-- Commercial C2: immutable Shopify financial evidence. No profit calculation.
create table public.vault_shopify_financial_evidence_governance (
  singleton boolean primary key default true check (singleton), prospective_started_at timestamptz,
  created_at timestamptz not null default now()
);
insert into public.vault_shopify_financial_evidence_governance(singleton) values(true) on conflict do nothing;
create table public.vault_shopify_discount_application_observations (
 id uuid primary key default gen_random_uuid(), source text not null default 'shopify' check(source='shopify'), evidence_mode text not null check(evidence_mode in ('prospective','historical')), shopify_order_id text not null, application_index integer not null check(application_index>=0), order_source_updated_at timestamptz not null, application_type text not null, code text, title text, description text, allocation_method text not null, target_selection text not null, target_type text not null, pricing_value_type text not null, pricing_value numeric, pricing_currency text, observed_at timestamptz not null, payload_fingerprint text not null, created_at timestamptz not null default now(), unique(source,shopify_order_id,application_index,order_source_updated_at));
create table public.vault_shopify_line_discount_allocation_observations (
 id uuid primary key default gen_random_uuid(), source text not null default 'shopify' check(source='shopify'), evidence_mode text not null check(evidence_mode in ('prospective','historical')), shopify_order_id text not null, shopify_line_item_id text not null, application_index integer not null check(application_index>=0), order_source_updated_at timestamptz not null, allocated_shop_amount numeric not null, allocated_shop_currency text not null, allocated_presentment_amount numeric, allocated_presentment_currency text, observed_at timestamptz not null, payload_fingerprint text not null, created_at timestamptz not null default now(), unique(source,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at));
create table public.vault_shopify_refund_observations (
 id uuid primary key default gen_random_uuid(), source text not null default 'shopify' check(source='shopify'), evidence_mode text not null check(evidence_mode in ('prospective','historical')), shopify_order_id text not null, shopify_refund_id text not null, refund_created_at timestamptz not null, refund_source_updated_at timestamptz not null, refund_processed_at timestamptz, total_refunded_amount numeric not null, currency text not null, observed_at timestamptz not null, payload_fingerprint text not null, created_at timestamptz not null default now(), unique(source,shopify_refund_id,refund_source_updated_at));
create table public.vault_shopify_refund_line_observations (
 id uuid primary key default gen_random_uuid(), source text not null default 'shopify' check(source='shopify'), evidence_mode text not null check(evidence_mode in ('prospective','historical')), shopify_order_id text not null, shopify_refund_id text not null, shopify_refund_line_item_id text not null, shopify_line_item_id text, refund_source_updated_at timestamptz not null, quantity integer not null check(quantity>=0), price_amount numeric not null, subtotal_amount numeric not null, tax_amount numeric not null, currency text not null, restocked boolean not null, restock_type text not null, restock_location_id text, observed_at timestamptz not null, payload_fingerprint text not null, created_at timestamptz not null default now(), unique(source,shopify_refund_id,shopify_refund_line_item_id,refund_source_updated_at));
create table public.vault_shopify_refund_transaction_observations (
 id uuid primary key default gen_random_uuid(), source text not null default 'shopify' check(source='shopify'), evidence_mode text not null check(evidence_mode in ('prospective','historical')), shopify_order_id text not null, shopify_refund_id text not null, shopify_order_transaction_id text not null, parent_transaction_id text, refund_source_updated_at timestamptz not null, transaction_kind text not null, transaction_status text not null, gateway text, amount numeric not null, currency text not null, transaction_created_at timestamptz not null, processed_at timestamptz, is_test boolean not null, observed_at timestamptz not null, payload_fingerprint text not null, created_at timestamptz not null default now(), unique(source,shopify_order_transaction_id,refund_source_updated_at));
create index vault_financial_discount_order_idx on public.vault_shopify_discount_application_observations(shopify_order_id,order_source_updated_at desc);
create index vault_financial_refund_order_idx on public.vault_shopify_refund_observations(shopify_order_id,refund_created_at);
create function public.reject_shopify_financial_evidence_mutation() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'Shopify financial evidence is append-only'; end $$;
create function public.guard_financial_evidence_boundary() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='DELETE' or old.prospective_started_at is not null or new.prospective_started_at is null then raise exception 'Financial evidence boundary is immutable'; end if; return new; end $$;
create trigger financial_boundary_immutable before update or delete on public.vault_shopify_financial_evidence_governance for each row execute function public.guard_financial_evidence_boundary();
create trigger financial_discount_immutable before update or delete on public.vault_shopify_discount_application_observations for each row execute function public.reject_shopify_financial_evidence_mutation();
create trigger financial_allocation_immutable before update or delete on public.vault_shopify_line_discount_allocation_observations for each row execute function public.reject_shopify_financial_evidence_mutation();
create trigger financial_refund_immutable before update or delete on public.vault_shopify_refund_observations for each row execute function public.reject_shopify_financial_evidence_mutation();
create trigger financial_refund_line_immutable before update or delete on public.vault_shopify_refund_line_observations for each row execute function public.reject_shopify_financial_evidence_mutation();
create trigger financial_refund_tx_immutable before update or delete on public.vault_shopify_refund_transaction_observations for each row execute function public.reject_shopify_financial_evidence_mutation();
alter table public.vault_shopify_financial_evidence_governance enable row level security; alter table public.vault_shopify_discount_application_observations enable row level security; alter table public.vault_shopify_line_discount_allocation_observations enable row level security; alter table public.vault_shopify_refund_observations enable row level security; alter table public.vault_shopify_refund_line_observations enable row level security; alter table public.vault_shopify_refund_transaction_observations enable row level security;
revoke all on public.vault_shopify_financial_evidence_governance,public.vault_shopify_discount_application_observations,public.vault_shopify_line_discount_allocation_observations,public.vault_shopify_refund_observations,public.vault_shopify_refund_line_observations,public.vault_shopify_refund_transaction_observations from anon,authenticated;
grant select,insert on public.vault_shopify_financial_evidence_governance,public.vault_shopify_discount_application_observations,public.vault_shopify_line_discount_allocation_observations,public.vault_shopify_refund_observations,public.vault_shopify_refund_line_observations,public.vault_shopify_refund_transaction_observations to service_role;
create function public.record_shopify_financial_evidence(payload jsonb, capture_mode text)
returns void language plpgsql security definer set search_path='' as $$
declare prospective boolean := capture_mode = 'prospective'; observed timestamptz;
begin
 if capture_mode not in ('prospective','historical') or jsonb_typeof(payload) <> 'object' or payload->>'capture_mode' is distinct from capture_mode then raise exception 'INVALID_FINANCIAL_CAPTURE'; end if;
 observed := (payload->>'observed_at')::timestamptz;
 if observed is null or observed > clock_timestamp()+interval '1 minute' then raise exception 'INVALID_FINANCIAL_OBSERVED_AT'; end if;
 if exists (select 1 from jsonb_to_recordset(coalesce(payload->'applications','[]')) as x(source text,shopify_order_id text,application_index int,order_source_updated_at timestamptz,payload_fingerprint text)
   join public.vault_shopify_discount_application_observations e using(source,shopify_order_id,application_index,order_source_updated_at) where e.payload_fingerprint<>x.payload_fingerprint)
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'allocations','[]')) as x(source text,shopify_order_id text,shopify_line_item_id text,application_index int,order_source_updated_at timestamptz,payload_fingerprint text)
   join public.vault_shopify_line_discount_allocation_observations e using(source,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at) where e.payload_fingerprint<>x.payload_fingerprint)
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'refunds','[]')) as x(source text,shopify_refund_id text,refund_source_updated_at timestamptz,payload_fingerprint text)
   join public.vault_shopify_refund_observations e using(source,shopify_refund_id,refund_source_updated_at) where e.payload_fingerprint<>x.payload_fingerprint)
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'refund_lines','[]')) as x(source text,shopify_refund_id text,shopify_refund_line_item_id text,refund_source_updated_at timestamptz,payload_fingerprint text)
   join public.vault_shopify_refund_line_observations e using(source,shopify_refund_id,shopify_refund_line_item_id,refund_source_updated_at) where e.payload_fingerprint<>x.payload_fingerprint)
 or exists (select 1 from jsonb_to_recordset(coalesce(payload->'refund_transactions','[]')) as x(source text,shopify_order_transaction_id text,refund_source_updated_at timestamptz,payload_fingerprint text)
   join public.vault_shopify_refund_transaction_observations e using(source,shopify_order_transaction_id,refund_source_updated_at) where e.payload_fingerprint<>x.payload_fingerprint)
then raise exception 'FINANCIAL_SOURCE_VERSION_CONFLICT'; end if;
 insert into public.vault_shopify_discount_application_observations(source,evidence_mode,shopify_order_id,application_index,order_source_updated_at,application_type,code,title,description,allocation_method,target_selection,target_type,pricing_value_type,pricing_value,pricing_currency,observed_at,payload_fingerprint)
 select source,evidence_mode,shopify_order_id,application_index,order_source_updated_at,application_type,code,title,description,allocation_method,target_selection,target_type,pricing_value_type,pricing_value,pricing_currency,observed_at,payload_fingerprint from jsonb_to_recordset(coalesce(payload->'applications','[]')) as x(source text,evidence_mode text,shopify_order_id text,application_index int,order_source_updated_at timestamptz,application_type text,code text,title text,description text,allocation_method text,target_selection text,target_type text,pricing_value_type text,pricing_value numeric,pricing_currency text,observed_at timestamptz,payload_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_line_discount_allocation_observations(source,evidence_mode,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at,allocated_shop_amount,allocated_shop_currency,allocated_presentment_amount,allocated_presentment_currency,observed_at,payload_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at,allocated_shop_amount,allocated_shop_currency,allocated_presentment_amount,allocated_presentment_currency,observed_at,payload_fingerprint from jsonb_to_recordset(coalesce(payload->'allocations','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_line_item_id text,application_index int,order_source_updated_at timestamptz,allocated_shop_amount numeric,allocated_shop_currency text,allocated_presentment_amount numeric,allocated_presentment_currency text,observed_at timestamptz,payload_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_refund_observations(source,evidence_mode,shopify_order_id,shopify_refund_id,refund_created_at,refund_source_updated_at,refund_processed_at,total_refunded_amount,currency,observed_at,payload_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_refund_id,refund_created_at,refund_source_updated_at,refund_processed_at,total_refunded_amount,currency,observed_at,payload_fingerprint from jsonb_to_recordset(coalesce(payload->'refunds','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,refund_created_at timestamptz,refund_source_updated_at timestamptz,refund_processed_at timestamptz,total_refunded_amount numeric,currency text,observed_at timestamptz,payload_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_refund_line_observations(source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_refund_line_item_id,shopify_line_item_id,refund_source_updated_at,quantity,price_amount,subtotal_amount,tax_amount,currency,restocked,restock_type,restock_location_id,observed_at,payload_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_refund_line_item_id,shopify_line_item_id,refund_source_updated_at,quantity,price_amount,subtotal_amount,tax_amount,currency,restocked,restock_type,restock_location_id,observed_at,payload_fingerprint from jsonb_to_recordset(coalesce(payload->'refund_lines','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,shopify_refund_line_item_id text,shopify_line_item_id text,refund_source_updated_at timestamptz,quantity int,price_amount numeric,subtotal_amount numeric,tax_amount numeric,currency text,restocked boolean,restock_type text,restock_location_id text,observed_at timestamptz,payload_fingerprint text) on conflict do nothing;
 insert into public.vault_shopify_refund_transaction_observations(source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_order_transaction_id,parent_transaction_id,refund_source_updated_at,transaction_kind,transaction_status,gateway,amount,currency,transaction_created_at,processed_at,is_test,observed_at,payload_fingerprint)
 select source,evidence_mode,shopify_order_id,shopify_refund_id,shopify_order_transaction_id,parent_transaction_id,refund_source_updated_at,transaction_kind,transaction_status,gateway,amount,currency,transaction_created_at,processed_at,is_test,observed_at,payload_fingerprint from jsonb_to_recordset(coalesce(payload->'refund_transactions','[]')) as x(source text,evidence_mode text,shopify_order_id text,shopify_refund_id text,shopify_order_transaction_id text,parent_transaction_id text,refund_source_updated_at timestamptz,transaction_kind text,transaction_status text,gateway text,amount numeric,currency text,transaction_created_at timestamptz,processed_at timestamptz,is_test boolean,observed_at timestamptz,payload_fingerprint text) on conflict do nothing;
 if prospective then update public.vault_shopify_financial_evidence_governance set prospective_started_at=observed where singleton and prospective_started_at is null; end if;
end $$;
revoke all on function public.record_shopify_financial_evidence(jsonb,text) from public,anon,authenticated; grant execute on function public.record_shopify_financial_evidence(jsonb,text) to service_role;
create view public.vault_shopify_financial_discount_application_latest with(security_barrier=true) as select distinct on(source,shopify_order_id,application_index) * from public.vault_shopify_discount_application_observations order by source,shopify_order_id,application_index,order_source_updated_at desc,created_at desc;
create view public.vault_shopify_financial_line_discount_allocation_latest with(security_barrier=true) as select distinct on(source,shopify_order_id,shopify_line_item_id,application_index) * from public.vault_shopify_line_discount_allocation_observations order by source,shopify_order_id,shopify_line_item_id,application_index,order_source_updated_at desc,created_at desc;
create view public.vault_shopify_financial_refund_latest with(security_barrier=true) as select distinct on(source,shopify_refund_id) * from public.vault_shopify_refund_observations order by source,shopify_refund_id,refund_source_updated_at desc,created_at desc;
create view public.vault_shopify_financial_refund_line_latest with(security_barrier=true) as select distinct on(source,shopify_refund_id,shopify_refund_line_item_id) * from public.vault_shopify_refund_line_observations order by source,shopify_refund_id,shopify_refund_line_item_id,refund_source_updated_at desc,created_at desc;
create view public.vault_shopify_financial_refund_transaction_latest with(security_barrier=true) as select distinct on(source,shopify_order_transaction_id) * from public.vault_shopify_refund_transaction_observations order by source,shopify_order_transaction_id,refund_source_updated_at desc,created_at desc;
create view public.vault_shopify_financial_refund_reconciliation with(security_barrier=true) as select r.shopify_order_id,r.shopify_refund_id,r.total_refunded_amount,r.currency,coalesce(sum(l.subtotal_amount),0) as line_merchandise_refunded,coalesce(sum(l.tax_amount),0) as line_tax_refunded,case when count(l.id)=0 then 'no_refund_lines' when sum(l.subtotal_amount+l.tax_amount)>r.total_refunded_amount then 'component_exceeds_refund_total' when sum(l.subtotal_amount+l.tax_amount)=r.total_refunded_amount then 'reconciled' else 'additional_components_or_transactions' end as reconciliation_state from public.vault_shopify_financial_refund_latest r left join public.vault_shopify_financial_refund_line_latest l on l.source=r.source and l.shopify_refund_id=r.shopify_refund_id group by r.shopify_order_id,r.shopify_refund_id,r.total_refunded_amount,r.currency;
revoke all on public.vault_shopify_financial_discount_application_latest,public.vault_shopify_financial_line_discount_allocation_latest,public.vault_shopify_financial_refund_latest,public.vault_shopify_financial_refund_line_latest,public.vault_shopify_financial_refund_transaction_latest,public.vault_shopify_financial_refund_reconciliation from anon,authenticated;
notify pgrst,'reload schema';
